version: '3'
services:
  mysql:
    container_name: asset-db
    image: mysql:8.0.33-oracle
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=asset-db
      - TZ="Asia/Seoul"
    ports:
      - "4343:3306"
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    stdin_open: true # `-i`
    tty: true # `-t`