insert into product(id, name, corp_id, p_type) value(330, '미래에셋TIGER필라델피아반도체레버리지증권상장지수투자신탁(주식혼합-파생형)(합성)', 60, 'FUND')
insert into fund_product(id, price) value(330, 26382.79)
insert into product(id, name, corp_id, p_type) value(331, '미래에셋TIGER미국나스닥100레버리지증권상장지수투자신탁(주식혼합-파생형)(합성)', 60, 'FUND')
insert into fund_product(id, price) value(331, 19057.81)
insert into product(id, name, corp_id, p_type) value(332, '미래에셋인디아인프라섹터증권모투자신탁(주식)', 60, 'FUND')
insert into fund_product(id, price) value(332, 2775.85)
insert into product(id, name, corp_id, p_type) value(333, '미래에셋연금인디아인프라증권자투자신탁 1(주식)', 60, 'FUND')
insert into fund_product(id, price) value(333, 1130.22)
insert into product(id, name, corp_id, p_type) value(334, '미래에셋인디아인프라섹터증권자투자신탁 1(주식)', 60, 'FUND')
insert into fund_product(id, price) value(334, 3060.99)
insert into product(id, name, corp_id, p_type) value(335, '미래에셋TIGER필라델피아반도체레버리지증권상장지수투자신탁(주식혼합-파생형)(합성)', 60, 'FUND')
insert into fund_product(id, price) value(335, 26382.79)
insert into product(id, name, corp_id, p_type) value(336, '미래에셋TIGER미국나스닥100레버리지증권상장지수투자신탁(주식혼합-파생형)(합성)', 60, 'FUND')
insert into fund_product(id, price) value(336, 19057.81)
insert into product(id, name, corp_id, p_type) value(337, '미래에셋인디아인프라섹터증권모투자신탁(주식)', 60, 'FUND')
insert into fund_product(id, price) value(337, 2775.85)
insert into product(id, name, corp_id, p_type) value(338, '미래에셋연금인디아인프라증권자투자신탁 1(주식)', 60, 'FUND')
insert into fund_product(id, price) value(338, 1130.22)
insert into product(id, name, corp_id, p_type) value(339, '미래에셋인디아인프라섹터증권자투자신탁 1(주식)', 60, 'FUND')
insert into fund_product(id, price) value(339, 3060.99)
insert into product(id, name, corp_id, p_type) value(340, '미래에셋TIGER필라델피아반도체레버리지증권상장지수투자신탁(주식혼합-파생형)(합성)', 60, 'FUND')
insert into fund_product(id, price) value(340, 26382.79)
insert into product(id, name, corp_id, p_type) value(341, '미래에셋TIGER미국나스닥100레버리지증권상장지수투자신탁(주식혼합-파생형)(합성)', 60, 'FUND')
insert into fund_product(id, price) value(341, 19057.81)
insert into product(id, name, corp_id, p_type) value(342, '미래에셋인디아인프라섹터증권모투자신탁(주식)', 60, 'FUND')
insert into fund_product(id, price) value(342, 2775.85)
insert into product(id, name, corp_id, p_type) value(343, '미래에셋연금인디아인프라증권자투자신탁 1(주식)', 60, 'FUND')
insert into fund_product(id, price) value(343, 1130.22)
insert into product(id, name, corp_id, p_type) value(344, '미래에셋인디아인프라섹터증권자투자신탁 1(주식)', 60, 'FUND')
insert into fund_product(id, price) value(344, 3060.99)
insert into product(id, name, corp_id, p_type) value(345, '미래에셋TIGER필라델피아반도체레버리지증권상장지수투자신탁(주식혼합-파생형)(합성)', 60, 'FUND')
insert into fund_product(id, price) value(345, 26382.79)
insert into product(id, name, corp_id, p_type) value(346, '미래에셋TIGER미국나스닥100레버리지증권상장지수투자신탁(주식혼합-파생형)(합성)', 60, 'FUND')
insert into fund_product(id, price) value(346, 19057.81)
insert into product(id, name, corp_id, p_type) value(347, '미래에셋인디아인프라섹터증권모투자신탁(주식)', 60, 'FUND')
insert into fund_product(id, price) value(347, 2775.85)
insert into product(id, name, corp_id, p_type) value(348, '미래에셋연금인디아인프라증권자투자신탁 1(주식)', 60, 'FUND')
insert into fund_product(id, price) value(348, 1130.22)
insert into product(id, name, corp_id, p_type) value(349, '미래에셋인디아인프라섹터증권자투자신탁 1(주식)', 60, 'FUND')
insert into fund_product(id, price) value(349, 3060.99)
insert into product(id, name, corp_id, p_type) value(350, '미래에셋TIGER필라델피아반도체레버리지증권상장지수투자신탁(주식혼합-파생형)(합성)', 60, 'FUND')
insert into fund_product(id, price) value(350, 26382.79)
insert into product(id, name, corp_id, p_type) value(351, '미래에셋TIGER미국나스닥100레버리지증권상장지수투자신탁(주식혼합-파생형)(합성)', 60, 'FUND')
insert into fund_product(id, price) value(351, 19057.81)
insert into product(id, name, corp_id, p_type) value(352, '미래에셋인디아인프라섹터증권모투자신탁(주식)', 60, 'FUND')
insert into fund_product(id, price) value(352, 2775.85)
insert into product(id, name, corp_id, p_type) value(353, '미래에셋연금인디아인프라증권자투자신탁 1(주식)', 60, 'FUND')
insert into fund_product(id, price) value(353, 1130.22)
insert into product(id, name, corp_id, p_type) value(354, '미래에셋인디아인프라섹터증권자투자신탁 1(주식)', 60, 'FUND')
insert into fund_product(id, price) value(354, 3060.99)
insert into product(id, name, corp_id, p_type) value(355, '신한SOL한국형글로벌반도체액티브증권상장지수투자신탁[주식]', 61, 'FUND')
insert into fund_product(id, price) value(355, 18833.21)
insert into product(id, name, corp_id, p_type) value(356, '신한인디아증권모투자신탁[주식]', 61, 'FUND')
insert into fund_product(id, price) value(356, 2850.62)
insert into product(id, name, corp_id, p_type) value(357, '신한SOLAI반도체소부장증권상장지수투자신탁[주식]', 61, 'FUND')
insert into fund_product(id, price) value(357, 15731.5)
insert into product(id, name, corp_id, p_type) value(358, '신한동유럽플러스증권모투자신탁[주식]', 61, 'FUND')
insert into fund_product(id, price) value(358, 947.28)
insert into product(id, name, corp_id, p_type) value(359, '신한동유럽플러스증권자투자신탁(H)[주식](종류)', 61, 'FUND')
insert into fund_product(id, price) value(359, 671.13)
insert into product(id, name, corp_id, p_type) value(360, '신한SOL한국형글로벌반도체액티브증권상장지수투자신탁[주식]', 61, 'FUND')
insert into fund_product(id, price) value(360, 18833.21)
insert into product(id, name, corp_id, p_type) value(361, '신한인디아증권모투자신탁[주식]', 61, 'FUND')
insert into fund_product(id, price) value(361, 2850.62)
insert into product(id, name, corp_id, p_type) value(362, '신한SOLAI반도체소부장증권상장지수투자신탁[주식]', 61, 'FUND')
insert into fund_product(id, price) value(362, 15731.5)
insert into product(id, name, corp_id, p_type) value(363, '신한동유럽플러스증권모투자신탁[주식]', 61, 'FUND')
insert into fund_product(id, price) value(363, 947.28)
insert into product(id, name, corp_id, p_type) value(364, '신한동유럽플러스증권자투자신탁(H)[주식](종류)', 61, 'FUND')
insert into fund_product(id, price) value(364, 671.13)
insert into product(id, name, corp_id, p_type) value(365, '신한SOL한국형글로벌반도체액티브증권상장지수투자신탁[주식]', 61, 'FUND')
insert into fund_product(id, price) value(365, 18833.21)
insert into product(id, name, corp_id, p_type) value(366, '신한인디아증권모투자신탁[주식]', 61, 'FUND')
insert into fund_product(id, price) value(366, 2850.62)
insert into product(id, name, corp_id, p_type) value(367, '신한SOLAI반도체소부장증권상장지수투자신탁[주식]', 61, 'FUND')
insert into fund_product(id, price) value(367, 15731.5)
insert into product(id, name, corp_id, p_type) value(368, '신한동유럽플러스증권모투자신탁[주식]', 61, 'FUND')
insert into fund_product(id, price) value(368, 947.28)
insert into product(id, name, corp_id, p_type) value(369, '신한동유럽플러스증권자투자신탁(H)[주식](종류)', 61, 'FUND')
insert into fund_product(id, price) value(369, 671.13)
insert into product(id, name, corp_id, p_type) value(370, '신한SOL한국형글로벌반도체액티브증권상장지수투자신탁[주식]', 61, 'FUND')
insert into fund_product(id, price) value(370, 18833.21)
insert into product(id, name, corp_id, p_type) value(371, '신한인디아증권모투자신탁[주식]', 61, 'FUND')
insert into fund_product(id, price) value(371, 2850.62)
insert into product(id, name, corp_id, p_type) value(372, '신한SOLAI반도체소부장증권상장지수투자신탁[주식]', 61, 'FUND')
insert into fund_product(id, price) value(372, 15731.5)
insert into product(id, name, corp_id, p_type) value(373, '신한동유럽플러스증권모투자신탁[주식]', 61, 'FUND')
insert into fund_product(id, price) value(373, 947.28)
insert into product(id, name, corp_id, p_type) value(374, '신한동유럽플러스증권자투자신탁(H)[주식](종류)', 61, 'FUND')
insert into fund_product(id, price) value(374, 671.13)
insert into product(id, name, corp_id, p_type) value(375, '신한SOL한국형글로벌반도체액티브증권상장지수투자신탁[주식]', 61, 'FUND')
insert into fund_product(id, price) value(375, 18833.21)
insert into product(id, name, corp_id, p_type) value(376, '신한인디아증권모투자신탁[주식]', 61, 'FUND')
insert into fund_product(id, price) value(376, 2850.62)
insert into product(id, name, corp_id, p_type) value(377, '신한SOLAI반도체소부장증권상장지수투자신탁[주식]', 61, 'FUND')
insert into fund_product(id, price) value(377, 15731.5)
insert into product(id, name, corp_id, p_type) value(378, '신한동유럽플러스증권모투자신탁[주식]', 61, 'FUND')
insert into fund_product(id, price) value(378, 947.28)
insert into product(id, name, corp_id, p_type) value(379, '신한동유럽플러스증권자투자신탁(H)[주식](종류)', 61, 'FUND')
insert into fund_product(id, price) value(379, 671.13)
insert into product(id, name, corp_id, p_type) value(380, '삼성KODEX미국반도체MV증권상장지수투자신탁[주식]', 62, 'FUND')
insert into fund_product(id, price) value(380, 22962.95)
insert into product(id, name, corp_id, p_type) value(381, '삼성인도중소형FOCUS증권모투자신탁[주식]', 62, 'FUND')
insert into fund_product(id, price) value(381, 4215.64)
insert into product(id, name, corp_id, p_type) value(382, '삼성인도중소형FOCUS증권자투자신탁UH[주식]', 62, 'FUND')
insert into fund_product(id, price) value(382, 4177.42)
insert into product(id, name, corp_id, p_type) value(383, '삼성클래식인도중소형FOCUS연금증권자투자신탁UH[주식]', 62, 'FUND')
insert into fund_product(id, price) value(383, 4155.14)
insert into product(id, name, corp_id, p_type) value(384, '삼성인도중소형FOCUS증권자투자신탁UH[주식]_Cw', 62, 'FUND')
insert into fund_product(id, price) value(384, 4213.26)
insert into product(id, name, corp_id, p_type) value(385, '삼성KODEX미국반도체MV증권상장지수투자신탁[주식]', 62, 'FUND')
insert into fund_product(id, price) value(385, 22962.95)
insert into product(id, name, corp_id, p_type) value(386, '삼성인도중소형FOCUS증권모투자신탁[주식]', 62, 'FUND')
insert into fund_product(id, price) value(386, 4215.64)
insert into product(id, name, corp_id, p_type) value(387, '삼성인도중소형FOCUS증권자투자신탁UH[주식]', 62, 'FUND')
insert into fund_product(id, price) value(387, 4177.42)
insert into product(id, name, corp_id, p_type) value(388, '삼성클래식인도중소형FOCUS연금증권자투자신탁UH[주식]', 62, 'FUND')
insert into fund_product(id, price) value(388, 4155.14)
insert into product(id, name, corp_id, p_type) value(389, '삼성인도중소형FOCUS증권자투자신탁UH[주식]_Cw', 62, 'FUND')
insert into fund_product(id, price) value(389, 4213.26)
insert into product(id, name, corp_id, p_type) value(390, '삼성KODEX미국반도체MV증권상장지수투자신탁[주식]', 62, 'FUND')
insert into fund_product(id, price) value(390, 22962.95)
insert into product(id, name, corp_id, p_type) value(391, '삼성인도중소형FOCUS증권모투자신탁[주식]', 62, 'FUND')
insert into fund_product(id, price) value(391, 4215.64)
insert into product(id, name, corp_id, p_type) value(392, '삼성인도중소형FOCUS증권자투자신탁UH[주식]', 62, 'FUND')
insert into fund_product(id, price) value(392, 4177.42)
insert into product(id, name, corp_id, p_type) value(393, '삼성클래식인도중소형FOCUS연금증권자투자신탁UH[주식]', 62, 'FUND')
insert into fund_product(id, price) value(393, 4155.14)
insert into product(id, name, corp_id, p_type) value(394, '삼성인도중소형FOCUS증권자투자신탁UH[주식]_Cw', 62, 'FUND')
insert into fund_product(id, price) value(394, 4213.26)
insert into product(id, name, corp_id, p_type) value(395, '삼성KODEX미국반도체MV증권상장지수투자신탁[주식]', 62, 'FUND')
insert into fund_product(id, price) value(395, 22962.95)
insert into product(id, name, corp_id, p_type) value(396, '삼성인도중소형FOCUS증권모투자신탁[주식]', 62, 'FUND')
insert into fund_product(id, price) value(396, 4215.64)
insert into product(id, name, corp_id, p_type) value(397, '삼성인도중소형FOCUS증권자투자신탁UH[주식]', 62, 'FUND')
insert into fund_product(id, price) value(397, 4177.42)
insert into product(id, name, corp_id, p_type) value(398, '삼성클래식인도중소형FOCUS연금증권자투자신탁UH[주식]', 62, 'FUND')
insert into fund_product(id, price) value(398, 4155.14)
insert into product(id, name, corp_id, p_type) value(399, '삼성인도중소형FOCUS증권자투자신탁UH[주식]_Cw', 62, 'FUND')
insert into fund_product(id, price) value(399, 4213.26)
insert into product(id, name, corp_id, p_type) value(400, '삼성KODEX미국반도체MV증권상장지수투자신탁[주식]', 62, 'FUND')
insert into fund_product(id, price) value(400, 22962.95)
insert into product(id, name, corp_id, p_type) value(401, '삼성인도중소형FOCUS증권모투자신탁[주식]', 62, 'FUND')
insert into fund_product(id, price) value(401, 4215.64)
insert into product(id, name, corp_id, p_type) value(402, '삼성인도중소형FOCUS증권자투자신탁UH[주식]', 62, 'FUND')
insert into fund_product(id, price) value(402, 4177.42)
insert into product(id, name, corp_id, p_type) value(403, '삼성클래식인도중소형FOCUS연금증권자투자신탁UH[주식]', 62, 'FUND')
insert into fund_product(id, price) value(403, 4155.14)
insert into product(id, name, corp_id, p_type) value(404, '삼성인도중소형FOCUS증권자투자신탁UH[주식]_Cw', 62, 'FUND')
insert into fund_product(id, price) value(404, 4213.26)
insert into product(id, name, corp_id, p_type) value(405, 'KBKBSTAR글로벌원자력iSelect증권상장지수투자신탁(주식)', 63, 'FUND')
insert into fund_product(id, price) value(405, 17790.97)
insert into product(id, name, corp_id, p_type) value(406, 'KBKBSTAR글로벌메타버스Moorgate증권상장지수투자신탁(주식)', 63, 'FUND')
insert into fund_product(id, price) value(406, 14006.96)
insert into product(id, name, corp_id, p_type) value(407, 'KBKBSTAR비메모리반도체액티브증권상장지수투자신탁(주식)', 63, 'FUND')
insert into fund_product(id, price) value(407, 13735.98)
insert into product(id, name, corp_id, p_type) value(408, 'KB지수연계증권투자신탁230(ELS-파생형)(운용)', 63, 'FUND')
insert into fund_product(id, price) value(408, 1129.36)
insert into product(id, name, corp_id, p_type) value(409, 'KB지수연계증권투자신탁230(ELS-파생형)A', 63, 'FUND')
insert into fund_product(id, price) value(409, 1128.94)
insert into product(id, name, corp_id, p_type) value(410, 'KBKBSTAR글로벌원자력iSelect증권상장지수투자신탁(주식)', 63, 'FUND')
insert into fund_product(id, price) value(410, 17790.97)
insert into product(id, name, corp_id, p_type) value(411, 'KBKBSTAR글로벌메타버스Moorgate증권상장지수투자신탁(주식)', 63, 'FUND')
insert into fund_product(id, price) value(411, 14006.96)
insert into product(id, name, corp_id, p_type) value(412, 'KBKBSTAR비메모리반도체액티브증권상장지수투자신탁(주식)', 63, 'FUND')
insert into fund_product(id, price) value(412, 13735.98)
insert into product(id, name, corp_id, p_type) value(413, 'KB지수연계증권투자신탁230(ELS-파생형)(운용)', 63, 'FUND')
insert into fund_product(id, price) value(413, 1129.36)
insert into product(id, name, corp_id, p_type) value(414, 'KB지수연계증권투자신탁230(ELS-파생형)A', 63, 'FUND')
insert into fund_product(id, price) value(414, 1128.94)
insert into product(id, name, corp_id, p_type) value(415, 'KBKBSTAR글로벌원자력iSelect증권상장지수투자신탁(주식)', 63, 'FUND')
insert into fund_product(id, price) value(415, 17790.97)
insert into product(id, name, corp_id, p_type) value(416, 'KBKBSTAR글로벌메타버스Moorgate증권상장지수투자신탁(주식)', 63, 'FUND')
insert into fund_product(id, price) value(416, 14006.96)
insert into product(id, name, corp_id, p_type) value(417, 'KBKBSTAR비메모리반도체액티브증권상장지수투자신탁(주식)', 63, 'FUND')
insert into fund_product(id, price) value(417, 13735.98)
insert into product(id, name, corp_id, p_type) value(418, 'KB지수연계증권투자신탁230(ELS-파생형)(운용)', 63, 'FUND')
insert into fund_product(id, price) value(418, 1129.36)
insert into product(id, name, corp_id, p_type) value(419, 'KB지수연계증권투자신탁230(ELS-파생형)A', 63, 'FUND')
insert into fund_product(id, price) value(419, 1128.94)
insert into product(id, name, corp_id, p_type) value(420, 'KBKBSTAR글로벌원자력iSelect증권상장지수투자신탁(주식)', 63, 'FUND')
insert into fund_product(id, price) value(420, 17790.97)
insert into product(id, name, corp_id, p_type) value(421, 'KBKBSTAR글로벌메타버스Moorgate증권상장지수투자신탁(주식)', 63, 'FUND')
insert into fund_product(id, price) value(421, 14006.96)
insert into product(id, name, corp_id, p_type) value(422, 'KBKBSTAR비메모리반도체액티브증권상장지수투자신탁(주식)', 63, 'FUND')
insert into fund_product(id, price) value(422, 13735.98)
insert into product(id, name, corp_id, p_type) value(423, 'KB지수연계증권투자신탁230(ELS-파생형)(운용)', 63, 'FUND')
insert into fund_product(id, price) value(423, 1129.36)
insert into product(id, name, corp_id, p_type) value(424, 'KB지수연계증권투자신탁230(ELS-파생형)A', 63, 'FUND')
insert into fund_product(id, price) value(424, 1128.94)
insert into product(id, name, corp_id, p_type) value(425, 'KBKBSTAR글로벌원자력iSelect증권상장지수투자신탁(주식)', 63, 'FUND')
insert into fund_product(id, price) value(425, 17790.97)
insert into product(id, name, corp_id, p_type) value(426, 'KBKBSTAR글로벌메타버스Moorgate증권상장지수투자신탁(주식)', 63, 'FUND')
insert into fund_product(id, price) value(426, 14006.96)
insert into product(id, name, corp_id, p_type) value(427, 'KBKBSTAR비메모리반도체액티브증권상장지수투자신탁(주식)', 63, 'FUND')
insert into fund_product(id, price) value(427, 13735.98)
insert into product(id, name, corp_id, p_type) value(428, 'KB지수연계증권투자신탁230(ELS-파생형)(운용)', 63, 'FUND')
insert into fund_product(id, price) value(428, 1129.36)
insert into product(id, name, corp_id, p_type) value(429, 'KB지수연계증권투자신탁230(ELS-파생형)A', 63, 'FUND')
insert into fund_product(id, price) value(429, 1128.94)
