insert into stock(code, name, price, stock_type,dart_code) value ('005930', '삼성전자', 75500, 'D', '00126380');
insert into stock(code, name, price, stock_type,dart_code) value ('000660', 'SK하이닉스', 212000, 'D', '00164779');
insert into stock(code, name, price, stock_type,dart_code) value ('373220', 'LG에너지솔루션', 358000, 'D', '01515323');
insert into stock(code, name, price, stock_type,dart_code) value ('207940', '삼성바이오로직스', 741000, 'D', '00877059');
insert into stock(code, name, price, stock_type,dart_code) value ('000270', '기아', 122000, 'D', '00106641');
insert into stock(code, name, price, stock_type,dart_code) value ('068270', '셀트리온', 193100, 'D', '00413046');
insert into stock(code, name, price, stock_type,dart_code) value ('005490', 'POSCO홀딩스', 379500, 'D', '00155319');
insert into stock(code, name, price, stock_type,dart_code) value ('105560', 'KB금융', 78600, 'D', '00688996');
insert into stock(code, name, price, stock_type,dart_code) value ('035420', 'NAVER', 170400, 'D', '00266961');
insert into stock(code, name, price, stock_type,dart_code) value ('006400', '삼성SDI', 393000, 'D', '00126362');
insert into stock(code, name, price, stock_type,dart_code) value ('051910', 'LG화학', 374500, 'D', '00356361');
insert into stock(code, name, price, stock_type,dart_code) value ('028260', '삼성물산', 133800, 'D', '00149655');
insert into stock(code, name, price, stock_type,dart_code) value ('055550', '신한지주', 46200, 'D', '00382199');
insert into stock(code, name, price, stock_type,dart_code) value ('003670', '포스코퓨처엠', 285500, 'D', '00155276');
insert into stock(code, name, price, stock_type,dart_code) value ('012330', '현대모비스', 218500, 'D', '00164788');
insert into stock(code, name, price, stock_type,dart_code) value ('035720', '카카오', 43250, 'D', '00258801');
insert into stock(code, name, price, stock_type,dart_code) value ('086790', '하나금융지주', 59800, 'D', '00547583');
insert into stock(code, name, price, stock_type,dart_code) value ('032830', '삼성생명', 84300, 'D', '00126256');
insert into stock(code, name, price, stock_type,dart_code) value ('066570', 'LG전자', 98200, 'D', '00401731');
insert into stock(code, name, price, stock_type,dart_code) value ('042700', '한미반도체', 159300, 'D', '00161383');
insert into stock(code, name, price, stock_type,dart_code) value ('138040', '메리츠금융지주', 74000, 'D', '00860332');
insert into stock(code, name, price, stock_type,dart_code) value ('034730', 'SK', 182300, 'D', '00181712');
insert into stock(code, name, price, stock_type,dart_code) value ('003550', 'LG', 80000, 'D', '00120021');
insert into stock(code, name, price, stock_type,dart_code) value ('259960', '크래프톤', 257500, 'D', '00760971');
insert into stock(code, name, price, stock_type,dart_code) value ('011200', 'HMM', 17500, 'D', '00164645');
insert into stock(code, name, price, stock_type,dart_code) value ('034020', '두산에너빌리티', 19240, 'D', '00159616');
insert into stock(code, name, price, stock_type,dart_code) value ('018260', '삼성에스디에스', 155500, 'D', '00126186');
insert into stock(code, name, price, stock_type,dart_code) value ('402340', 'SK스퀘어', 88200, 'D', '01596425');
insert into stock(code, name, price, stock_type,dart_code) value ('329180', 'HD현대중공업', 129800, 'D', '01390344');
insert into stock(code, name, price, stock_type,dart_code) value ('009150', '삼성전기', 149800, 'D', '00126371');
insert into stock(code, name, price, stock_type,dart_code) value ('017670', 'SK텔레콤', 51100, 'D', '00159023');
insert into stock(code, name, price, stock_type,dart_code) value ('323410', '카카오뱅크', 22400, 'D', '01133217');
insert into stock(code, name, price, stock_type,dart_code) value ('024110', '기업은행', 13370, 'D', '00149646');
insert into stock(code, name, price, stock_type,dart_code) value ('012450', '한화에어로스페이스', 210500, 'D', '00126566');
insert into stock(code, name, price, stock_type,dart_code) value ('316140', '우리금융지주', 14070, 'D', '01350869');
insert into stock(code, name, price, stock_type,dart_code) value ('090430', '아모레퍼시픽', 178300, 'D', '00583424');
insert into stock(code, name, price, stock_type,dart_code) value ('010130', '고려아연', 498000, 'D', '00102858');
insert into stock(code, name, price, stock_type,dart_code) value ('096770', 'SK이노베이션', 103800, 'D', '00631518');
insert into stock(code, name, price, stock_type,dart_code) value ('267260', 'HD현대일렉트릭', 274500, 'D', '01205851');
insert into stock(code, name, price, stock_type,dart_code) value ('009540', 'HD한국조선해양', 133800, 'D', '00164830');
insert into stock(code, name, price, stock_type,dart_code) value ('047050', '포스코인터내셔널', 53700, 'D', '00124504');
insert into stock(code, name, price, stock_type,dart_code) value ('042660', '한화오션', 30400, 'D', '00111704');
insert into stock(code, name, price, stock_type,dart_code) value ('450080', '에코프로머티', 131800, 'D', '01311408');
insert into stock(code, name, price, stock_type,dart_code) value ('352820', '하이브', 198200, 'D', '01204056');
insert into stock(code, name, price, stock_type,dart_code) value ('003490', '대한항공', 22200, 'D', '00113526');
insert into stock(code, name, price, stock_type,dart_code) value ('010140', '삼성중공업', 9230, 'D', '00126478');
insert into stock(code, name, price, stock_type,dart_code) value ('010950', 'S-Oil', 66600, 'D', '00138279');
insert into stock(code, name, price, stock_type,dart_code) value ('005830', 'DB손해보험', 105200, 'D', '00159102');
insert into stock(code, name, price, stock_type,dart_code) value ('086280', '현대글로비스', 183700, 'D', '00360595');
insert into stock(code, name, price, stock_type,dart_code) value ('011790', 'SKC', 166300, 'D', '00139889');
insert into stock(code, name, price, stock_type,dart_code) value ('051900', 'LG생활건강', 401500, 'D', '00356370');
insert into stock(code, name, price, stock_type,dart_code) value ('022100', '포스코DX', 40500, 'D', '00155212');
insert into stock(code, name, price, stock_type,dart_code) value ('443060', 'HD현대마린솔루션', 137800, 'D', '01194689');
insert into stock(code, name, price, stock_type,dart_code) value ('000100', '유한양행', 75800, 'D', '00145109');
insert into stock(code, name, price, stock_type,dart_code) value ('066970', '엘앤에프', 164800, 'D', '00398701');
insert into stock(code, name, price, stock_type,dart_code) value ('009830', '한화솔루션', 32400, 'D', '00162461');
insert into stock(code, name, price, stock_type,dart_code) value ('005070', '코스모신소재', 170700, 'D', '00129989');
insert into stock(code, name, price, stock_type,dart_code) value ('161390', '한국타이어앤테크놀로지', 44750, 'D', '00937324');
insert into stock(code, name, price, stock_type,dart_code) value ('088980', '맥쿼리인프라', 12630, 'D', '00435297');
insert into stock(code, name, price, stock_type,dart_code) value ('267250', 'HD현대', 69300, 'D', '01205709');
insert into stock(code, name, price, stock_type,dart_code) value ('097950', 'CJ제일제당', 362000, 'D', '00635134');
insert into stock(code, name, price, stock_type,dart_code) value ('011070', 'LG이노텍', 229000, 'D', '00105961');
insert into stock(code, name, price, stock_type,dart_code) value ('241560', '두산밥캣', 52900, 'D', '01032486');
insert into stock(code, name, price, stock_type,dart_code) value ('454910', '두산로보틱스', 80700, 'D', '01105153');
insert into stock(code, name, price, stock_type,dart_code) value ('001570', '금양', 89500, 'D', '00106119');
insert into stock(code, name, price, stock_type,dart_code) value ('011170', '롯데케미칼', 119900, 'D', '00165413');
insert into stock(code, name, price, stock_type,dart_code) value ('034220', 'LG디스플레이', 10100, 'D', '00105873');
insert into stock(code, name, price, stock_type,dart_code) value ('047810', '한국항공우주', 51500, 'D', '00309503');
insert into stock(code, name, price, stock_type,dart_code) value ('251270', '넷마블', 56100, 'D', '00904672');
insert into stock(code, name, price, stock_type,dart_code) value ('006260', 'LS', 146600, 'D', '00105952');
insert into stock(code, name, price, stock_type,dart_code) value ('180640', '한진칼', 69200, 'D', '00983040');
insert into stock(code, name, price, stock_type,dart_code) value ('029780', '삼성카드', 39050, 'D', '00126292');
insert into stock(code, name, price, stock_type,dart_code) value ('003230', '삼양식품', 592000, 'D', '00126955');
insert into stock(code, name, price, stock_type,dart_code) value ('028050', '삼성E&A', 22400, 'D', '00126308');
insert into stock(code, name, price, stock_type,dart_code) value ('032640', 'LG유플러스', 9720, 'D', '00231363');
insert into stock(code, name, price, stock_type,dart_code) value ('006800', '미래에셋증권', 7090, 'D', '00111722');
insert into stock(code, name, price, stock_type,dart_code) value ('036570', '엔씨소프트', 187300, 'D', '00261443');
insert into stock(code, name, price, stock_type,dart_code) value ('064350', '현대로템', 37650, 'D', '00302926');
insert into stock(code, name, price, stock_type,dart_code) value ('377300', '카카오페이', 30500, 'D', '01244601');
insert into stock(code, name, price, stock_type,dart_code) value ('036460', '한국가스공사', 43750, 'D', '00261285');
insert into stock(code, name, price, stock_type,dart_code) value ('307950', '현대오토에버', 147100, 'D', '00362441');
insert into stock(code, name, price, stock_type,dart_code) value ('021240', '코웨이', 54600, 'D', '00170558');
insert into stock(code, name, price, stock_type,dart_code) value ('078930', 'GS', 42950, 'D', '00500254');
insert into stock(code, name, price, stock_type,dart_code) value ('302440', 'SK바이오사이언스', 51400, 'D', '01319899');
insert into stock(code, name, price, stock_type,dart_code) value ('005940', 'NH투자증권', 11940, 'D', '00120182');
insert into stock(code, name, price, stock_type,dart_code) value ('004020', '현대제철', 28650, 'D', '00145880');
insert into stock(code, name, price, stock_type,dart_code) value ('271560', '오리온', 96700, 'D', '01238169');
insert into stock(code, name, price, stock_type,dart_code) value ('001040', 'CJ', 130900, 'D', '00148540');
insert into stock(code, name, price, stock_type,dart_code) value ('071050', '한국금융지주', 67500, 'D', '00432102');
insert into stock(code, name, price, stock_type,dart_code) value ('079550', 'LIG넥스원', 169600, 'D', '00503668');
insert into stock(code, name, price, stock_type,dart_code) value ('298040', '효성중공업', 396500, 'D', '01316245');
insert into stock(code, name, price, stock_type,dart_code) value ('000720', '현대건설', 32950, 'D', '00164478');
insert into stock(code, name, price, stock_type,dart_code) value ('128940', '한미약품', 282000, 'D', '00828497');
insert into stock(code, name, price, stock_type,dart_code) value ('000150', '두산', 202500, 'D', '00117212');
insert into stock(code, name, price, stock_type,dart_code) value ('361610', 'SK아이이테크놀로지', 46300, 'D', '01386916');
insert into stock(code, name, price, stock_type,dart_code) value ('272210', '한화시스템', 17250, 'D', '00339391');
insert into stock(code, name, price, stock_type,dart_code) value ('039490', '키움증권', 127100, 'D', '00296290');
insert into stock(code, name, price, stock_type,dart_code) value ('004370', '농심', 530000, 'D', '00108241');
insert into stock(code, name, price, stock_type,dart_code) value ('016360', '삼성증권', 35900, 'D', '00104856');
insert into stock(code, name, price, stock_type,dart_code) value ('035250', '강원랜드', 14760, 'D', '00255619');
insert into stock(code, name, price, stock_type,dart_code) value ('007660', '이수페타시스', 48100, 'D', '00107613');
insert into stock(code, name, price, stock_type,dart_code) value ('001450', '현대해상', 32600, 'D', '00164973');
insert into stock(code, name, price, stock_type,dart_code) value ('010620', 'HD현대미포', 72500, 'D', '00164609');
insert into stock(code, name, price, stock_type,dart_code) value ('001440', '대한전선', 15440, 'D', '00113207');
insert into stock(code, name, price, stock_type,dart_code) value ('278470', '에이피알', 361500, 'D', '01190568');
insert into stock(code, name, price, stock_type,dart_code) value ('004990', '롯데지주', 25100, 'D', '00120562');
insert into stock(code, name, price, stock_type,dart_code) value ('175330', 'JB금융지주', 13490, 'D', '00980122');
insert into stock(code, name, price, stock_type,dart_code) value ('018880', '한온시스템', 4920, 'D', '00161125');
insert into stock(code, name, price, stock_type,dart_code) value ('052690', '한전기술', 68600, 'D', '00159209');
insert into stock(code, name, price, stock_type,dart_code) value ('383220', 'F&F', 68200, 'D', '01568413');
insert into stock(code, name, price, stock_type,dart_code) value ('138930', 'BNK금융지주', 8090, 'D', '00858364');
insert into stock(code, name, price, stock_type,dart_code) value ('020150', '롯데에너지머티리얼즈', 55800, 'D', '00113997');
insert into stock(code, name, price, stock_type,dart_code) value ('088350', '한화생명', 2760, 'D', '00113058');
insert into stock(code, name, price, stock_type,dart_code) value ('081660', '휠라홀딩스', 39300, 'D', '00195229');
insert into stock(code, name, price, stock_type,dart_code) value ('007070', 'GS리테일', 21900, 'D', '00140177');
insert into stock(code, name, price, stock_type,dart_code) value ('000120', 'CJ대한통운', 100500, 'D', '00113410');
insert into stock(code, name, price, stock_type,dart_code) value ('012750', '에스원', 60200, 'D', '00158501');
insert into stock(code, name, price, stock_type,dart_code) value ('204320', 'HL만도', 47550, 'D', '01042775');
insert into stock(code, name, price, stock_type,dart_code) value ('008770', '호텔신라', 56100, 'D', '00165680');
insert into stock(code, name, price, stock_type,dart_code) value ('028670', '팬오션', 4110, 'D', '00122737');
insert into stock(code, name, price, stock_type,dart_code) value ('008930', '한미사이언스', 31300, 'D', '00161426');
insert into stock(code, name, price, stock_type,dart_code) value ('030000', '제일기획', 18450, 'D', '00148276');
insert into stock(code, name, price, stock_type,dart_code) value ('012510', '더존비즈온', 68900, 'D', '00172291');
insert into stock(code, name, price, stock_type,dart_code) value ('112610', '씨에스윈드', 49400, 'D', '00670340');
insert into stock(code, name, price, stock_type,dart_code) value ('014680', '한솔케미칼', 182200, 'D', '00140955');
insert into stock(code, name, price, stock_type,dart_code) value ('282330', 'BGF리테일', 115200, 'D', '01263022');
insert into stock(code, name, price, stock_type,dart_code) value ('000880', '한화', 26500, 'D', '00160588');
insert into stock(code, name, price, stock_type,dart_code) value ('073240', '금호타이어', 6890, 'D', '00481454');
insert into stock(code, name, price, stock_type,dart_code) value ('007310', '오뚜기', 486500, 'D', '00141529');
insert into stock(code, name, price, stock_type,dart_code) value ('026960', '동서', 19410, 'D', '00864383');
insert into stock(code, name, price, stock_type,dart_code) value ('000990', 'DB하이텍', 42650, 'D', '00160843');
insert into stock(code, name, price, stock_type,dart_code) value ('010060', 'OCI홀딩스', 93300, 'D', '00148896');
insert into stock(code, name, price, stock_type,dart_code) value ('023530', '롯데쇼핑', 64400, 'D', '00120526');
insert into stock(code, name, price, stock_type,dart_code) value ('005850', '에스엘', 39000, 'D', '00125521');
insert into stock(code, name, price, stock_type,dart_code) value ('192820', '코스맥스', 155500, 'D', '01009789');
insert into stock(code, name, price, stock_type,dart_code) value ('457190', '이수스페셜티케미컬', 58100, 'D', '01762569');
insert into stock(code, name, price, stock_type,dart_code) value ('009420', '한올바이오파마', 33400, 'D', '00162586');
insert into stock(code, name, price, stock_type,dart_code) value ('298020', '효성티앤씨', 390500, 'D', '01316227');
insert into stock(code, name, price, stock_type,dart_code) value ('280360', '롯데웰푸드', 178100, 'D', '01258507');
insert into stock(code, name, price, stock_type,dart_code) value ('139480', '이마트', 59000, 'D', '00872984');
insert into stock(code, name, price, stock_type,dart_code) value ('051600', '한전KPS', 36100, 'D', '00159218');
insert into stock(code, name, price, stock_type,dart_code) value ('018670', 'SK가스', 174300, 'D', '00144164');
insert into stock(code, name, price, stock_type,dart_code) value ('103140', '풍산', 57200, 'D', '00684714');
insert into stock(code, name, price, stock_type,dart_code) value ('002710', 'TCC스틸', 60700, 'D', '00117300');
insert into stock(code, name, price, stock_type,dart_code) value ('004170', '신세계', 160900, 'D', '00136378');
insert into stock(code, name, price, stock_type,dart_code) value ('298050', '효성첨단소재', 353000, 'D', '01316254');
insert into stock(code, name, price, stock_type,dart_code) value ('011210', '현대위아', 57200, 'D', '00106623');
insert into stock(code, name, price, stock_type,dart_code) value ('111770', '영원무역', 35000, 'D', '00776820');
insert into stock(code, name, price, stock_type,dart_code) value ('042670', 'HD현대인프라코어', 7720, 'D', '00344287');
insert into stock(code, name, price, stock_type,dart_code) value ('004490', '세방전지', 108200, 'D', '00133858');
insert into stock(code, name, price, stock_type,dart_code) value ('047040', '대우건설', 3625, 'D', '00124540');
insert into stock(code, name, price, stock_type,dart_code) value ('336260', '두산퓨얼셀', 22650, 'D', '01412725');
insert into stock(code, name, price, stock_type,dart_code) value ('161890', '한국콜마', 61700, 'D', '00939331');
insert into stock(code, name, price, stock_type,dart_code) value ('000080', '하이트진로', 20700, 'D', '00150244');
insert into stock(code, name, price, stock_type,dart_code) value ('000240', '한국앤컴퍼니', 15120, 'D', '00160047');
insert into stock(code, name, price, stock_type,dart_code) value ('006110', '삼아알미늄', 96200, 'D', '00126779');
insert into stock(code, name, price, stock_type,dart_code) value ('006280', '녹십자', 119500, 'D', '00129679');
insert into stock(code, name, price, stock_type,dart_code) value ('014820', '동원시스템즈', 47900, 'D', '00132637');
insert into stock(code, name, price, stock_type,dart_code) value ('185750', '종근당', 102500, 'D', '00992871');
insert into stock(code, name, price, stock_type,dart_code) value ('139130', 'DGB금융지주', 7930, 'D', '00878915');
insert into stock(code, name, price, stock_type,dart_code) value ('375500', 'DL이앤씨', 34350, 'D', '01524093');
insert into stock(code, name, price, stock_type,dart_code) value ('003690', '코리안리', 7990, 'D', '00113191');
insert into stock(code, name, price, stock_type,dart_code) value ('395400', 'SK리츠', 4835, 'D', '01535150');
insert into stock(code, name, price, stock_type,dart_code) value ('336370', '솔루스첨단소재', 18200, 'D', '01412822');
insert into stock(code, name, price, stock_type,dart_code) value ('009240', '한샘', 54300, 'D', '00161693');
insert into stock(code, name, price, stock_type,dart_code) value ('006360', 'GS건설', 14640, 'D', '00120030');
insert into stock(code, name, price, stock_type,dart_code) value ('000210', 'DL', 59500, 'D', '00109693');
insert into stock(code, name, price, stock_type,dart_code) value ('006040', '동원산업', 34600, 'D', '00118026');
insert into stock(code, name, price, stock_type,dart_code) value ('005420', '코스모화학', 32450, 'D', '00160302');
insert into stock(code, name, price, stock_type,dart_code) value ('069620', '대웅제약', 106700, 'D', '00427483');
insert into stock(code, name, price, stock_type,dart_code) value ('004000', '롯데정밀화학', 47300, 'D', '00157681');
insert into stock(code, name, price, stock_type,dart_code) value ('137310', '에스디바이오센서', 9800, 'D', '00854997');
insert into stock(code, name, price, stock_type,dart_code) value ('004800', '효성', 59300, 'D', '00117188');
insert into stock(code, name, price, stock_type,dart_code) value ('001720', '신영증권', 73500, 'D', '00136721');
insert into stock(code, name, price, stock_type,dart_code) value ('103590', '일진전기', 25300, 'D', '00683469');
insert into stock(code, name, price, stock_type,dart_code) value ('145720', '덴티움', 108800, 'D', '00526599');
insert into stock(code, name, price, stock_type,dart_code) value ('069960', '현대백화점', 49950, 'D', '00428251');
insert into stock(code, name, price, stock_type,dart_code) value ('000400', '롯데손해보험', 3725, 'D', '00113562');
insert into stock(code, name, price, stock_type,dart_code) value ('248070', '솔루엠', 22850, 'D', '01159233');
insert into stock(code, name, price, stock_type,dart_code) value ('108320', 'LX세미콘', 70200, 'D', '00525934');
insert into stock(code, name, price, stock_type,dart_code) value ('001120', 'LX인터내셔널', 29400, 'D', '00120076');
insert into stock(code, name, price, stock_type,dart_code) value ('294870', 'HDC현대산업개발', 16980, 'D', '01310269');
insert into stock(code, name, price, stock_type,dart_code) value ('009970', '영원무역홀딩스', 81400, 'D', '00140964');
insert into stock(code, name, price, stock_type,dart_code) value ('353200', '대덕전자', 22400, 'D', '01478712');
insert into stock(code, name, price, stock_type,dart_code) value ('120110', '코오롱인더', 40050, 'D', '00795135');
insert into stock(code, name, price, stock_type,dart_code) value ('005180', '빙그레', 108600, 'D', '00124726');
insert into stock(code, name, price, stock_type,dart_code) value ('003620', 'KG모빌리티', 5460, 'D', '00138242');
insert into stock(code, name, price, stock_type,dart_code) value ('001740', 'SK네트웍스', 4790, 'D', '00131780');
insert into stock(code, name, price, stock_type,dart_code) value ('082740', '한화엔진', 12700, 'D', '00361008');
insert into stock(code, name, price, stock_type,dart_code) value ('267270', 'HD현대건설기계', 54700, 'D', '01205842');
insert into stock(code, name, price, stock_type,dart_code) value ('365550', 'ESR켄달스퀘어리츠', 4825, 'D', '01437186');
insert into stock(code, name, price, stock_type,dart_code) value ('006650', '대한유화', 157400, 'D', '00260383');
insert into stock(code, name, price, stock_type,dart_code) value ('089860', '롯데렌탈', 27750, 'D', '00545716');
insert into stock(code, name, price, stock_type,dart_code) value ('229640', 'LS에코에너지', 33150, 'D', '01093007');
insert into stock(code, name, price, stock_type,dart_code) value ('008730', '율촌화학', 40150, 'D', '00145260');
insert into stock(code, name, price, stock_type,dart_code) value ('003090', '대웅', 16670, 'D', '01013481');
insert into stock(code, name, price, stock_type,dart_code) value ('002840', '미원상사', 202500, 'D', '00121932');
insert into stock(code, name, price, stock_type,dart_code) value ('192080', '더블유게임즈', 43950, 'D', '01010110');
insert into stock(code, name, price, stock_type,dart_code) value ('001800', '오리온홀딩스', 15000, 'D', '00117577');
insert into stock(code, name, price, stock_type, eng_name) value ('MSFT', '마이크로소프트', 424.7, 'F', 'Microsoft Corp');
insert into stock(code, name, price, stock_type, eng_name) value ('AAPL', '애플', 196.9, 'F', 'Apple Inc');
insert into stock(code, name, price, stock_type, eng_name) value ('NVDA', '엔비디아', 120.37, 'F', 'NVIDIA Corp');
insert into stock(code, name, price, stock_type, eng_name) value ('AMZN', '아마존닷컴', 184.07, 'F', 'Amazon.com Inc');
insert into stock(code, name, price, stock_type, eng_name) value ('META', '메타 플랫폼스', 493.86, 'F', 'Meta Platforms Inc');
insert into stock(code, name, price, stock_type, eng_name) value ('GOOGL', '알파벳 Class A', 174.97, 'F', 'Alphabet Inc Class A');
insert into stock(code, name, price, stock_type, eng_name) value ('GOOG', '알파벳 Class C', 176.45, 'F', 'Alphabet Inc Class C');
insert into stock(code, name, price, stock_type, eng_name) value ('AVGO', '브로드컴', 1409.8, 'F', 'Broadcom Inc');
insert into stock(code, name, price, stock_type, eng_name) value ('TSLA', '테슬라', 176.06, 'F', 'Tesla Inc');
insert into stock(code, name, price, stock_type, eng_name) value ('ASML', 'ASML 홀딩 ADR', 1016.14, 'F', 'ASML Holding NV ADR');
insert into stock(code, name, price, stock_type, eng_name) value ('COST', '코스트코 홀세일', 847.18, 'F', 'Costco Wholesale Corp');
insert into stock(code, name, price, stock_type, eng_name) value ('NFLX', '넷플릭스', 641.01, 'F', 'Netflix Inc');
insert into stock(code, name, price, stock_type, eng_name) value ('AMD', '어드밴스드 마이크로 디바이시스(AMD)', 162.48, 'F', 'Advanced Micro Devices Inc');
insert into stock(code, name, price, stock_type, eng_name) value ('AZN', '아스트라제네카 ADR', 80.22, 'F', 'AstraZeneca PLC ADR');
insert into stock(code, name, price, stock_type, eng_name) value ('PEP', '펩시코', 170.11, 'F', 'PepsiCo Inc');
insert into stock(code, name, price, stock_type, eng_name) value ('QCOM', '퀄컴', 205.29, 'F', 'Qualcomm Inc');
insert into stock(code, name, price, stock_type, eng_name) value ('TMUS', 'T-모바일 US', 179.93, 'F', 'T-Mobile US Inc');
insert into stock(code, name, price, stock_type, eng_name) value ('ADBE', '어도비', 453.84, 'F', 'Adobe Inc');
insert into stock(code, name, price, stock_type, eng_name) value ('LIN', '린드', 432.73, 'F', 'Linde PLC');
insert into stock(code, name, price, stock_type, eng_name) value ('PDD', '핀둬둬 ADR', 143.66, 'F', 'PDD Holdings Inc ADR');
insert into stock(code, name, price, stock_type, eng_name) value ('SLM', 'SLM', 20.72, 'F', 'SLM Corp');
insert into stock(code, name, price, stock_type, eng_name) value ('TMDX', '트랜스메딕스 그룹', 135.21, 'F', 'Transmedics Group Inc');
insert into stock(code, name, price, stock_type, eng_name) value ('NVEI', '뉴베이', 32.15, 'F', 'Nuvei Corp');
insert into stock(code, name, price, stock_type, eng_name) value ('FELE', '프랭클린 일렉트릭', 95.4, 'F', 'Franklin Electric Co Inc');
insert into stock(code, name, price, stock_type, eng_name) value ('CRDO', '크레도 테크놀로지 그룹 홀딩', 27.83, 'F', 'Credo Technology Group Holding Ltd');
insert into stock(code, name, price, stock_type, eng_name) value ('SBNY', 'Signature Bank', 70.0, 'F', 'Signature Bank');
insert into stock(code, name, price, stock_type, eng_name) value ('FIZZ', '내셔널 베버리지', 46.45, 'F', 'National Beverage Corp');
insert into stock(code, name, price, stock_type, eng_name) value ('OZK', '뱅크 오즈크', 38.0, 'F', 'Bank Ozk');
insert into stock(code, name, price, stock_type, eng_name) value ('UBSI', '유나이티드 뱅크셰어스(Nasdaq GS)', 31.55, 'F', 'United Bankshares Inc');
insert into stock(code, name, price, stock_type, eng_name) value ('VRRM', '베라 모빌리티', 26.15, 'F', 'Verra Mobility Corp');
insert into stock(code, name, price, stock_type, eng_name) value ('IAC', 'IAC', 49.47, 'F', 'IAC Inc');
insert into stock(code, name, price, stock_type, eng_name) value ('ALVO', '알보테크', 13.98, 'F', 'Alvotech SA');
insert into stock(code, name, price, stock_type, eng_name) value ('LOPE', '그랜드 캐년 에듀케이션', 141.94, 'F', 'Grand Canyon Education Inc');
insert into stock(code, name, price, stock_type, eng_name) value ('POWI', '파워 인티그레이션', 73.32, 'F', 'Power Integrations Inc');
insert into stock(code, name, price, stock_type, eng_name) value ('GBDC', '골럽 캐피탈 BDC', 16.1, 'F', 'Golub Capital BDC Inc');
insert into stock(code, name, price, stock_type, eng_name) value ('IBRX', '이뮤니티바이오', 6.05, 'F', 'Immunitybio Inc');
insert into stock(code, name, price, stock_type, eng_name) value ('TIGO', '밀리콤 인터내셔널 셀룰러', 24.37, 'F', 'Millicom International Cellular SA');
insert into stock(code, name, price, stock_type, eng_name) value ('PI', '임핀지', 148.4, 'F', 'Impinj Inc');
insert into stock(code, name, price, stock_type, eng_name) value ('TSEM', '타워 세미컨덕터', 37.28, 'F', 'Tower Semiconductor Ltd');
insert into stock(code, name, price, stock_type, eng_name) value ('FORM', '폼팩터', 52.56, 'F', 'FormFactor Inc');
insert into stock(code, name, price, stock_type, eng_name) value ('CENX', '센추리 알루미늄', 15.69, 'F', 'Century Aluminum Co');
insert into stock(code, name, price, stock_type, eng_name) value ('KALU', '카이저 알루미늄', 90.23, 'F', 'Kaiser Aluminum Corp');
insert into stock(code, name, price, stock_type, eng_name) value ('TLRY', '틸레이 브랜즈', 1.78, 'F', 'Tilray Brands Inc');
insert into stock(code, name, price, stock_type, eng_name) value ('LGND', '리간드 파마슈티컬스', 80.61, 'F', 'Ligand Pharmaceuticals Inc');
insert into stock(code, name, price, stock_type, eng_name) value ('AVDL', '아바델 파마슈티컬스 ADR', 15.41, 'F', 'Avadel Pharmaceuticals PLC');
insert into stock(code, name, price, stock_type, eng_name) value ('CRCT', '크리컷', 6.7, 'F', 'Cricut Inc');
insert into stock(code, name, price, stock_type, eng_name) value ('MRTN', '마텐 트랜스포트', 17.57, 'F', 'Marten Transport Ltd');
insert into stock(code, name, price, stock_type, eng_name) value ('EVBG', '에버브릿지', 34.68, 'F', 'Everbridge Inc');
insert into stock(code, name, price, stock_type, eng_name) value ('SUPN', '슈퍼누스 파마슈티컬스', 25.99, 'F', 'Supernus Pharmaceuticals Inc');
insert into stock(code, name, price, stock_type, eng_name) value ('ATEC', '알파텍 홀딩스', 10.2, 'F', 'Alphatec Holdings Inc');
insert into stock(code, name, price, stock_type, eng_name) value ('DSGR', '디스트리뷰션 솔루션스 그룹', 30.55, 'F', 'Distribution Solutions Group Inc');
insert into stock(code, name, price, stock_type, eng_name) value ('MXL', '맥스리니어', 16.85, 'F', 'Maxlinear Inc');
insert into stock(code, name, price, stock_type, eng_name) value ('EFSC', '엔터프라이즈 파이낸셜 서비스', 37.82, 'F', 'Enterprise Financial Services Corp');
insert into stock(code, name, price, stock_type, eng_name) value ('UPWK', '업워크', 10.62, 'F', 'Upwork Inc');
insert into stock(code, name, price, stock_type, eng_name) value ('AFYA', '아피야', 16.1, 'F', 'Afya Ltd');
insert into stock(code, name, price, stock_type, eng_name) value ('PRDO', '퍼도세오 에듀케이션', 21.56, 'F', 'Perdoceo Education Corp');
insert into stock(code, name, price, stock_type, eng_name) value ('MRX', '마렉스 그룹', 19.89, 'F', 'Marex Group PLC');
insert into stock(code, name, price, stock_type, eng_name) value ('OXLC', '옥스포드 레인 캐피털', 5.67, 'F', 'Oxford Lane Capital Corp');
insert into stock(code, name, price, stock_type, eng_name) value ('BMBL', '범블', 11.1, 'F', 'Bumble Inc');
insert into stock(code, name, price, stock_type, eng_name) value ('ANIP', 'ANI 파마슈티컬스', 65.68, 'F', 'ANI Pharmaceuticals Inc');
insert into stock(code, name, price, stock_type, eng_name) value ('MITK', '마이텍 시스템즈', 12.13, 'F', 'Mitek Systems Inc');
insert into stock(code, name, price, stock_type, eng_name) value ('GOOD', '글래드스톤 커머셜', 14.35, 'F', 'Gladstone Commercial Corp');
insert into stock(code, name, price, stock_type, eng_name) value ('VINP', '빈치 파트너스 인베스트먼츠', 10.55, 'F', 'Vinci Partners Investments Ltd');
insert into stock(code, name, price, stock_type, eng_name) value ('NNDM', '나노 디멘션 ADR', 2.55, 'F', 'Nano Dimension Ltd ADR');
insert into stock(code, name, price, stock_type, eng_name) value ('NWTN', '이스트 스톤 애퀴지션', 2.0, 'F', 'NWTN Inc');
insert into stock(code, name, price, stock_type, eng_name) value ('PHAR', '파밍 그룹 ADR', 8.06, 'F', 'Pharming Group NV ADR');
insert into stock(code, name, price, stock_type, eng_name) value ('LXEO', '렉시오 테라퓨틱스', 17.11, 'F', 'Lexeo Therapeutics Inc');
insert into stock(code, name, price, stock_type, eng_name) value ('FRPH', 'FRP 홀딩스', 29.9, 'F', 'FRP Holdings Inc');
insert into stock(code, name, price, stock_type, eng_name) value ('KYTX', '카이버나 테라퓨틱스', 13.13, 'F', 'Kyverna Therapeutics Inc');
insert into stock(code, name, price, stock_type, eng_name) value ('TREE', '렌딩트리', 42.08, 'F', 'Lendingtree Inc');
insert into stock(code, name, price, stock_type, eng_name) value ('MLAB', '메사 래보라토리스', 103.76, 'F', 'Mesa Laboratories Inc');
insert into stock(code, name, price, stock_type, eng_name) value ('CASS', '캐스 인포메이션 시스템즈', 40.97, 'F', 'Cass Information Systems Inc');
insert into stock(code, name, price, stock_type, eng_name) value ('ERAS', '이래스카', 2.35, 'F', 'Erasca Inc');
insert into stock(code, name, price, stock_type, eng_name) value ('SCWX', '시큐어웍스', 6.01, 'F', 'SecureWorks Corp');
insert into stock(code, name, price, stock_type, eng_name) value ('CLFD', '클리어필드', 38.95, 'F', 'Clearfield Inc');
insert into stock(code, name, price, stock_type, eng_name) value ('GRPN', '그루폰', 14.31, 'F', 'Groupon Inc');
insert into stock(code, name, price, stock_type, eng_name) value ('LASR', '엔라이트', 11.65, 'F', 'nLIGHT Inc');
insert into stock(code, name, price, stock_type, eng_name) value ('LUNR', '인튜이티브 머신스', 4.52, 'F', 'Intuitive Machines Inc');
insert into stock(code, name, price, stock_type, eng_name) value ('ALTI', '알티 글로벌', 4.68, 'F', 'AlTi Global  Inc');
insert into stock(code, name, price, stock_type, eng_name) value ('CGNT', '코그나이트 소프트웨어', 7.78, 'F', 'Cognyte Software Ltd');
insert into stock(code, name, price, stock_type, eng_name) value ('JRVR', '제임스 리버 그룹 홀딩스', 7.51, 'F', 'James River Group Holdings Ltd');
insert into stock(code, name, price, stock_type, eng_name) value ('WTBA', '웨스트 뱅코프', 16.87, 'F', 'West Bancorporation Inc');
insert into stock(code, name, price, stock_type, eng_name) value ('MGNX', '매크로제닉스', 4.45, 'F', 'MacroGenics Inc');
insert into stock(code, name, price, stock_type, eng_name) value ('CRMD', '코메딕스', 5.12, 'F', 'CorMedix Inc');
insert into stock(code, name, price, stock_type, eng_name) value ('USAP', '유니버설 스테인리스 & 앨로이 프로덕츠', 31.44, 'F', 'Universal Stainless & Alloy Products Inc');
insert into stock(code, name, price, stock_type, eng_name) value ('IVCAU', 'Investcorp India Acquisition Units', 10.96, 'F', 'Investcorp India Acquisition Units');
insert into stock(code, name, price, stock_type, eng_name) value ('QRTEA', '큐레이트 리테일 시리즈 A', 0.72, 'F', 'Qurate Retail Inc Series A');
insert into stock(code, name, price, stock_type, eng_name) value ('GAMB', '갬블링닷컴 그룹', 7.71, 'F', 'Gambling.com Group Ltd');
insert into stock(code, name, price, stock_type, eng_name) value ('EMLDU', 'FTAC Emerald Acquisition Units', 10.96, 'F', 'FTAC Emerald Acquisition Units');
insert into stock(code, name, price, stock_type, eng_name) value ('RVNC', '레반스 테라퓨틱스', 2.66, 'F', 'Revance Therapeutics Inc');
insert into stock(code, name, price, stock_type, eng_name) value ('NATR', '네이처스 선샤인 프로덕츠', 14.87, 'F', 'Nature''s Sunshine Products Inc');
insert into stock(code, name, price, stock_type, eng_name) value ('UHG', '유나이티드 홈즈 그룹', 5.89, 'F', 'United Homes Group Inc');
insert into stock(code, name, price, stock_type, eng_name) value ('FBIZ', '퍼스트 비즈니스 파이낸셜 서비스', 33.73, 'F', 'First Business Financial Services Inc');
insert into stock(code, name, price, stock_type, eng_name) value ('XOMA', '조마', 23.5, 'F', 'XOMA Corp');
insert into stock(code, name, price, stock_type, eng_name) value ('VBNK', '버사뱅크', 10.81, 'F', 'VersaBank');
insert into stock(code, name, price, stock_type, eng_name) value ('PFTAU', 'Perception Capital Units', 10.8, 'F', 'Perception Capital Units');
insert into stock(code, name, price, stock_type, eng_name) value ('NATH', '네이선스 페이머스', 69.2, 'F', 'Nathan''s Famous Inc');
insert into stock(code, name, price, stock_type, eng_name) value ('VMD', '비메드 헬스케어', 7.15, 'F', 'Viemed Healthcare Inc');
insert into stock(code, name, price, stock_type, eng_name) value ('RCKY', '로키 브랜즈', 37.76, 'F', 'Rocky Brands Inc');
insert into stock(code, name, price, stock_type, eng_name) value ('IMAQU', 'International Media Acquisition Units', 12.15, 'F', 'International Media Acquisition Units');
insert into stock(code, name, price, stock_type, eng_name) value ('FULTP', '풀턴 파이낸셜 우선주 시리즈 A 5.125%', 19.04, 'F', 'Fulton Financial 1 40th DS Cum Prf Shs Series A');
insert into stock(code, name, price, stock_type, eng_name) value ('ALCYU', 'Alchemy Investments Acquisition 1 Units', 10.77, 'F', 'Alchemy Investments Acquisition 1 Units');
insert into stock(code, name, price, stock_type, eng_name) value ('OPTN', '옵티노우즈', 1.07, 'F', 'OptiNose Inc');
insert into stock(code, name, price, stock_type, eng_name) value ('AENT', '얼라이언스 엔터테인먼트 홀딩', 3.02, 'F', 'Alliance Entertainment Holding Corp');
insert into stock(code, name, price, stock_type, eng_name) value ('III', '인포메이션 서비스 그룹', 3.16, 'F', 'Information Services Group Inc');
insert into stock(code, name, price, stock_type, eng_name) value ('DSY', '플루토니안 애퀴지션', 3.94, 'F', 'Plutonian Acquisition Corp');
insert into stock(code, name, price, stock_type, eng_name) value ('RELL', '리처드슨 일렉트로닉스', 10.65, 'F', 'Richardson Electronics Ltd');
insert into stock(code, name, price, stock_type, eng_name) value ('ESHA', 'ESH 애퀴지션', 10.43, 'F', 'ESH Acquisition Corp');
insert into stock(code, name, price, stock_type, eng_name) value ('FNGR', '핑거모션', 2.94, 'F', 'FingerMotion Inc');
insert into stock(code, name, price, stock_type, eng_name) value ('ADVM', '애드베럼 바이오테크놀로지스', 7.34, 'F', 'Adverum Biotechnologies Inc');
insert into stock(code, name, price, stock_type, eng_name) value ('BDSX', '바이오데식스', 1.35, 'F', 'Biodesix Inc');
insert into stock(code, name, price, stock_type, eng_name) value ('RCMT', 'RCM 테크놀로지스', 19.49, 'F', 'R C M Technologies Inc');
insert into stock(code, name, price, stock_type, eng_name) value ('SIFY', '사이피 테크놀러지 ADR', 0.68, 'F', 'Sify Technologies Ltd ADR');
insert into stock(code, name, price, stock_type, eng_name) value ('IMAB', '아이맵 ADR', 1.91, 'F', 'I-Mab ADR');
insert into stock(code, name, price, stock_type, eng_name) value ('PESI', '퍼마-픽스 인바이런먼털 서비스', 9.6, 'F', 'Perma-Fix Environmental Services Inc');
insert into stock(code, name, price, stock_type, eng_name) value ('KOD', '코디악 사이언스', 2.85, 'F', 'Kodiak Sciences Inc');
insert into stock(code, name, price, stock_type, eng_name) value ('HOWL', '웨어울프 테라퓨틱스', 3.18, 'F', 'Werewolf Therapeutics Inc');
insert into stock(code, name, price, stock_type, eng_name) value ('PWOD', '펜스 우즈 뱅코프', 20.22, 'F', 'Penns Woods Bancorp Inc');
insert into stock(code, name, price, stock_type, eng_name) value ('STI', '솔리디온 테크놀로지', 1.71, 'F', 'Solidion Technology Inc');
insert into stock(code, name, price, stock_type, eng_name) value ('CFFI', 'C&F 파이낸셜', 44.31, 'F', 'C&F Financial Corp');
insert into stock(code, name, price, stock_type, eng_name) value ('IKNA', '아이케나 온콜로지', 1.75, 'F', 'Ikena Oncology Inc');
insert into stock(code, name, price, stock_type, eng_name) value ('SCYX', '사이넥시스', 2.2, 'F', 'SCYNEXIS Inc');
insert into stock(code, name, price, stock_type, eng_name) value ('BUJA', '부킷 잘릴 글로벌 애퀴지션 1', 10.74, 'F', 'Bukit Jalil Global Acquisition 1 Ltd');
insert into stock(code, name, price, stock_type, eng_name) value ('FORA', '포리안', 2.78, 'F', 'Forian Inc');
insert into stock(code, name, price, stock_type, eng_name) value ('SLS', '셀라스 라이프 사이언스 그룹', 1.36, 'F', 'Sellas Life Sciences Group Inc');
insert into stock(code, name, price, stock_type, eng_name) value ('CMRX', '키메릭스', 0.91, 'F', 'Chimerix Inc');
insert into stock(code, name, price, stock_type, eng_name) value ('BIRD', '올버즈', 0.53, 'F', 'Allbirds Inc');
insert into stock(code, name, price, stock_type, eng_name) value ('VOR', '보어 바이오파마', 1.2, 'F', 'Vor Biopharma Inc');
insert into stock(code, name, price, stock_type, eng_name) value ('EMCG', '임브레이스 체인지 애퀴지션', 11.26, 'F', 'Embrace Change Acquisition Corp');
insert into stock(code, name, price, stock_type, eng_name) value ('MRNS', '매리너스 파마슈티컬스', 1.5, 'F', 'Marinus Pharmaceuticals Inc');
insert into stock(code, name, price, stock_type, eng_name) value ('BUJAU', 'Bukit Jalil Global Acquisition 1 Units', 10.71, 'F', 'Bukit Jalil Global Acquisition 1 Units');
insert into stock(code, name, price, stock_type, eng_name) value ('SURG', '서지페이즈', 4.3, 'F', 'Surgepays Inc');
insert into stock(code, name, price, stock_type, eng_name) value ('ELUT', '엘루시아', 3.34, 'F', 'Elutia Inc');
insert into stock(code, name, price, stock_type, eng_name) value ('FIAC', '포커스 임팩트 애퀴지션', 11.1, 'F', 'Focus Impact Acquisition Corp');
insert into stock(code, name, price, stock_type, eng_name) value ('MAXN', '맥시온솔라테크놀로지스', 1.53, 'F', 'Maxeon Solar Technologies Ltd');
insert into stock(code, name, price, stock_type, eng_name) value ('GLST', '글로벌 스타 애퀴지션', 11.44, 'F', 'Global Star Acquisition Inc');
insert into stock(code, name, price, stock_type, eng_name) value ('IRAA', '아이리스 애퀴지션', 11.45, 'F', 'Iris Acquisition Corp');
insert into stock(code, name, price, stock_type, eng_name) value ('SIEB', '시버트 파이낸셜 코퍼레이션', 2.07, 'F', 'Siebert Financial Corp');
insert into stock(code, name, price, stock_type, eng_name) value ('BLEU', '블루아카시아', 10.91, 'F', 'Bleuacacia Ltd');
insert into stock(code, name, price, stock_type, eng_name) value ('RSSS', '리서치 솔루션스', 2.51, 'F', 'Research Solutions Inc');
insert into stock(code, name, price, stock_type, eng_name) value ('CDTG', 'CDT 인바이어런먼털 테크놀로지 인베스트먼트 홀딩스', 4.12, 'F', 'CDT Environmental Technology Investment Holdings Ltd');
insert into stock(code, name, price, stock_type, eng_name) value ('OSS', '원 스탑 시스템', 2.21, 'F', 'One Stop Systems Inc');
insert into stock(code, name, price, stock_type, eng_name) value ('LINK', '인터링크 일렉트로닉스', 4.26, 'F', 'Interlink Electronics Inc');
insert into stock(code, name, price, stock_type, eng_name) value ('BLAC', '벨뷰 라이프 사이언시스 애퀴지션', 10.74, 'F', 'Bellevue Life Sciences Acquisition Corp');
insert into stock(code, name, price, stock_type, eng_name) value ('YOTA', '요타 애퀴지션', 11.0, 'F', 'Yotta Acquisition Corp');
insert into stock(code, name, price, stock_type, eng_name) value ('DXR', '닥소', 9.05, 'F', 'Daxor Corp');
insert into stock(code, name, price, stock_type, eng_name) value ('AIRE', '리알파 테크', 1.0, 'F', 'reAlpha Tech Corp');
insert into stock(code, name, price, stock_type, eng_name) value ('DUET', '듀엣 애퀴지션', 11.06, 'F', 'DUET Acquisition Corp');
insert into stock(code, name, price, stock_type, eng_name) value ('OPHC', '옵티멈뱅크 홀딩스', 4.47, 'F', 'OptimumBank Holdings Inc');
insert into stock(code, name, price, stock_type, eng_name) value ('CPTN', '셉톤', 2.84, 'F', 'Cepton Inc');
insert into stock(code, name, price, stock_type, eng_name) value ('HSON', '허드슨 글로벌', 15.2, 'F', 'Hudson Global Inc');
insert into stock(code, name, price, stock_type, eng_name) value ('RVPH', '리비바 파마슈티컬스 홀딩스', 1.42, 'F', 'Reviva Pharmaceuticals Holdings  Inc.');
insert into stock(code, name, price, stock_type, eng_name) value ('OKYO', 'OKYO 파마 ADR', 1.39, 'F', 'OKYO Pharma Ltd');
insert into stock(code, name, price, stock_type, eng_name) value ('AADI', '아디 바이오사이언스', 1.72, 'F', 'Aadi Bioscience Inc');
insert into stock(code, name, price, stock_type, eng_name) value ('PODC', '포드캐스톤', 1.81, 'F', 'Podcastone Inc');
insert into stock(code, name, price, stock_type, eng_name) value ('CODX', '코다이아그나스틱스', 1.45, 'F', 'Co-Diagnostics Inc');
insert into stock(code, name, price, stock_type, eng_name) value ('KOSS', '코스', 4.45, 'F', 'Koss Corp');
insert into stock(code, name, price, stock_type, eng_name) value ('ALGS', '앨리고스 테라퓨틱스', 0.55, 'F', 'Aligos Therapeutics Inc');
insert into stock(code, name, price, stock_type, eng_name) value ('LEXX', '렉사리아 바이오사이언스', 3.3, 'F', 'Lexaria Bioscience Corp');
insert into stock(code, name, price, stock_type, eng_name) value ('RAND', '랜드 캐피탈', 16.9, 'F', 'Rand Capital Corp');
insert into stock(code, name, price, stock_type, eng_name) value ('VERB', '버브 테크놀러지', 0.14, 'F', 'Verb Technology Company Inc');
insert into stock(code, name, price, stock_type, eng_name) value ('MTEX', '매나테크', 8.0, 'F', 'Mannatech Inc');
insert into stock(code, name, price, stock_type, eng_name) value ('DXYN', '딕시 그룹', 0.92, 'F', 'Dixie Group Inc');
insert into stock(code, name, price, stock_type, eng_name) value ('CMMB', '키모맵 테라퓨틱스 ADR', 1.05, 'F', 'Chemomab Therapeutics Ltd ADR');
insert into stock(code, name, price, stock_type, eng_name) value ('SGLY', '싱귤러리티 퓨처 테크놀로지', 3.98, 'F', 'Singularity Future Technology Ltd');
insert into stock(code, name, price, stock_type, eng_name) value ('FTFT', '퓨처 핀테크 그룹', 0.75, 'F', 'Future Fintech Group Inc');
insert into stock(code, name, price, stock_type, eng_name) value ('FLGC', '플로라 그로스', 1.2, 'F', 'Flora Growth Corp');
insert into stock(code, name, price, stock_type, eng_name) value ('EDUC', '에듀케이셔널 디벨롭먼트', 1.71, 'F', 'Educational Development Corp');
insert into stock(code, name, price, stock_type, eng_name) value ('FRES', '프레시2 그룹 ADR', 0.41, 'F', 'Fresh2 Group Ltd ADR');
insert into stock(code, name, price, stock_type, eng_name) value ('MNPR', '모노파 테라퓨틱스', 0.84, 'F', 'Monopar Therapeutics Inc');
insert into stock(code, name, price, stock_type, eng_name) value ('INTJ', '인텔리전트 그룹', 1.05, 'F', 'Intelligent Group Ltd');
insert into stock(code, name, price, stock_type, eng_name) value ('QTI', 'QT 이미징 홀딩스', 0.67, 'F', 'QT Imaging Holdings Inc');
insert into stock(code, name, price, stock_type, eng_name) value ('YJ', '윤지 ADR', 0.7, 'F', 'Yunji Inc ADR');
insert into stock(code, name, price, stock_type, eng_name) value ('GLTO', '갈렉토', 0.53, 'F', 'Galecto Inc');
insert into stock(code, name, price, stock_type, eng_name) value ('ASTR', '아스트라 스페이스', 0.59, 'F', 'Astra Space Inc');
insert into stock(code, name, price, stock_type, eng_name) value ('ELSE', '일렉트로-센서스', 4.04, 'F', 'Electro-Sensors Inc');
insert into stock(code, name, price, stock_type, eng_name) value ('UCAR', '유 파워', 5.38, 'F', 'U Power Ltd');
insert into stock(code, name, price, stock_type, eng_name) value ('YGMZ', '명주 로지스틱 홀딩스', 0.36, 'F', 'MingZhu Logistics Holdings Ltd');
insert into stock(code, name, price, stock_type, eng_name) value ('HYW', '해인 금융 지주 그룹 ADR', 0.42, 'F', 'Hywin Holdings Ltd ADR');
insert into stock(code, name, price, stock_type, eng_name) value ('ONVO', '오가노보 홀딩스', 0.97, 'F', 'Organovo Holdings Inc');
insert into stock(code, name, price, stock_type, eng_name) value ('DBGI', '디지털 브랜즈 그룹', 1.61, 'F', 'Digital Brands Group Inc');
insert into stock(code, name, price, stock_type, eng_name) value ('CYTO', '알타미라 테라퓨틱스', 1.39, 'F', 'Altamira Therapeutics Ltd');
insert into stock(code, name, price, stock_type, eng_name) value ('SNOA', '소노마 파머수티컬스', 0.21, 'F', 'Sonoma Pharmaceuticals Inc');
insert into stock(code, name, price, stock_type, eng_name) value ('ATXI', '애버뉴 테라퓨틱스', 3.37, 'F', 'Avenue Therapeutics Inc');
insert into stock(code, name, price, stock_type, eng_name) value ('XYLO', '자일로 테크놀로지스 ADR', 1.65, 'F', 'Xylo Technologies Ltd ADR');
insert into stock(code, name, price, stock_type, eng_name) value ('XHG', 'X체인지 TEC.INC ADR', 0.74, 'F', 'XChange TEC.INC ADR');
insert into stock(code, name, price, stock_type, eng_name) value ('FRGT', '프라이트 테크놀로지스', 0.59, 'F', 'Freight Technologies Inc');
insert into stock(code, name, price, stock_type, eng_name) value ('SINT', 'SINTX 테크놀로지스', 5.04, 'F', 'SINTX Technologies Inc');
insert into stock(code, name, price, stock_type, eng_name) value ('HSDT', '헬리우스 메디컬 테크놀로지스', 1.23, 'F', 'Helius Medical Technologies Inc');
insert into stock(code, name, price, stock_type, eng_name) value ('TCON', '트라콘 파마슈티컬스', 1.13, 'F', 'TRACON Pharmaceuticals Inc');
insert into stock(code, name, price, stock_type, eng_name) value ('SBET', '샤프링크 게이밍', 0.9, 'F', 'Sharplink Gaming Inc');
insert into stock(code, name, price, stock_type, eng_name) value ('AUUD', '아우디아', 1.08, 'F', 'Auddia Inc');
insert into stock(code, name, price, stock_type, eng_name) value ('BACK', 'IMAC 홀딩스', 2.52, 'F', 'IMAC Holdings Inc');
insert into stock(code, name, price, stock_type, eng_name) value ('INVO', 'INVO 바이오사이언스', 0.77, 'F', 'INVO Bioscience Inc');
insert into stock(code, name, price, stock_type, eng_name) value ('ZCMD', '중차오', 1.17, 'F', 'Zhongchao Inc');
insert into stock(code, name, price, stock_type, eng_name) value ('AEMD', '애슬론 메디컬', 0.55, 'F', 'Aethlon Medical Inc');
insert into stock(code, name, price, stock_type, eng_name) value ('CYCC', '사이클라셀 파마슈티컬스', 1.94, 'F', 'Cyclacel Pharmaceuticals Inc');
insert into stock(code, name, price, stock_type, eng_name) value ('WNW', '메이우 테크놀로지', 1.03, 'F', 'Meiwu Technology Co Ltd');
insert into stock(code, name, price, stock_type, eng_name) value ('SEEL', '실로스 테라퓨틱스', 1.09, 'F', 'Seelos Therapeutics Inc');
