insert into product(id, name, corp_id, p_type) value(1, 'Sh첫만남우대예금', 11, 'DEPOSIT');
insert into deposit_product value(1);
insert into product(id, name, corp_id, p_type) value(2, 'NH고향사랑기부예금', 10, 'DEPOSIT');
insert into deposit_product value(2);
insert into product(id, name, corp_id, p_type) value(3, 'DGB주거래우대예금(첫만남고객형)', 12, 'DEPOSIT');
insert into deposit_product value(3);
insert into product(id, name, corp_id, p_type) value(4, 'JB 최강전북 축구사랑 예금', 13, 'DEPOSIT');
insert into deposit_product value(4);
insert into product(id, name, corp_id, p_type) value(5, 'The 든든 예금', 14, 'DEPOSIT');
insert into deposit_product value(5);
insert into product(id, name, corp_id, p_type) value(6, 'BNK코리보연동정기예금', 14, 'DEPOSIT');
insert into deposit_product value(6);
insert into product(id, name, corp_id, p_type) value(7, 'DGB함께예금', 12, 'DEPOSIT');
insert into deposit_product value(7);
insert into product(id, name, corp_id, p_type) value(8, 'J 정기예금', 15, 'DEPOSIT');
insert into deposit_product value(8);
insert into product(id, name, corp_id, p_type) value(9, 'IBK D-Day통장(단기중금채)', 9, 'DEPOSIT');
insert into deposit_product value(9);
insert into product(id, name, corp_id, p_type) value(10, 'IBK평생한가족통장[중금채]', 9, 'DEPOSIT');
insert into deposit_product value(10);
insert into product(id, name, corp_id, p_type) value(11, 'Sh해양플라스틱Zero!예금', 11, 'DEPOSIT');
insert into deposit_product value(11);
insert into product(id, name, corp_id, p_type) value(12, '직장인우대예금', 12, 'DEPOSIT');
insert into deposit_product value(12);
insert into product(id, name, corp_id, p_type) value(13, 'KIA타이거즈 우승기원 예금', 16, 'DEPOSIT');
insert into deposit_product value(13);
insert into product(id, name, corp_id, p_type) value(14, 'BNK주거래우대정기예금', 14, 'DEPOSIT');
insert into deposit_product value(14);
insert into product(id, name, corp_id, p_type) value(15, 'JB 1·2·3 정기예금', 13, 'DEPOSIT');
insert into deposit_product value(15);
insert into product(id, name, corp_id, p_type) value(16, 'e-그린세이브예금', 17, 'DEPOSIT');
insert into deposit_product value(16);
insert into product(id, name, corp_id, p_type) value(17, '스마일드림정기예금', 15, 'DEPOSIT');
insert into deposit_product value(17);
insert into product(id, name, corp_id, p_type) value(18, '굿스타트예금', 16, 'DEPOSIT');
insert into deposit_product value(18);
insert into product(id, name, corp_id, p_type) value(19, '더(The) 특판 정기예금', 18, 'DEPOSIT');
insert into deposit_product value(19);
insert into product(id, name, corp_id, p_type) value(20, 'IBK평생한가족통장[정기예금]', 9, 'DEPOSIT');
insert into deposit_product value(20);
insert into product(id, name, corp_id, p_type) value(21, 'IM스마트예금', 12, 'DEPOSIT');
insert into deposit_product value(21);
insert into product(id, name, corp_id, p_type) value(22, 'DGB주거래우대예금(단골고객형)', 12, 'DEPOSIT');
insert into deposit_product value(22);
insert into product(id, name, corp_id, p_type) value(23, 'JB Smart-App 예금', 13, 'DEPOSIT');
insert into deposit_product value(23);
insert into product(id, name, corp_id, p_type) value(24, '신한 My플러스 정기예금', 19, 'DEPOSIT');
insert into deposit_product value(24);
insert into product(id, name, corp_id, p_type) value(25, 'Tops CD연동 정기예금', 19, 'DEPOSIT');
insert into deposit_product value(25);
insert into product(id, name, corp_id, p_type) value(26, '우리 첫거래우대 정기예금', 20, 'DEPOSIT');
insert into deposit_product value(26);
insert into product(id, name, corp_id, p_type) value(27, '1석7조통장(중금채)', 9, 'DEPOSIT');
insert into deposit_product value(27);
insert into product(id, name, corp_id, p_type) value(28, 'NH올원e예금', 10, 'DEPOSIT');
insert into deposit_product value(28);
insert into product(id, name, corp_id, p_type) value(29, 'NH왈츠회전예금II', 10, 'DEPOSIT');
insert into deposit_product value(29);
insert into product(id, name, corp_id, p_type) value(30, '(The 고마워요 5월) 특판 예금', 13, 'DEPOSIT');
insert into deposit_product value(30);
insert into product(id, name, corp_id, p_type) value(31, 'BNK MY 원 픽 정기예금', 14, 'DEPOSIT');
insert into deposit_product value(31);
insert into product(id, name, corp_id, p_type) value(32, 'WON플러스 예금', 20, 'DEPOSIT');
insert into deposit_product value(32);
insert into product(id, name, corp_id, p_type) value(33, 'JB 주거래 예금', 13, 'DEPOSIT');
insert into deposit_product value(33);
insert into product(id, name, corp_id, p_type) value(34, '행운박스예금', 16, 'DEPOSIT');
insert into deposit_product value(34);
insert into product(id, name, corp_id, p_type) value(35, 'KDB 정기예금', 21, 'DEPOSIT');
insert into deposit_product value(35);
insert into product(id, name, corp_id, p_type) value(36, '코드K 정기예금', 22, 'DEPOSIT');
insert into deposit_product value(36);
insert into product(id, name, corp_id, p_type) value(37, 'NH내가Green초록세상예금', 10, 'DEPOSIT');
insert into deposit_product value(37);
insert into product(id, name, corp_id, p_type) value(38, '쏠편한 정기예금', 19, 'DEPOSIT');
insert into deposit_product value(38);
insert into product(id, name, corp_id, p_type) value(39, '하나의 정기예금', 23, 'DEPOSIT');
insert into deposit_product value(39);
insert into product(id, name, corp_id, p_type) value(40, '스마트모아Dream정기예금', 16, 'DEPOSIT');
insert into deposit_product value(40);
insert into product(id, name, corp_id, p_type) value(41, 'JB다이렉트예금', 13, 'DEPOSIT');
insert into deposit_product value(41);
insert into product(id, name, corp_id, p_type) value(42, 'The플러스예금', 16, 'DEPOSIT');
insert into deposit_product value(42);
insert into product(id, name, corp_id, p_type) value(43, 'BNK더조은정기예금', 14, 'DEPOSIT');
insert into deposit_product value(43);
insert into product(id, name, corp_id, p_type) value(44, 'JB 골든 에이지 예금', 13, 'DEPOSIT');
insert into deposit_product value(44);
insert into product(id, name, corp_id, p_type) value(45, '친환경녹색예금', 12, 'DEPOSIT');
insert into deposit_product value(45);
insert into product(id, name, corp_id, p_type) value(46, 'LIVE정기예금', 18, 'DEPOSIT');
insert into deposit_product value(46);
insert into product(id, name, corp_id, p_type) value(47, 'DGB행복파트너예금(연금형)', 12, 'DEPOSIT');
insert into deposit_product value(47);
insert into product(id, name, corp_id, p_type) value(48, '자유만기회전예금', 12, 'DEPOSIT');
insert into deposit_product value(48);
insert into product(id, name, corp_id, p_type) value(49, 'SC제일 친환경비움예금', 17, 'DEPOSIT');
insert into deposit_product value(49);
insert into product(id, name, corp_id, p_type) value(50, '중도해지 괜찮Wa예금', 16, 'DEPOSIT');
insert into deposit_product value(50);
insert into product(id, name, corp_id, p_type) value(51, '큰만족실세예금', 10, 'DEPOSIT');
insert into deposit_product value(51);
insert into product(id, name, corp_id, p_type) value(52, '1석7조통장(정기예금)', 9, 'DEPOSIT');
insert into deposit_product value(52);
insert into product(id, name, corp_id, p_type) value(53, '카카오뱅크 정기예금', 24, 'DEPOSIT');
insert into deposit_product value(53);
insert into product(id, name, corp_id, p_type) value(54, '플러스다모아예금', 16, 'DEPOSIT');
insert into deposit_product value(54);
insert into product(id, name, corp_id, p_type) value(55, '이자먼저Wa예금', 16, 'DEPOSIT');
insert into deposit_product value(55);
insert into product(id, name, corp_id, p_type) value(56, 'IBK혁신창업기업응원통장[실세금리정기예금]', 9, 'DEPOSIT');
insert into deposit_product value(56);
insert into product(id, name, corp_id, p_type) value(57, '스마트 정기예금', 13, 'DEPOSIT');
insert into deposit_product value(57);
insert into product(id, name, corp_id, p_type) value(58, '자유적립식예금', 12, 'DEPOSIT');
insert into deposit_product value(58);
insert into product(id, name, corp_id, p_type) value(59, '마니마니정기예금', 14, 'DEPOSIT');
insert into deposit_product value(59);
insert into product(id, name, corp_id, p_type) value(60, 'IBK혁신창업기업응원통장[중소기업금융채권]', 9, 'DEPOSIT');
insert into deposit_product value(60);
insert into product(id, name, corp_id, p_type) value(61, '독도사랑예금', 11, 'DEPOSIT');
insert into deposit_product value(61);
insert into product(id, name, corp_id, p_type) value(62, '사랑해정기예금(실세금리정기예금)', 11, 'DEPOSIT');
insert into deposit_product value(62);
insert into product(id, name, corp_id, p_type) value(63, '실세금리정기예금', 9, 'DEPOSIT');
insert into deposit_product value(63);
insert into product(id, name, corp_id, p_type) value(64, '어촌복지예금 (거치식예금)', 11, 'DEPOSIT');
insert into deposit_product value(64);
insert into product(id, name, corp_id, p_type) value(65, '제주DREAM 정기예금', 15, 'DEPOSIT');
insert into deposit_product value(65);
insert into product(id, name, corp_id, p_type) value(66, 'NH더하고나눔정기예금', 10, 'DEPOSIT');
insert into deposit_product value(66);
insert into product(id, name, corp_id, p_type) value(67, '국민수퍼정기예금(CD금리연동형)', 25, 'DEPOSIT');
insert into deposit_product value(67);
insert into product(id, name, corp_id, p_type) value(68, '미래설계 장기플랜 연금예금', 19, 'DEPOSIT');
insert into deposit_product value(68);
insert into product(id, name, corp_id, p_type) value(69, '미래설계 크레바스 연금예금', 19, 'DEPOSIT');
insert into deposit_product value(69);
insert into product(id, name, corp_id, p_type) value(70, '플러스정기예금', 12, 'DEPOSIT');
insert into deposit_product value(70);
insert into product(id, name, corp_id, p_type) value(71, 'BNK내맘대로 예금', 18, 'DEPOSIT');
insert into deposit_product value(71);
insert into product(id, name, corp_id, p_type) value(72, 'KB국민UP정기예금', 25, 'DEPOSIT');
insert into deposit_product value(72);
insert into product(id, name, corp_id, p_type) value(73, '정기예금', 9, 'DEPOSIT');
insert into deposit_product value(73);
insert into product(id, name, corp_id, p_type) value(74, '토스뱅크 먼저 이자 받는 정기예금', 26, 'DEPOSIT');
insert into deposit_product value(74);
insert into product(id, name, corp_id, p_type) value(75, '3·6·9 정기예금', 23, 'DEPOSIT');
insert into deposit_product value(75);
insert into product(id, name, corp_id, p_type) value(76, '우리 SUPER 정기예금', 20, 'DEPOSIT');
insert into deposit_product value(76);
insert into product(id, name, corp_id, p_type) value(77, '맞춤형 자유만기 정기예금', 13, 'DEPOSIT');
insert into deposit_product value(77);
insert into product(id, name, corp_id, p_type) value(78, 'IBK회전정기예금', 9, 'DEPOSIT');
insert into deposit_product value(78);
insert into product(id, name, corp_id, p_type) value(79, '장기회전정기예금', 18, 'DEPOSIT');
insert into deposit_product value(79);
insert into product(id, name, corp_id, p_type) value(80, '정기예금', 10, 'DEPOSIT');
insert into deposit_product value(80);
insert into product(id, name, corp_id, p_type) value(81, '정기예금', 15, 'DEPOSIT');
insert into deposit_product value(81);
insert into product(id, name, corp_id, p_type) value(82, 'JB FUN 세이브 통장', 13, 'DEPOSIT');
insert into deposit_product value(82);
insert into product(id, name, corp_id, p_type) value(83, 'JB회전정기예금', 13, 'DEPOSIT');
insert into deposit_product value(83);
insert into product(id, name, corp_id, p_type) value(84, '시장금리부 정기예금', 13, 'DEPOSIT');
insert into deposit_product value(84);
insert into product(id, name, corp_id, p_type) value(85, '신한 S드림(DREAM) 정기예금', 19, 'DEPOSIT');
insert into deposit_product value(85);
insert into product(id, name, corp_id, p_type) value(86, '사랑해나누리예금', 11, 'DEPOSIT');
insert into deposit_product value(86);
insert into product(id, name, corp_id, p_type) value(87, '퍼스트정기예금', 17, 'DEPOSIT');
insert into deposit_product value(87);
insert into product(id, name, corp_id, p_type) value(88, 'JB 참 괜찮은 정기예금', 13, 'DEPOSIT');
insert into deposit_product value(88);
insert into product(id, name, corp_id, p_type) value(89, 'Tops 회전 정기예금', 19, 'DEPOSIT');
insert into deposit_product value(89);
insert into product(id, name, corp_id, p_type) value(90, '정기예금', 13, 'DEPOSIT');
insert into deposit_product value(90);
insert into product(id, name, corp_id, p_type) value(91, '럭키한 쿠폰 예금', 13, 'DEPOSIT');
insert into deposit_product value(91);
insert into product(id, name, corp_id, p_type) value(92, '퍼스트정기예금(회전식)', 17, 'DEPOSIT');
insert into deposit_product value(92);
insert into product(id, name, corp_id, p_type) value(93, '국민수퍼정기예금(개인)', 25, 'DEPOSIT');
insert into deposit_product value(93);
insert into product(id, name, corp_id, p_type) value(94, 'Sh평생주거래우대예금', 11, 'DEPOSIT');
insert into deposit_product value(94);
insert into product(id, name, corp_id, p_type) value(95, '메리트정기예금', 18, 'DEPOSIT');
insert into deposit_product value(95);
insert into product(id, name, corp_id, p_type) value(96, '일반 정기예금', 21, 'DEPOSIT');
insert into deposit_product value(96);
insert into product(id, name, corp_id, p_type) value(97, '일반정기예금', 16, 'DEPOSIT');
insert into deposit_product value(97);
insert into product(id, name, corp_id, p_type) value(98, '정기예금', 19, 'DEPOSIT');
insert into deposit_product value(98);
insert into product(id, name, corp_id, p_type) value(99, '정기예금', 20, 'DEPOSIT');
insert into deposit_product value(99);
insert into product(id, name, corp_id, p_type) value(100, '고단위 플러스(금리연동형)', 23, 'DEPOSIT');
insert into deposit_product value(100);
insert into product(id, name, corp_id, p_type) value(101, '고단위 플러스(금리확정형)', 23, 'DEPOSIT');
insert into deposit_product value(101);
insert into product(id, name, corp_id, p_type) value(102, '정기예금', 23, 'DEPOSIT');
insert into deposit_product value(102);
insert into product(id, name, corp_id, p_type) value(103, '일반정기예금', 25, 'DEPOSIT');
insert into deposit_product value(103);
insert into product(id, name, corp_id, p_type) value(104, '장기회전정기예금', 14, 'DEPOSIT');
insert into deposit_product value(104);
insert into product(id, name, corp_id, p_type) value(105, '정기예금', 14, 'DEPOSIT');
insert into deposit_product value(105);
insert into product(id, name, corp_id, p_type) value(106, '회전플러스정기예금', 18, 'DEPOSIT');
insert into deposit_product value(106);
insert into product(id, name, corp_id, p_type) value(107, '일반정기예금', 11, 'DEPOSIT');
insert into deposit_product value(107);
insert into product(id, name, corp_id, p_type) value(108, '두루두루정기예금', 20, 'DEPOSIT');
insert into deposit_product value(108);
insert into product(id, name, corp_id, p_type) value(109, 'JB슈퍼씨드 적금', 13, 'SAVING');
insert into saving_product value(109);
insert into product(id, name, corp_id, p_type) value(110, '데일리 워킹 적금', 20, 'SAVING');
insert into saving_product value(110);
insert into product(id, name, corp_id, p_type) value(111, 'NH 상생+아이행복적금', 10, 'SAVING');
insert into saving_product value(111);
insert into product(id, name, corp_id, p_type) value(112, '우리 사장님 활짝 핀 적금', 20, 'SAVING');
insert into saving_product value(112);
insert into product(id, name, corp_id, p_type) value(113, '온국민 건강적금-골든라이프', 25, 'SAVING');
insert into saving_product value(113);
insert into product(id, name, corp_id, p_type) value(114, '주거래기업부금(정액적립식)', 9, 'SAVING');
insert into saving_product value(114);
insert into product(id, name, corp_id, p_type) value(115, 'BNK아기천사적금', 18, 'SAVING');
insert into saving_product value(115);
insert into product(id, name, corp_id, p_type) value(116, '터치 적금', 14, 'DEPOSIT');
insert into deposit_product value(116);
insert into product(id, name, corp_id, p_type) value(117, 'KB차차차 적금', 25, 'SAVING');
insert into saving_product value(117);
insert into product(id, name, corp_id, p_type) value(118, '하나 아이키움 적금', 23, 'SAVING');
insert into saving_product value(118);
insert into product(id, name, corp_id, p_type) value(119, '온국민 건강적금', 25, 'SAVING');
insert into saving_product value(119);
insert into product(id, name, corp_id, p_type) value(120, 'IBK장병내일준비적금', 9, 'SAVING');
insert into saving_product value(120);
insert into product(id, name, corp_id, p_type) value(121, '우리페이 적금', 20, 'SAVING');
insert into saving_product value(121);
insert into product(id, name, corp_id, p_type) value(122, 'KB장병내일준비적금', 25, 'SAVING');
insert into saving_product value(122);
insert into product(id, name, corp_id, p_type) value(123, 'IBK탄소제로적금', 9, 'SAVING');
insert into saving_product value(123);
insert into product(id, name, corp_id, p_type) value(124, '카카오뱅크 한달적금', 24, 'SAVING');
insert into saving_product value(124);
insert into product(id, name, corp_id, p_type) value(125, '새희망적금', 16, 'SAVING');
insert into saving_product value(125);
insert into product(id, name, corp_id, p_type) value(126, 'NH1418스윙적금', 10, 'SAVING');
insert into saving_product value(126);
insert into product(id, name, corp_id, p_type) value(127, '청년 처음적금', 19, 'SAVING');
insert into saving_product value(127);
insert into product(id, name, corp_id, p_type) value(128, 'IBK부모급여우대적금', 9, 'SAVING');
insert into saving_product value(128);
insert into product(id, name, corp_id, p_type) value(129, 'BNK 위더스(With-Us) 자유적금', 14, 'DEPOSIT');
insert into deposit_product value(129);
insert into product(id, name, corp_id, p_type) value(130, '원비즈플라자 멤버십 적금', 20, 'SAVING');
insert into saving_product value(130);
insert into product(id, name, corp_id, p_type) value(131, '우리 투게더 적금', 20, 'SAVING');
insert into saving_product value(131);
insert into product(id, name, corp_id, p_type) value(132, '3초 플레이 적금', 13, 'SAVING');
insert into saving_product value(132);
insert into product(id, name, corp_id, p_type) value(133, '텔레파시적금', 16, 'SAVING');
insert into saving_product value(133);
insert into product(id, name, corp_id, p_type) value(134, 'N일 적금(200일)', 20, 'SAVING');
insert into saving_product value(134);
insert into product(id, name, corp_id, p_type) value(135, 'N일 적금', 20, 'SAVING');
insert into saving_product value(135);
insert into product(id, name, corp_id, p_type) value(136, 'Sh어촌청년을 응원海', 11, 'SAVING');
insert into saving_product value(136);
insert into product(id, name, corp_id, p_type) value(137, 'IBK청년도약계좌', 9, 'SAVING');
insert into saving_product value(137);
insert into product(id, name, corp_id, p_type) value(138, 'KB청년도약계좌', 25, 'SAVING');
insert into saving_product value(138);
insert into product(id, name, corp_id, p_type) value(139, 'NH청년도약계좌', 10, 'SAVING');
insert into saving_product value(139);
insert into product(id, name, corp_id, p_type) value(140, '신한 청년도약계좌', 19, 'SAVING');
insert into saving_product value(140);
insert into product(id, name, corp_id, p_type) value(141, '우리 청년도약계좌', 20, 'SAVING');
insert into saving_product value(141);
insert into product(id, name, corp_id, p_type) value(142, '하나 청년도약계좌', 23, 'SAVING');
insert into saving_product value(142);
insert into product(id, name, corp_id, p_type) value(144, '신한투자증권 종합계좌', 27, 'CMA');
insert into cmaproduct value(144);