insert into corporation value (20, 'KB캐피탈', 'https://financial.pstatic.net/pie/common-bi/1.0.2/images/CAPITAL_KB_Profile.png')
insert into corporation value (21, 'KB국민카드', 'https://financial.pstatic.net/pie/common-bi/1.0.2/images/CD_KB_Profile.png')
insert into corporation value (22, 'BNK경남은행', 'https://financial.pstatic.net/pie/common-bi/1.0.2/images/BK_KYOUNGNAM_Profile.png')
insert into corporation value (23, '우리카드', 'https://financial.pstatic.net/pie/common-bi/1.0.2/images/CD_WOORI_Profile.png')
insert into corporation value (24, '신한카드', 'https://financial.pstatic.net/pie/common-bi/1.0.2/images/CD_SHINHAN_Profile.png')
insert into corporation value (25, '다올저축은행', 'https://financial.pstatic.net/pie/common-bi/1.0.2/images/SB_DAOL_Profile.png')
insert into corporation value (26, '예가람저축은행', 'https://financial.pstatic.net/pie/common-bi/1.0.2/images/SB_YEKARAM_Profile.png')
insert into corporation value (27, 'KB저축은행', 'https://financial.pstatic.net/pie/common-bi/1.0.2/images/SB_KB_Profile.png')
insert into corporation value (28, '신한저축은행', 'https://financial.pstatic.net/pie/common-bi/1.0.2/images/SB_SHINHAN_Profile.png')
insert into corporation value (29, '롯데캐피탈', 'https://financial.pstatic.net/pie/common-bi/1.0.2/images/CAPITAL_LOTTE_Profile.png')
insert into corporation value (30, '교보생명', 'https://financial.pstatic.net/pie/common-bi/1.0.2/images/IS_KYOBOLIFE_Profile.png')
insert into corporation value (31, 'SBI저축은행', 'https://financial.pstatic.net/pie/common-bi/1.0.2/images/SB_SBI2_Profile.png')
insert into corporation value (32, '상상인저축은행', 'https://financial.pstatic.net/pie/common-bi/1.0.2/images/SB_SSIN_Profile.png')
insert into corporation value (33, 'IBK저축은행', 'https://financial.pstatic.net/pie/common-bi/1.0.2/images/SB_IBK_Profile.png')
insert into corporation value (34, '융창저축은행', 'https://financial.pstatic.net/pie/common-bi/1.0.2/images/SB_YOONGCHANG_Profile.png')
insert into corporation value (35, 'BNK캐피탈', 'https://financial.pstatic.net/pie/common-bi/1.0.2/images/CAPITAL_BNK_Profile.png')
insert into corporation value (36, '하나저축은행', 'https://financial.pstatic.net/pie/common-bi/1.0.2/images/SB_HANA_Profile.png')
insert into corporation value (37, 'BNK저축은행', 'https://financial.pstatic.net/pie/common-bi/1.0.2/images/SB_BNK_Profile.png')
insert into corporation value (38, '웰컴저축은행', 'https://financial.pstatic.net/pie/common-bi/1.0.2/images/SB_WELCOME_Profile.png')
insert into corporation value (39, '미래에셋캐피탈', 'https://financial.pstatic.net/pie/common-bi/1.0.2/images/CAPITAL_MIRAE_Profile.png')
insert into corporation value (40, '스마트저축은행', 'https://financial.pstatic.net/pie/common-bi/1.0.2/images/SB_SMART_Profile.png')
insert into corporation value (41, 'JB우리캐피탈', 'https://financial.pstatic.net/pie/common-bi/1.0.2/images/CAPITAL_JB_WOORI_Profile.png')
insert into corporation value (42, '우리금융저축은행', 'https://financial.pstatic.net/pie/common-bi/1.0.2/images/SB_WOORIFIN_Profile.png')
insert into corporation value (43, '동원제일저축은행', 'https://financial.pstatic.net/pie/common-bi/1.0.2/images/SB_DONGWONJEIL_Profile.png')
insert into corporation value (44, 'DB저축은행', 'https://financial.pstatic.net/pie/common-bi/1.0.2/images/SB_DB_Profile.png')
insert into corporation value (45, '한국투자저축은행', 'https://financial.pstatic.net/pie/common-bi/1.0.2/images/SB_KOREAINVEST_Profile.png')
insert into corporation value (46, '우리금융캐피탈', 'https://financial.pstatic.net/pie/common-bi/1.0.2/images/CAPITAL_WOORIF_Profile.png')
insert into corporation value (47, '키움예스저축은행', 'https://financial.pstatic.net/pie/common-bi/1.0.2/images/SB_KIWOOMYES_Profile.png')
insert into corporation value (48, '한화저축은행', 'https://financial.pstatic.net/pie/common-bi/1.0.2/images/SB_HANWHA_Profile.png')
insert into corporation value (49, '키움저축은행', 'https://financial.pstatic.net/pie/common-bi/1.0.2/images/SB_KIWOOM_Profile.png')
insert into corporation value (50, 'OK저축은행', 'https://financial.pstatic.net/pie/common-bi/1.0.2/images/SB_OK_Profile.png')
insert into corporation value (51, '고려저축은행', 'https://financial.pstatic.net/pie/common-bi/1.0.2/images/SB_COREA_Profile.png')
insert into corporation value (52, '애큐온저축은행', 'https://financial.pstatic.net/pie/common-bi/1.0.2/images/SB_ACUON_Profile.png')
insert into corporation value (53, 'JT저축은행', 'https://financial.pstatic.net/pie/common-bi/1.0.2/images/SB_JT_Profile.png')
insert into corporation value (54, 'OSB저축은행', 'https://financial.pstatic.net/pie/common-bi/1.0.2/images/SB_OSB_Profile.png')
insert into corporation value (55, '모아저축은행', 'https://financial.pstatic.net/pie/common-bi/1.0.2/images/SB_MOA_Profile.png')
insert into product(id, name, corp_id, p_type) value(514, '내일로 신용대출', 20, 'LOAN')
insert into loan_product value(514)
insert into product(id, name, corp_id, p_type) value(515, '내집으로 신용대출', 20, 'LOAN')
insert into loan_product value(515)
insert into product(id, name, corp_id, p_type) value(516, '자동차 담보대출 내차로', 20, 'LOAN')
insert into loan_product value(516)
insert into product(id, name, corp_id, p_type) value(517, '소액론 신용대출', 20, 'LOAN')
insert into loan_product value(517)
insert into product(id, name, corp_id, p_type) value(518, '장기카드대출', 21, 'LOAN')
insert into loan_product value(518)
insert into product(id, name, corp_id, p_type) value(519, 'BNK모바일신용대출', 22, 'LOAN')
insert into loan_product value(519)
insert into product(id, name, corp_id, p_type) value(520, '올인원대출', 23, 'LOAN')
insert into loan_product value(520)
insert into product(id, name, corp_id, p_type) value(521, '신용대출', 14, 'LOAN')
insert into loan_product value(521)
insert into product(id, name, corp_id, p_type) value(522, '신용대출플러스', 14, 'LOAN')
insert into loan_product value(522)
insert into product(id, name, corp_id, p_type) value(523, '즉시대출', 24, 'LOAN')
insert into loan_product value(523)
insert into product(id, name, corp_id, p_type) value(524, '사업자금대출', 24, 'LOAN')
insert into loan_product value(524)
insert into product(id, name, corp_id, p_type) value(525, '장기카드대출', 24, 'LOAN')
insert into loan_product value(525)
insert into product(id, name, corp_id, p_type) value(526, '원스탑대환대출', 24, 'LOAN')
insert into loan_product value(526)
insert into product(id, name, corp_id, p_type) value(527, '모바일프라임론', 8, 'LOAN')
insert into loan_product value(527)
insert into product(id, name, corp_id, p_type) value(528, '사장님 신용대출', 14, 'LOAN')
insert into loan_product value(528)
insert into product(id, name, corp_id, p_type) value(529, 'JB 위풍당당 대출', 4, 'LOAN')
insert into loan_product value(529)
insert into product(id, name, corp_id, p_type) value(530, '돌려드림론', 9, 'LOAN')
insert into loan_product value(530)
insert into product(id, name, corp_id, p_type) value(531, 'KB국민 이지론플러스', 21, 'LOAN')
insert into loan_product value(531)
insert into product(id, name, corp_id, p_type) value(532, 'Fi신용대출', 25, 'LOAN')
insert into loan_product value(532)
insert into product(id, name, corp_id, p_type) value(533, '사장님대출', 18, 'LOAN')
insert into loan_product value(533)
insert into product(id, name, corp_id, p_type) value(534, '사장님마이너스통장', 18, 'LOAN')
insert into loan_product value(534)
insert into product(id, name, corp_id, p_type) value(535, '우리 Oh!(5)클릭 대출', 12, 'LOAN')
insert into loan_product value(535)
insert into product(id, name, corp_id, p_type) value(536, 'BNK모바일신용대출플러스', 22, 'LOAN')
insert into loan_product value(536)
insert into product(id, name, corp_id, p_type) value(537, 'JB 햇살론뱅크', 4, 'LOAN')
insert into loan_product value(537)
insert into product(id, name, corp_id, p_type) value(538, 'PRIME플러스론', 8, 'LOAN')
insert into loan_product value(538)
insert into product(id, name, corp_id, p_type) value(539, 'GPS론', 26, 'LOAN')
insert into loan_product value(539)
insert into product(id, name, corp_id, p_type) value(540, '빅머니M', 26, 'LOAN')
insert into loan_product value(540)
insert into product(id, name, corp_id, p_type) value(541, '빅머니U', 26, 'LOAN')
insert into loan_product value(541)
insert into product(id, name, corp_id, p_type) value(542, '예스론', 26, 'LOAN')
insert into loan_product value(542)
insert into product(id, name, corp_id, p_type) value(543, 'JB 탄탄대로 사업자대출', 4, 'LOAN')
insert into loan_product value(543)
insert into product(id, name, corp_id, p_type) value(544, 'kiwi신용대출', 27, 'LOAN')
insert into loan_product value(544)
insert into product(id, name, corp_id, p_type) value(545, 'kiwi마이홈신용대출', 27, 'LOAN')
insert into loan_product value(545)
insert into product(id, name, corp_id, p_type) value(546, 'kiwi전환대출', 27, 'LOAN')
insert into loan_product value(546)
insert into product(id, name, corp_id, p_type) value(547, '직장인중금리', 9, 'LOAN')
insert into loan_product value(547)
insert into product(id, name, corp_id, p_type) value(548, '참신한대출', 28, 'LOAN')
insert into loan_product value(548)
insert into product(id, name, corp_id, p_type) value(549, 'KB국민 개인사업자대출', 21, 'LOAN')
insert into loan_product value(549)
insert into product(id, name, corp_id, p_type) value(550, 'KJB햇살론뱅크', 8, 'LOAN')
insert into loan_product value(550)
insert into product(id, name, corp_id, p_type) value(551, '신용대출', 29, 'LOAN')
insert into loan_product value(551)
insert into product(id, name, corp_id, p_type) value(552, '사업자대출', 29, 'LOAN')
insert into loan_product value(552)
insert into product(id, name, corp_id, p_type) value(553, '교보e바로받는신용대출', 30, 'LOAN')
insert into loan_product value(553)
insert into product(id, name, corp_id, p_type) value(554, '신용대출', 31, 'LOAN')
insert into loan_product value(554)
insert into product(id, name, corp_id, p_type) value(555, '대환대출', 31, 'LOAN')
insert into loan_product value(555)
insert into product(id, name, corp_id, p_type) value(556, '오토론', 32, 'LOAN')
insert into loan_product value(556)
insert into product(id, name, corp_id, p_type) value(557, '온라인햇살론', 33, 'LOAN')
insert into loan_product value(557)
insert into product(id, name, corp_id, p_type) value(558, '온라인햇살론', 34, 'LOAN')
insert into loan_product value(558)
insert into product(id, name, corp_id, p_type) value(559, '근로자햇살론', 34, 'LOAN')
insert into loan_product value(559)
insert into product(id, name, corp_id, p_type) value(560, 'BNK신용대출', 35, 'LOAN')
insert into loan_product value(560)
insert into product(id, name, corp_id, p_type) value(561, 'BNK신용대출PLUS', 35, 'LOAN')
insert into loan_product value(561)
insert into product(id, name, corp_id, p_type) value(562, 'kiwi비상금대출', 27, 'LOAN')
insert into loan_product value(562)
insert into product(id, name, corp_id, p_type) value(563, 'kiwi여성비상금대출', 27, 'LOAN')
insert into loan_product value(563)
insert into product(id, name, corp_id, p_type) value(564, '사잇돌2', 31, 'LOAN')
insert into loan_product value(564)
insert into product(id, name, corp_id, p_type) value(565, '하나슈퍼드림론', 36, 'LOAN')
insert into loan_product value(565)
insert into product(id, name, corp_id, p_type) value(566, '사잇돌2', 36, 'LOAN')
insert into loan_product value(566)
insert into product(id, name, corp_id, p_type) value(567, '햇살론 ', 36, 'LOAN')
insert into loan_product value(567)
insert into product(id, name, corp_id, p_type) value(568, '햇살론', 37, 'LOAN')
insert into loan_product value(568)
insert into product(id, name, corp_id, p_type) value(569, '햇살론', 38, 'LOAN')
insert into loan_product value(569)
insert into product(id, name, corp_id, p_type) value(570, '햇살론2', 26, 'LOAN')
insert into loan_product value(570)
insert into product(id, name, corp_id, p_type) value(571, '온라인햇살론', 27, 'LOAN')
insert into loan_product value(571)
insert into product(id, name, corp_id, p_type) value(572, '햇살론/온라인햇살론', 28, 'LOAN')
insert into loan_product value(572)
insert into product(id, name, corp_id, p_type) value(573, '사잇돌2', 37, 'LOAN')
insert into loan_product value(573)
insert into product(id, name, corp_id, p_type) value(574, '사잇돌2대출', 28, 'LOAN')
insert into loan_product value(574)
insert into product(id, name, corp_id, p_type) value(575, '미래에셋캐피탈 신용대출', 39, 'LOAN')
insert into loan_product value(575)
insert into product(id, name, corp_id, p_type) value(576, '일반신용대출', 21, 'LOAN')
insert into loan_product value(576)
insert into product(id, name, corp_id, p_type) value(577, '직장인 신용대출', 40, 'LOAN')
insert into loan_product value(577)
insert into product(id, name, corp_id, p_type) value(578, '대환대출', 41, 'LOAN')
insert into loan_product value(578)
insert into product(id, name, corp_id, p_type) value(579, '비타WON [신용]', 42, 'LOAN')
insert into loan_product value(579)
insert into product(id, name, corp_id, p_type) value(580, '직장인 햇살론', 43, 'LOAN')
insert into loan_product value(580)
insert into product(id, name, corp_id, p_type) value(581, '마이론', 37, 'LOAN')
insert into loan_product value(581)
insert into product(id, name, corp_id, p_type) value(582, 'DreamBig 신용대출', 44, 'LOAN')
insert into loan_product value(582)
insert into product(id, name, corp_id, p_type) value(583, '살만한대출', 45, 'LOAN')
insert into loan_product value(583)
insert into product(id, name, corp_id, p_type) value(584, '네이버파이낸셜 연계 신용대출(자산론)', 46, 'LOAN')
insert into loan_product value(584)
insert into product(id, name, corp_id, p_type) value(585, '키움예스론H', 47, 'LOAN')
insert into loan_product value(585)
insert into product(id, name, corp_id, p_type) value(586, '직장인신용대출 오렌지론', 48, 'LOAN')
insert into loan_product value(586)
insert into product(id, name, corp_id, p_type) value(587, '키움예스론F', 47, 'LOAN')
insert into loan_product value(587)
insert into product(id, name, corp_id, p_type) value(588, '키움예스론', 47, 'LOAN')
insert into loan_product value(588)
insert into product(id, name, corp_id, p_type) value(589, '키움 신용대출', 49, 'LOAN')
insert into loan_product value(589)
insert into product(id, name, corp_id, p_type) value(590, 'OK한도우대론', 50, 'LOAN')
insert into loan_product value(590)
insert into product(id, name, corp_id, p_type) value(591, '주부OK론', 50, 'LOAN')
insert into loan_product value(591)
insert into product(id, name, corp_id, p_type) value(592, '사업자OK론', 50, 'LOAN')
insert into loan_product value(592)
insert into product(id, name, corp_id, p_type) value(593, '웰컴중금리대출', 38, 'LOAN')
insert into loan_product value(593)
insert into product(id, name, corp_id, p_type) value(594, '참신한500', 28, 'LOAN')
insert into loan_product value(594)
insert into product(id, name, corp_id, p_type) value(595, '뉴플랜론Ⅲ', 51, 'LOAN')
insert into loan_product value(595)
insert into product(id, name, corp_id, p_type) value(596, '사잇돌2대출', 27, 'LOAN')
insert into loan_product value(596)
insert into product(id, name, corp_id, p_type) value(597, '개인신용대출', 41, 'LOAN')
insert into loan_product value(597)
insert into product(id, name, corp_id, p_type) value(598, '자동차담보대출', 41, 'LOAN')
insert into loan_product value(598)
insert into product(id, name, corp_id, p_type) value(599, 'i-빅론U', 33, 'LOAN')
insert into loan_product value(599)
insert into product(id, name, corp_id, p_type) value(600, '네이버파이낸셜 연계 신용대출(직장인론)', 46, 'LOAN')
insert into loan_product value(600)
insert into product(id, name, corp_id, p_type) value(601, '웰컴중금리대출', 38, 'LOAN')
insert into loan_product value(601)
insert into product(id, name, corp_id, p_type) value(602, '개인신용대출', 50, 'LOAN')
insert into loan_product value(602)
insert into product(id, name, corp_id, p_type) value(603, '애큐온프라임론', 52, 'LOAN')
insert into loan_product value(603)
insert into product(id, name, corp_id, p_type) value(604, '파라솔 신용대출(모바일 자동대출)', 53, 'LOAN')
insert into loan_product value(604)
insert into product(id, name, corp_id, p_type) value(605, '라이브M', 26, 'LOAN')
insert into loan_product value(605)
insert into product(id, name, corp_id, p_type) value(606, '라이브U', 26, 'LOAN')
insert into loan_product value(606)
insert into product(id, name, corp_id, p_type) value(607, '직장인 신용대출(오리치론)', 54, 'LOAN')
insert into loan_product value(607)
insert into product(id, name, corp_id, p_type) value(608, '소액신용대출(오예스론)', 54, 'LOAN')
insert into loan_product value(608)
insert into product(id, name, corp_id, p_type) value(609, '믿을론(다이렉트)', 55, 'LOAN')
insert into loan_product value(609)
