insert into product(id, name, corp_id, p_type) value(1, 'Sh첫만남우대예금', 1, 'DEPOSIT');
insert into deposit_product value(1);
insert into product(id, name, corp_id, p_type) value(2, 'NH고향사랑기부예금', 2, 'DEPOSIT');
insert into deposit_product value(2);
insert into product(id, name, corp_id, p_type) value(3, 'DGB주거래우대예금(첫만남고객형)', 3, 'DEPOSIT');
insert into deposit_product value(3);
insert into product(id, name, corp_id, p_type) value(4, 'JB 최강전북 축구사랑 예금', 4, 'DEPOSIT');
insert into deposit_product value(4);
insert into product(id, name, corp_id, p_type) value(5, 'The 든든 예금', 5, 'DEPOSIT');
insert into deposit_product value(5);
insert into product(id, name, corp_id, p_type) value(6, 'BNK코리보연동정기예금', 5, 'DEPOSIT');
insert into deposit_product value(6);
insert into product(id, name, corp_id, p_type) value(7, 'DGB함께예금', 3, 'DEPOSIT');
insert into deposit_product value(7);
insert into product(id, name, corp_id, p_type) value(8, 'J 정기예금', 6, 'DEPOSIT');
insert into deposit_product value(8);
insert into product(id, name, corp_id, p_type) value(9, 'IBK D-Day통장(단기중금채)', 7, 'DEPOSIT');
insert into deposit_product value(9);
insert into product(id, name, corp_id, p_type) value(10, 'IBK평생한가족통장[중금채]', 7, 'DEPOSIT');
insert into deposit_product value(10);
insert into product(id, name, corp_id, p_type) value(11, 'Sh해양플라스틱Zero!예금', 1, 'DEPOSIT');
insert into deposit_product value(11);
insert into product(id, name, corp_id, p_type) value(12, '직장인우대예금', 3, 'DEPOSIT');
insert into deposit_product value(12);
insert into product(id, name, corp_id, p_type) value(13, 'KIA타이거즈 우승기원 예금', 8, 'DEPOSIT');
insert into deposit_product value(13);
insert into product(id, name, corp_id, p_type) value(14, 'BNK주거래우대정기예금', 5, 'DEPOSIT');
insert into deposit_product value(14);
insert into product(id, name, corp_id, p_type) value(15, 'JB 1·2·3 정기예금', 4, 'DEPOSIT');
insert into deposit_product value(15);
insert into product(id, name, corp_id, p_type) value(16, 'e-그린세이브예금', 9, 'DEPOSIT');
insert into deposit_product value(16);
insert into product(id, name, corp_id, p_type) value(17, '스마일드림정기예금', 6, 'DEPOSIT');
insert into deposit_product value(17);
insert into product(id, name, corp_id, p_type) value(18, '굿스타트예금', 8, 'DEPOSIT');
insert into deposit_product value(18);
insert into product(id, name, corp_id, p_type) value(19, '더(The) 특판 정기예금', 10, 'DEPOSIT');
insert into deposit_product value(19);
insert into product(id, name, corp_id, p_type) value(20, 'IBK평생한가족통장[정기예금]', 7, 'DEPOSIT');
insert into deposit_product value(20);
insert into product(id, name, corp_id, p_type) value(21, 'IM스마트예금', 3, 'DEPOSIT');
insert into deposit_product value(21);
insert into product(id, name, corp_id, p_type) value(22, 'DGB주거래우대예금(단골고객형)', 3, 'DEPOSIT');
insert into deposit_product value(22);
insert into product(id, name, corp_id, p_type) value(23, 'JB Smart-App 예금', 4, 'DEPOSIT');
insert into deposit_product value(23);
insert into product(id, name, corp_id, p_type) value(24, '신한 My플러스 정기예금', 11, 'DEPOSIT');
insert into deposit_product value(24);
insert into product(id, name, corp_id, p_type) value(25, 'Tops CD연동 정기예금', 11, 'DEPOSIT');
insert into deposit_product value(25);
insert into product(id, name, corp_id, p_type) value(26, '우리 첫거래우대 정기예금', 12, 'DEPOSIT');
insert into deposit_product value(26);
insert into product(id, name, corp_id, p_type) value(27, '1석7조통장(중금채)', 7, 'DEPOSIT');
insert into deposit_product value(27);
insert into product(id, name, corp_id, p_type) value(28, 'NH올원e예금', 2, 'DEPOSIT');
insert into deposit_product value(28);
insert into product(id, name, corp_id, p_type) value(29, 'NH왈츠회전예금II', 2, 'DEPOSIT');
insert into deposit_product value(29);
insert into product(id, name, corp_id, p_type) value(30, '(The 고마워요 5월) 특판 예금', 4, 'DEPOSIT');
insert into deposit_product value(30);
insert into product(id, name, corp_id, p_type) value(31, 'BNK MY 원 픽 정기예금', 5, 'DEPOSIT');
insert into deposit_product value(31);
insert into product(id, name, corp_id, p_type) value(32, 'WON플러스 예금', 12, 'DEPOSIT');
insert into deposit_product value(32);
insert into product(id, name, corp_id, p_type) value(33, 'JB 주거래 예금', 4, 'DEPOSIT');
insert into deposit_product value(33);
insert into product(id, name, corp_id, p_type) value(34, '행운박스예금', 8, 'DEPOSIT');
insert into deposit_product value(34);
insert into product(id, name, corp_id, p_type) value(35, 'KDB 정기예금', 13, 'DEPOSIT');
insert into deposit_product value(35);
insert into product(id, name, corp_id, p_type) value(36, '코드K 정기예금', 14, 'DEPOSIT');
insert into deposit_product value(36);
insert into product(id, name, corp_id, p_type) value(37, 'NH내가Green초록세상예금', 2, 'DEPOSIT');
insert into deposit_product value(37);
insert into product(id, name, corp_id, p_type) value(38, '쏠편한 정기예금', 11, 'DEPOSIT');
insert into deposit_product value(38);
insert into product(id, name, corp_id, p_type) value(39, '하나의 정기예금', 15, 'DEPOSIT');
insert into deposit_product value(39);
insert into product(id, name, corp_id, p_type) value(40, '스마트모아Dream정기예금', 8, 'DEPOSIT');
insert into deposit_product value(40);
insert into product(id, name, corp_id, p_type) value(41, 'JB다이렉트예금', 4, 'DEPOSIT');
insert into deposit_product value(41);
insert into product(id, name, corp_id, p_type) value(42, 'The플러스예금', 8, 'DEPOSIT');
insert into deposit_product value(42);
insert into product(id, name, corp_id, p_type) value(43, 'BNK더조은정기예금', 5, 'DEPOSIT');
insert into deposit_product value(43);
insert into product(id, name, corp_id, p_type) value(44, 'JB 골든 에이지 예금', 4, 'DEPOSIT');
insert into deposit_product value(44);
insert into product(id, name, corp_id, p_type) value(45, '친환경녹색예금', 3, 'DEPOSIT');
insert into deposit_product value(45);
insert into product(id, name, corp_id, p_type) value(46, 'LIVE정기예금', 10, 'DEPOSIT');
insert into deposit_product value(46);
insert into product(id, name, corp_id, p_type) value(47, 'DGB행복파트너예금(연금형)', 3, 'DEPOSIT');
insert into deposit_product value(47);
insert into product(id, name, corp_id, p_type) value(48, '자유만기회전예금', 3, 'DEPOSIT');
insert into deposit_product value(48);
insert into product(id, name, corp_id, p_type) value(49, 'SC제일 친환경비움예금', 9, 'DEPOSIT');
insert into deposit_product value(49);
insert into product(id, name, corp_id, p_type) value(50, '중도해지 괜찮Wa예금', 8, 'DEPOSIT');
insert into deposit_product value(50);
insert into product(id, name, corp_id, p_type) value(51, '큰만족실세예금', 2, 'DEPOSIT');
insert into deposit_product value(51);
insert into product(id, name, corp_id, p_type) value(52, '1석7조통장(정기예금)', 7, 'DEPOSIT');
insert into deposit_product value(52);
insert into product(id, name, corp_id, p_type) value(53, '카카오뱅크 정기예금', 16, 'DEPOSIT');
insert into deposit_product value(53);
insert into product(id, name, corp_id, p_type) value(54, '플러스다모아예금', 8, 'DEPOSIT');
insert into deposit_product value(54);
insert into product(id, name, corp_id, p_type) value(55, '이자먼저Wa예금', 8, 'DEPOSIT');
insert into deposit_product value(55);
insert into product(id, name, corp_id, p_type) value(56, 'IBK혁신창업기업응원통장[실세금리정기예금]', 7, 'DEPOSIT');
insert into deposit_product value(56);
insert into product(id, name, corp_id, p_type) value(57, '스마트 정기예금', 4, 'DEPOSIT');
insert into deposit_product value(57);
insert into product(id, name, corp_id, p_type) value(58, '자유적립식예금', 3, 'DEPOSIT');
insert into deposit_product value(58);
insert into product(id, name, corp_id, p_type) value(59, '마니마니정기예금', 5, 'DEPOSIT');
insert into deposit_product value(59);
insert into product(id, name, corp_id, p_type) value(60, 'IBK혁신창업기업응원통장[중소기업금융채권]', 7, 'DEPOSIT');
insert into deposit_product value(60);
insert into product(id, name, corp_id, p_type) value(61, '독도사랑예금', 1, 'DEPOSIT');
insert into deposit_product value(61);
insert into product(id, name, corp_id, p_type) value(62, '사랑해정기예금(실세금리정기예금)', 1, 'DEPOSIT');
insert into deposit_product value(62);
insert into product(id, name, corp_id, p_type) value(63, '실세금리정기예금', 7, 'DEPOSIT');
insert into deposit_product value(63);
insert into product(id, name, corp_id, p_type) value(64, '어촌복지예금 (거치식예금)', 1, 'DEPOSIT');
insert into deposit_product value(64);
insert into product(id, name, corp_id, p_type) value(65, '제주DREAM 정기예금', 6, 'DEPOSIT');
insert into deposit_product value(65);
insert into product(id, name, corp_id, p_type) value(66, 'NH더하고나눔정기예금', 2, 'DEPOSIT');
insert into deposit_product value(66);
insert into product(id, name, corp_id, p_type) value(67, '국민수퍼정기예금(CD금리연동형)', 17, 'DEPOSIT');
insert into deposit_product value(67);
insert into product(id, name, corp_id, p_type) value(68, '미래설계 장기플랜 연금예금', 11, 'DEPOSIT');
insert into deposit_product value(68);
insert into product(id, name, corp_id, p_type) value(69, '미래설계 크레바스 연금예금', 11, 'DEPOSIT');
insert into deposit_product value(69);
insert into product(id, name, corp_id, p_type) value(70, '플러스정기예금', 3, 'DEPOSIT');
insert into deposit_product value(70);
insert into product(id, name, corp_id, p_type) value(71, 'BNK내맘대로 예금', 10, 'DEPOSIT');
insert into deposit_product value(71);
insert into product(id, name, corp_id, p_type) value(72, 'KB국민UP정기예금', 17, 'DEPOSIT');
insert into deposit_product value(72);
insert into product(id, name, corp_id, p_type) value(73, '정기예금', 7, 'DEPOSIT');
insert into deposit_product value(73);
insert into product(id, name, corp_id, p_type) value(74, '토스뱅크 먼저 이자 받는 정기예금', 18, 'DEPOSIT');
insert into deposit_product value(74);
insert into product(id, name, corp_id, p_type) value(75, '3·6·9 정기예금', 15, 'DEPOSIT');
insert into deposit_product value(75);
insert into product(id, name, corp_id, p_type) value(76, '우리 SUPER 정기예금', 12, 'DEPOSIT');
insert into deposit_product value(76);
insert into product(id, name, corp_id, p_type) value(77, '맞춤형 자유만기 정기예금', 4, 'DEPOSIT');
insert into deposit_product value(77);
insert into product(id, name, corp_id, p_type) value(78, 'IBK회전정기예금', 7, 'DEPOSIT');
insert into deposit_product value(78);
insert into product(id, name, corp_id, p_type) value(79, '장기회전정기예금', 10, 'DEPOSIT');
insert into deposit_product value(79);
insert into product(id, name, corp_id, p_type) value(80, '정기예금', 2, 'DEPOSIT');
insert into deposit_product value(80);
insert into product(id, name, corp_id, p_type) value(81, '정기예금', 6, 'DEPOSIT');
insert into deposit_product value(81);
insert into product(id, name, corp_id, p_type) value(82, 'JB FUN 세이브 통장', 4, 'DEPOSIT');
insert into deposit_product value(82);
insert into product(id, name, corp_id, p_type) value(83, 'JB회전정기예금', 4, 'DEPOSIT');
insert into deposit_product value(83);
insert into product(id, name, corp_id, p_type) value(84, '시장금리부 정기예금', 4, 'DEPOSIT');
insert into deposit_product value(84);
insert into product(id, name, corp_id, p_type) value(85, '신한 S드림(DREAM) 정기예금', 11, 'DEPOSIT');
insert into deposit_product value(85);
insert into product(id, name, corp_id, p_type) value(86, '사랑해나누리예금', 1, 'DEPOSIT');
insert into deposit_product value(86);
insert into product(id, name, corp_id, p_type) value(87, '퍼스트정기예금', 9, 'DEPOSIT');
insert into deposit_product value(87);
insert into product(id, name, corp_id, p_type) value(88, 'JB 참 괜찮은 정기예금', 4, 'DEPOSIT');
insert into deposit_product value(88);
insert into product(id, name, corp_id, p_type) value(89, 'Tops 회전 정기예금', 11, 'DEPOSIT');
insert into deposit_product value(89);
insert into product(id, name, corp_id, p_type) value(90, '정기예금', 4, 'DEPOSIT');
insert into deposit_product value(90);
insert into product(id, name, corp_id, p_type) value(91, '럭키한 쿠폰 예금', 4, 'DEPOSIT');
insert into deposit_product value(91);
insert into product(id, name, corp_id, p_type) value(92, '퍼스트정기예금(회전식)', 9, 'DEPOSIT');
insert into deposit_product value(92);
insert into product(id, name, corp_id, p_type) value(93, '국민수퍼정기예금(개인)', 17, 'DEPOSIT');
insert into deposit_product value(93);
insert into product(id, name, corp_id, p_type) value(94, 'Sh평생주거래우대예금', 1, 'DEPOSIT');
insert into deposit_product value(94);
insert into product(id, name, corp_id, p_type) value(95, '메리트정기예금', 10, 'DEPOSIT');
insert into deposit_product value(95);
insert into product(id, name, corp_id, p_type) value(96, '일반 정기예금', 13, 'DEPOSIT');
insert into deposit_product value(96);
insert into product(id, name, corp_id, p_type) value(97, '일반정기예금', 8, 'DEPOSIT');
insert into deposit_product value(97);
insert into product(id, name, corp_id, p_type) value(98, '정기예금', 11, 'DEPOSIT');
insert into deposit_product value(98);
insert into product(id, name, corp_id, p_type) value(99, '정기예금', 12, 'DEPOSIT');
insert into deposit_product value(99);
insert into product(id, name, corp_id, p_type) value(100, '고단위 플러스(금리연동형)', 15, 'DEPOSIT');
insert into deposit_product value(100);
insert into product(id, name, corp_id, p_type) value(101, '고단위 플러스(금리확정형)', 15, 'DEPOSIT');
insert into deposit_product value(101);
insert into product(id, name, corp_id, p_type) value(102, '정기예금', 15, 'DEPOSIT');
insert into deposit_product value(102);
insert into product(id, name, corp_id, p_type) value(103, '일반정기예금', 17, 'DEPOSIT');
insert into deposit_product value(103);
insert into product(id, name, corp_id, p_type) value(104, '장기회전정기예금', 5, 'DEPOSIT');
insert into deposit_product value(104);
insert into product(id, name, corp_id, p_type) value(105, '정기예금', 5, 'DEPOSIT');
insert into deposit_product value(105);
insert into product(id, name, corp_id, p_type) value(106, '회전플러스정기예금', 10, 'DEPOSIT');
insert into deposit_product value(106);
insert into product(id, name, corp_id, p_type) value(107, '일반정기예금', 1, 'DEPOSIT');
insert into deposit_product value(107);
insert into product(id, name, corp_id, p_type) value(108, '두루두루정기예금', 12, 'DEPOSIT');
insert into deposit_product value(108);
insert into product(id, name, corp_id, p_type) value(109, 'JB슈퍼씨드 적금', 4, 'SAVING');
insert into saving_product value(109);
insert into product(id, name, corp_id, p_type) value(110, '데일리 워킹 적금', 12, 'SAVING');
insert into saving_product value(110);
insert into product(id, name, corp_id, p_type) value(111, 'NH 상생+아이행복적금', 2, 'SAVING');
insert into saving_product value(111);
insert into product(id, name, corp_id, p_type) value(112, '우리 사장님 활짝 핀 적금', 12, 'SAVING');
insert into saving_product value(112);
insert into product(id, name, corp_id, p_type) value(113, '온국민 건강적금-골든라이프', 17, 'SAVING');
insert into saving_product value(113);
insert into product(id, name, corp_id, p_type) value(114, '주거래기업부금(정액적립식)', 7, 'SAVING');
insert into saving_product value(114);
insert into product(id, name, corp_id, p_type) value(115, 'BNK아기천사적금', 10, 'SAVING');
insert into saving_product value(115);
insert into product(id, name, corp_id, p_type) value(116, '터치 적금', 5, 'SAVING');
insert into saving_product value(116);
insert into product(id, name, corp_id, p_type) value(117, 'KB차차차 적금', 17, 'SAVING');
insert into saving_product value(117);
insert into product(id, name, corp_id, p_type) value(118, '하나 아이키움 적금', 15, 'SAVING');
insert into saving_product value(118);
insert into product(id, name, corp_id, p_type) value(119, '온국민 건강적금', 17, 'SAVING');
insert into saving_product value(119);
insert into product(id, name, corp_id, p_type) value(120, 'IBK장병내일준비적금', 7, 'SAVING');
insert into saving_product value(120);
insert into product(id, name, corp_id, p_type) value(121, '우리페이 적금', 12, 'SAVING');
insert into saving_product value(121);
insert into product(id, name, corp_id, p_type) value(122, 'KB장병내일준비적금', 17, 'SAVING');
insert into saving_product value(122);
insert into product(id, name, corp_id, p_type) value(123, 'IBK탄소제로적금', 7, 'SAVING');
insert into saving_product value(123);
insert into product(id, name, corp_id, p_type) value(124, '카카오뱅크 한달적금', 16, 'SAVING');
insert into saving_product value(124);
insert into product(id, name, corp_id, p_type) value(125, '새희망적금', 8, 'SAVING');
insert into saving_product value(125);
insert into product(id, name, corp_id, p_type) value(126, 'NH1418스윙적금', 2, 'SAVING');
insert into saving_product value(126);
insert into product(id, name, corp_id, p_type) value(127, '청년 처음적금', 11, 'SAVING');
insert into saving_product value(127);
insert into product(id, name, corp_id, p_type) value(128, '데일리 워킹 적금', 12, 'SAVING');
insert into saving_product value(128);
insert into product(id, name, corp_id, p_type) value(129, 'NH 상생+아이행복적금', 2, 'SAVING');
insert into saving_product value(129);
insert into product(id, name, corp_id, p_type) value(130, '우리 사장님 활짝 핀 적금', 12, 'SAVING');
insert into saving_product value(130);
insert into product(id, name, corp_id, p_type) value(131, '온국민 건강적금-골든라이프', 17, 'SAVING');
insert into saving_product value(131);
insert into product(id, name, corp_id, p_type) value(132, '주거래기업부금(정액적립식)', 7, 'SAVING');
insert into saving_product value(132);
insert into product(id, name, corp_id, p_type) value(133, 'BNK아기천사적금', 10, 'SAVING');
insert into saving_product value(133);
insert into product(id, name, corp_id, p_type) value(134, '터치 적금', 5, 'SAVING');
insert into saving_product value(134);
insert into product(id, name, corp_id, p_type) value(135, 'KB차차차 적금', 17, 'SAVING');
insert into saving_product value(135);
insert into product(id, name, corp_id, p_type) value(136, '하나 아이키움 적금', 15, 'SAVING');
insert into saving_product value(136);
insert into product(id, name, corp_id, p_type) value(137, '온국민 건강적금', 17, 'SAVING');
insert into saving_product value(137);
insert into product(id, name, corp_id, p_type) value(138, 'IBK장병내일준비적금', 7, 'SAVING');
insert into saving_product value(138);
insert into product(id, name, corp_id, p_type) value(139, '우리페이 적금', 12, 'SAVING');
insert into saving_product value(139);
insert into product(id, name, corp_id, p_type) value(140, 'KB장병내일준비적금', 17, 'SAVING');
insert into saving_product value(140);
insert into product(id, name, corp_id, p_type) value(141, 'IBK탄소제로적금', 7, 'SAVING');
insert into saving_product value(141);
insert into product(id, name, corp_id, p_type) value(142, '카카오뱅크 한달적금', 16, 'SAVING');
insert into saving_product value(142);
insert into product(id, name, corp_id, p_type) value(143, '새희망적금', 8, 'SAVING');
insert into saving_product value(143);
insert into product(id, name, corp_id, p_type) value(144, 'NH1418스윙적금', 2, 'SAVING');
insert into saving_product value(144);
insert into product(id, name, corp_id, p_type) value(145, '청년 처음적금', 11, 'SAVING');
insert into saving_product value(145);
insert into product(id, name, corp_id, p_type) value(146, 'IBK부모급여우대적금', 7, 'SAVING');
insert into saving_product value(146);
insert into product(id, name, corp_id, p_type) value(147, 'NH 상생+아이행복적금', 2, 'SAVING');
insert into saving_product value(147);
insert into product(id, name, corp_id, p_type) value(148, '우리 사장님 활짝 핀 적금', 12, 'SAVING');
insert into saving_product value(148);
insert into product(id, name, corp_id, p_type) value(149, '온국민 건강적금-골든라이프', 17, 'SAVING');
insert into saving_product value(149);
insert into product(id, name, corp_id, p_type) value(150, '주거래기업부금(정액적립식)', 7, 'SAVING');
insert into saving_product value(150);
insert into product(id, name, corp_id, p_type) value(151, 'BNK아기천사적금', 10, 'SAVING');
insert into saving_product value(151);
insert into product(id, name, corp_id, p_type) value(152, '터치 적금', 5, 'SAVING');
insert into saving_product value(152);
insert into product(id, name, corp_id, p_type) value(153, 'KB차차차 적금', 17, 'SAVING');
insert into saving_product value(153);
insert into product(id, name, corp_id, p_type) value(154, '하나 아이키움 적금', 15, 'SAVING');
insert into saving_product value(154);
insert into product(id, name, corp_id, p_type) value(155, '온국민 건강적금', 17, 'SAVING');
insert into saving_product value(155);
insert into product(id, name, corp_id, p_type) value(156, 'IBK장병내일준비적금', 7, 'SAVING');
insert into saving_product value(156);
insert into product(id, name, corp_id, p_type) value(157, '우리페이 적금', 12, 'SAVING');
insert into saving_product value(157);
insert into product(id, name, corp_id, p_type) value(158, 'KB장병내일준비적금', 17, 'SAVING');
insert into saving_product value(158);
insert into product(id, name, corp_id, p_type) value(159, 'IBK탄소제로적금', 7, 'SAVING');
insert into saving_product value(159);
insert into product(id, name, corp_id, p_type) value(160, '카카오뱅크 한달적금', 16, 'SAVING');
insert into saving_product value(160);
insert into product(id, name, corp_id, p_type) value(161, '새희망적금', 8, 'SAVING');
insert into saving_product value(161);
insert into product(id, name, corp_id, p_type) value(162, 'NH1418스윙적금', 2, 'SAVING');
insert into saving_product value(162);
insert into product(id, name, corp_id, p_type) value(163, '청년 처음적금', 11, 'SAVING');
insert into saving_product value(163);
insert into product(id, name, corp_id, p_type) value(164, 'IBK부모급여우대적금', 7, 'SAVING');
insert into saving_product value(164);
insert into product(id, name, corp_id, p_type) value(165, 'BNK 위더스(With-Us) 자유적금', 5, 'SAVING');
insert into saving_product value(165);
insert into product(id, name, corp_id, p_type) value(166, '우리 사장님 활짝 핀 적금', 12, 'SAVING');
insert into saving_product value(166);
insert into product(id, name, corp_id, p_type) value(167, '온국민 건강적금-골든라이프', 17, 'SAVING');
insert into saving_product value(167);
insert into product(id, name, corp_id, p_type) value(168, '주거래기업부금(정액적립식)', 7, 'SAVING');
insert into saving_product value(168);
insert into product(id, name, corp_id, p_type) value(169, 'BNK아기천사적금', 10, 'SAVING');
insert into saving_product value(169);
insert into product(id, name, corp_id, p_type) value(170, '터치 적금', 5, 'SAVING');
insert into saving_product value(170);
insert into product(id, name, corp_id, p_type) value(171, 'KB차차차 적금', 17, 'SAVING');
insert into saving_product value(171);
insert into product(id, name, corp_id, p_type) value(172, '하나 아이키움 적금', 15, 'SAVING');
insert into saving_product value(172);
insert into product(id, name, corp_id, p_type) value(173, '온국민 건강적금', 17, 'SAVING');
insert into saving_product value(173);
insert into product(id, name, corp_id, p_type) value(174, 'IBK장병내일준비적금', 7, 'SAVING');
insert into saving_product value(174);
insert into product(id, name, corp_id, p_type) value(175, '우리페이 적금', 12, 'SAVING');
insert into saving_product value(175);
insert into product(id, name, corp_id, p_type) value(176, 'KB장병내일준비적금', 17, 'SAVING');
insert into saving_product value(176);
insert into product(id, name, corp_id, p_type) value(177, 'IBK탄소제로적금', 7, 'SAVING');
insert into saving_product value(177);
insert into product(id, name, corp_id, p_type) value(178, '카카오뱅크 한달적금', 16, 'SAVING');
insert into saving_product value(178);
insert into product(id, name, corp_id, p_type) value(179, '새희망적금', 8, 'SAVING');
insert into saving_product value(179);
insert into product(id, name, corp_id, p_type) value(180, 'NH1418스윙적금', 2, 'SAVING');
insert into saving_product value(180);
insert into product(id, name, corp_id, p_type) value(181, '청년 처음적금', 11, 'SAVING');
insert into saving_product value(181);
insert into product(id, name, corp_id, p_type) value(182, 'IBK부모급여우대적금', 7, 'SAVING');
insert into saving_product value(182);
insert into product(id, name, corp_id, p_type) value(183, 'BNK 위더스(With-Us) 자유적금', 5, 'SAVING');
insert into saving_product value(183);
insert into product(id, name, corp_id, p_type) value(184, '원비즈플라자 멤버십 적금', 12, 'SAVING');
insert into saving_product value(184);
insert into product(id, name, corp_id, p_type) value(185, '온국민 건강적금-골든라이프', 17, 'SAVING');
insert into saving_product value(185);
insert into product(id, name, corp_id, p_type) value(186, '주거래기업부금(정액적립식)', 7, 'SAVING');
insert into saving_product value(186);
insert into product(id, name, corp_id, p_type) value(187, 'BNK아기천사적금', 10, 'SAVING');
insert into saving_product value(187);
insert into product(id, name, corp_id, p_type) value(188, '터치 적금', 5, 'SAVING');
insert into saving_product value(188);
insert into product(id, name, corp_id, p_type) value(189, 'KB차차차 적금', 17, 'SAVING');
insert into saving_product value(189);
insert into product(id, name, corp_id, p_type) value(190, '하나 아이키움 적금', 15, 'SAVING');
insert into saving_product value(190);
insert into product(id, name, corp_id, p_type) value(191, '온국민 건강적금', 17, 'SAVING');
insert into saving_product value(191);
insert into product(id, name, corp_id, p_type) value(192, 'IBK장병내일준비적금', 7, 'SAVING');
insert into saving_product value(192);
insert into product(id, name, corp_id, p_type) value(193, '우리페이 적금', 12, 'SAVING');
insert into saving_product value(193);
insert into product(id, name, corp_id, p_type) value(194, 'KB장병내일준비적금', 17, 'SAVING');
insert into saving_product value(194);
insert into product(id, name, corp_id, p_type) value(195, 'IBK탄소제로적금', 7, 'SAVING');
insert into saving_product value(195);
insert into product(id, name, corp_id, p_type) value(196, '카카오뱅크 한달적금', 16, 'SAVING');
insert into saving_product value(196);
insert into product(id, name, corp_id, p_type) value(197, '새희망적금', 8, 'SAVING');
insert into saving_product value(197);
insert into product(id, name, corp_id, p_type) value(198, 'NH1418스윙적금', 2, 'SAVING');
insert into saving_product value(198);
insert into product(id, name, corp_id, p_type) value(199, '청년 처음적금', 11, 'SAVING');
insert into saving_product value(199);
insert into product(id, name, corp_id, p_type) value(200, 'IBK부모급여우대적금', 7, 'SAVING');
insert into saving_product value(200);
insert into product(id, name, corp_id, p_type) value(201, 'BNK 위더스(With-Us) 자유적금', 5, 'SAVING');
insert into saving_product value(201);
insert into product(id, name, corp_id, p_type) value(202, '원비즈플라자 멤버십 적금', 12, 'SAVING');
insert into saving_product value(202);
insert into product(id, name, corp_id, p_type) value(203, '우리 투게더 적금', 12, 'SAVING');
insert into saving_product value(203);
insert into product(id, name, corp_id, p_type) value(204, '주거래기업부금(정액적립식)', 7, 'SAVING');
insert into saving_product value(204);
insert into product(id, name, corp_id, p_type) value(205, 'BNK아기천사적금', 10, 'SAVING');
insert into saving_product value(205);
insert into product(id, name, corp_id, p_type) value(206, '터치 적금', 5, 'SAVING');
insert into saving_product value(206);
insert into product(id, name, corp_id, p_type) value(207, 'KB차차차 적금', 17, 'SAVING');
insert into saving_product value(207);
insert into product(id, name, corp_id, p_type) value(208, '하나 아이키움 적금', 15, 'SAVING');
insert into saving_product value(208);
insert into product(id, name, corp_id, p_type) value(209, '온국민 건강적금', 17, 'SAVING');
insert into saving_product value(209);
insert into product(id, name, corp_id, p_type) value(210, 'IBK장병내일준비적금', 7, 'SAVING');
insert into saving_product value(210);
insert into product(id, name, corp_id, p_type) value(211, '우리페이 적금', 12, 'SAVING');
insert into saving_product value(211);
insert into product(id, name, corp_id, p_type) value(212, 'KB장병내일준비적금', 17, 'SAVING');
insert into saving_product value(212);
insert into product(id, name, corp_id, p_type) value(213, 'IBK탄소제로적금', 7, 'SAVING');
insert into saving_product value(213);
insert into product(id, name, corp_id, p_type) value(214, '카카오뱅크 한달적금', 16, 'SAVING');
insert into saving_product value(214);
insert into product(id, name, corp_id, p_type) value(215, '새희망적금', 8, 'SAVING');
insert into saving_product value(215);
insert into product(id, name, corp_id, p_type) value(216, 'NH1418스윙적금', 2, 'SAVING');
insert into saving_product value(216);
insert into product(id, name, corp_id, p_type) value(217, '청년 처음적금', 11, 'SAVING');
insert into saving_product value(217);
insert into product(id, name, corp_id, p_type) value(218, 'IBK부모급여우대적금', 7, 'SAVING');
insert into saving_product value(218);
insert into product(id, name, corp_id, p_type) value(219, 'BNK 위더스(With-Us) 자유적금', 5, 'SAVING');
insert into saving_product value(219);
insert into product(id, name, corp_id, p_type) value(220, '원비즈플라자 멤버십 적금', 12, 'SAVING');
insert into saving_product value(220);
insert into product(id, name, corp_id, p_type) value(221, '우리 투게더 적금', 12, 'SAVING');
insert into saving_product value(221);
insert into product(id, name, corp_id, p_type) value(222, '3초 플레이 적금', 4, 'SAVING');
insert into saving_product value(222);
insert into product(id, name, corp_id, p_type) value(223, 'BNK아기천사적금', 10, 'SAVING');
insert into saving_product value(223);
insert into product(id, name, corp_id, p_type) value(224, '터치 적금', 5, 'SAVING');
insert into saving_product value(224);
insert into product(id, name, corp_id, p_type) value(225, 'KB차차차 적금', 17, 'SAVING');
insert into saving_product value(225);
insert into product(id, name, corp_id, p_type) value(226, '하나 아이키움 적금', 15, 'SAVING');
insert into saving_product value(226);
insert into product(id, name, corp_id, p_type) value(227, '온국민 건강적금', 17, 'SAVING');
insert into saving_product value(227);
insert into product(id, name, corp_id, p_type) value(228, 'IBK장병내일준비적금', 7, 'SAVING');
insert into saving_product value(228);
insert into product(id, name, corp_id, p_type) value(229, '우리페이 적금', 12, 'SAVING');
insert into saving_product value(229);
insert into product(id, name, corp_id, p_type) value(230, 'KB장병내일준비적금', 17, 'SAVING');
insert into saving_product value(230);
insert into product(id, name, corp_id, p_type) value(231, 'IBK탄소제로적금', 7, 'SAVING');
insert into saving_product value(231);
insert into product(id, name, corp_id, p_type) value(232, '카카오뱅크 한달적금', 16, 'SAVING');
insert into saving_product value(232);
insert into product(id, name, corp_id, p_type) value(233, '새희망적금', 8, 'SAVING');
insert into saving_product value(233);
insert into product(id, name, corp_id, p_type) value(234, 'NH1418스윙적금', 2, 'SAVING');
insert into saving_product value(234);
insert into product(id, name, corp_id, p_type) value(235, '청년 처음적금', 11, 'SAVING');
insert into saving_product value(235);
insert into product(id, name, corp_id, p_type) value(236, 'IBK부모급여우대적금', 7, 'SAVING');
insert into saving_product value(236);
insert into product(id, name, corp_id, p_type) value(237, 'BNK 위더스(With-Us) 자유적금', 5, 'SAVING');
insert into saving_product value(237);
insert into product(id, name, corp_id, p_type) value(238, '원비즈플라자 멤버십 적금', 12, 'SAVING');
insert into saving_product value(238);
insert into product(id, name, corp_id, p_type) value(239, '우리 투게더 적금', 12, 'SAVING');
insert into saving_product value(239);
insert into product(id, name, corp_id, p_type) value(240, '3초 플레이 적금', 4, 'SAVING');
insert into saving_product value(240);
insert into product(id, name, corp_id, p_type) value(241, '텔레파시적금', 8, 'SAVING');
insert into saving_product value(241);
insert into product(id, name, corp_id, p_type) value(242, '터치 적금', 5, 'SAVING');
insert into saving_product value(242);
insert into product(id, name, corp_id, p_type) value(243, 'KB차차차 적금', 17, 'SAVING');
insert into saving_product value(243);
insert into product(id, name, corp_id, p_type) value(244, '하나 아이키움 적금', 15, 'SAVING');
insert into saving_product value(244);
insert into product(id, name, corp_id, p_type) value(245, '온국민 건강적금', 17, 'SAVING');
insert into saving_product value(245);
insert into product(id, name, corp_id, p_type) value(246, 'IBK장병내일준비적금', 7, 'SAVING');
insert into saving_product value(246);
insert into product(id, name, corp_id, p_type) value(247, '우리페이 적금', 12, 'SAVING');
insert into saving_product value(247);
insert into product(id, name, corp_id, p_type) value(248, 'KB장병내일준비적금', 17, 'SAVING');
insert into saving_product value(248);
insert into product(id, name, corp_id, p_type) value(249, 'IBK탄소제로적금', 7, 'SAVING');
insert into saving_product value(249);
insert into product(id, name, corp_id, p_type) value(250, '카카오뱅크 한달적금', 16, 'SAVING');
insert into saving_product value(250);
insert into product(id, name, corp_id, p_type) value(251, '새희망적금', 8, 'SAVING');
insert into saving_product value(251);
insert into product(id, name, corp_id, p_type) value(252, 'NH1418스윙적금', 2, 'SAVING');
insert into saving_product value(252);
insert into product(id, name, corp_id, p_type) value(253, '청년 처음적금', 11, 'SAVING');
insert into saving_product value(253);
insert into product(id, name, corp_id, p_type) value(254, 'IBK부모급여우대적금', 7, 'SAVING');
insert into saving_product value(254);
insert into product(id, name, corp_id, p_type) value(255, 'BNK 위더스(With-Us) 자유적금', 5, 'SAVING');
insert into saving_product value(255);
insert into product(id, name, corp_id, p_type) value(256, '원비즈플라자 멤버십 적금', 12, 'SAVING');
insert into saving_product value(256);
insert into product(id, name, corp_id, p_type) value(257, '우리 투게더 적금', 12, 'SAVING');
insert into saving_product value(257);
insert into product(id, name, corp_id, p_type) value(258, '3초 플레이 적금', 4, 'SAVING');
insert into saving_product value(258);
insert into product(id, name, corp_id, p_type) value(259, '텔레파시적금', 8, 'SAVING');
insert into saving_product value(259);
insert into product(id, name, corp_id, p_type) value(260, 'N일 적금(200일)', 12, 'SAVING');
insert into saving_product value(260);
insert into product(id, name, corp_id, p_type) value(261, 'KB차차차 적금', 17, 'SAVING');
insert into saving_product value(261);
insert into product(id, name, corp_id, p_type) value(262, '하나 아이키움 적금', 15, 'SAVING');
insert into saving_product value(262);
insert into product(id, name, corp_id, p_type) value(263, '온국민 건강적금', 17, 'SAVING');
insert into saving_product value(263);
insert into product(id, name, corp_id, p_type) value(264, 'IBK장병내일준비적금', 7, 'SAVING');
insert into saving_product value(264);
insert into product(id, name, corp_id, p_type) value(265, '우리페이 적금', 12, 'SAVING');
insert into saving_product value(265);
insert into product(id, name, corp_id, p_type) value(266, 'KB장병내일준비적금', 17, 'SAVING');
insert into saving_product value(266);
insert into product(id, name, corp_id, p_type) value(267, 'IBK탄소제로적금', 7, 'SAVING');
insert into saving_product value(267);
insert into product(id, name, corp_id, p_type) value(268, '카카오뱅크 한달적금', 16, 'SAVING');
insert into saving_product value(268);
insert into product(id, name, corp_id, p_type) value(269, '새희망적금', 8, 'SAVING');
insert into saving_product value(269);
insert into product(id, name, corp_id, p_type) value(270, 'NH1418스윙적금', 2, 'SAVING');
insert into saving_product value(270);
insert into product(id, name, corp_id, p_type) value(271, '청년 처음적금', 11, 'SAVING');
insert into saving_product value(271);
insert into product(id, name, corp_id, p_type) value(272, 'IBK부모급여우대적금', 7, 'SAVING');
insert into saving_product value(272);
insert into product(id, name, corp_id, p_type) value(273, 'BNK 위더스(With-Us) 자유적금', 5, 'SAVING');
insert into saving_product value(273);
insert into product(id, name, corp_id, p_type) value(274, '원비즈플라자 멤버십 적금', 12, 'SAVING');
insert into saving_product value(274);
insert into product(id, name, corp_id, p_type) value(275, '우리 투게더 적금', 12, 'SAVING');
insert into saving_product value(275);
insert into product(id, name, corp_id, p_type) value(276, '3초 플레이 적금', 4, 'SAVING');
insert into saving_product value(276);
insert into product(id, name, corp_id, p_type) value(277, '텔레파시적금', 8, 'SAVING');
insert into saving_product value(277);
insert into product(id, name, corp_id, p_type) value(278, 'N일 적금(200일)', 12, 'SAVING');
insert into saving_product value(278);
insert into product(id, name, corp_id, p_type) value(279, 'N일 적금', 12, 'SAVING');
insert into saving_product value(279);
insert into product(id, name, corp_id, p_type) value(280, '하나 아이키움 적금', 15, 'SAVING');
insert into saving_product value(280);
insert into product(id, name, corp_id, p_type) value(281, '온국민 건강적금', 17, 'SAVING');
insert into saving_product value(281);
insert into product(id, name, corp_id, p_type) value(282, 'IBK장병내일준비적금', 7, 'SAVING');
insert into saving_product value(282);
insert into product(id, name, corp_id, p_type) value(283, '우리페이 적금', 12, 'SAVING');
insert into saving_product value(283);
insert into product(id, name, corp_id, p_type) value(284, 'KB장병내일준비적금', 17, 'SAVING');
insert into saving_product value(284);
insert into product(id, name, corp_id, p_type) value(285, 'IBK탄소제로적금', 7, 'SAVING');
insert into saving_product value(285);
insert into product(id, name, corp_id, p_type) value(286, '카카오뱅크 한달적금', 16, 'SAVING');
insert into saving_product value(286);
insert into product(id, name, corp_id, p_type) value(287, '새희망적금', 8, 'SAVING');
insert into saving_product value(287);
insert into product(id, name, corp_id, p_type) value(288, 'NH1418스윙적금', 2, 'SAVING');
insert into saving_product value(288);
insert into product(id, name, corp_id, p_type) value(289, '청년 처음적금', 11, 'SAVING');
insert into saving_product value(289);
insert into product(id, name, corp_id, p_type) value(290, 'IBK부모급여우대적금', 7, 'SAVING');
insert into saving_product value(290);
insert into product(id, name, corp_id, p_type) value(291, 'BNK 위더스(With-Us) 자유적금', 5, 'SAVING');
insert into saving_product value(291);
insert into product(id, name, corp_id, p_type) value(292, '원비즈플라자 멤버십 적금', 12, 'SAVING');
insert into saving_product value(292);
insert into product(id, name, corp_id, p_type) value(293, '우리 투게더 적금', 12, 'SAVING');
insert into saving_product value(293);
insert into product(id, name, corp_id, p_type) value(294, '3초 플레이 적금', 4, 'SAVING');
insert into saving_product value(294);
insert into product(id, name, corp_id, p_type) value(295, '텔레파시적금', 8, 'SAVING');
insert into saving_product value(295);
insert into product(id, name, corp_id, p_type) value(296, 'N일 적금(200일)', 12, 'SAVING');
insert into saving_product value(296);
insert into product(id, name, corp_id, p_type) value(297, 'N일 적금', 12, 'SAVING');
insert into saving_product value(297);
insert into product(id, name, corp_id, p_type) value(298, 'Sh어촌청년을 응원海', 1, 'SAVING');
insert into saving_product value(298);
insert into product(id, name, corp_id, p_type) value(299, '온국민 건강적금', 17, 'SAVING');
insert into saving_product value(299);
insert into product(id, name, corp_id, p_type) value(300, 'IBK장병내일준비적금', 7, 'SAVING');
insert into saving_product value(300);
insert into product(id, name, corp_id, p_type) value(301, '우리페이 적금', 12, 'SAVING');
insert into saving_product value(301);
insert into product(id, name, corp_id, p_type) value(302, 'KB장병내일준비적금', 17, 'SAVING');
insert into saving_product value(302);
insert into product(id, name, corp_id, p_type) value(303, 'IBK탄소제로적금', 7, 'SAVING');
insert into saving_product value(303);
insert into product(id, name, corp_id, p_type) value(304, '카카오뱅크 한달적금', 16, 'SAVING');
insert into saving_product value(304);
insert into product(id, name, corp_id, p_type) value(305, '새희망적금', 8, 'SAVING');
insert into saving_product value(305);
insert into product(id, name, corp_id, p_type) value(306, 'NH1418스윙적금', 2, 'SAVING');
insert into saving_product value(306);
insert into product(id, name, corp_id, p_type) value(307, '청년 처음적금', 11, 'SAVING');
insert into saving_product value(307);
insert into product(id, name, corp_id, p_type) value(308, 'IBK부모급여우대적금', 7, 'SAVING');
insert into saving_product value(308);
insert into product(id, name, corp_id, p_type) value(309, 'BNK 위더스(With-Us) 자유적금', 5, 'SAVING');
insert into saving_product value(309);
insert into product(id, name, corp_id, p_type) value(310, '원비즈플라자 멤버십 적금', 12, 'SAVING');
insert into saving_product value(310);
insert into product(id, name, corp_id, p_type) value(311, '우리 투게더 적금', 12, 'SAVING');
insert into saving_product value(311);
insert into product(id, name, corp_id, p_type) value(312, '3초 플레이 적금', 4, 'SAVING');
insert into saving_product value(312);
insert into product(id, name, corp_id, p_type) value(313, '텔레파시적금', 8, 'SAVING');
insert into saving_product value(313);
insert into product(id, name, corp_id, p_type) value(314, 'N일 적금(200일)', 12, 'SAVING');
insert into saving_product value(314);
insert into product(id, name, corp_id, p_type) value(315, 'N일 적금', 12, 'SAVING');
insert into saving_product value(315);
insert into product(id, name, corp_id, p_type) value(316, 'Sh어촌청년을 응원海', 1, 'SAVING');
insert into saving_product value(316);
insert into product(id, name, corp_id, p_type) value(317, 'IBK청년도약계좌', 7, 'SAVING');
insert into saving_product value(317);
insert into product(id, name, corp_id, p_type) value(318, 'IBK장병내일준비적금', 7, 'SAVING');
insert into saving_product value(318);
insert into product(id, name, corp_id, p_type) value(319, '우리페이 적금', 12, 'SAVING');
insert into saving_product value(319);
insert into product(id, name, corp_id, p_type) value(320, 'KB장병내일준비적금', 17, 'SAVING');
insert into saving_product value(320);
insert into product(id, name, corp_id, p_type) value(321, 'IBK탄소제로적금', 7, 'SAVING');
insert into saving_product value(321);
insert into product(id, name, corp_id, p_type) value(322, '카카오뱅크 한달적금', 16, 'SAVING');
insert into saving_product value(322);
insert into product(id, name, corp_id, p_type) value(323, '새희망적금', 8, 'SAVING');
insert into saving_product value(323);
insert into product(id, name, corp_id, p_type) value(324, 'NH1418스윙적금', 2, 'SAVING');
insert into saving_product value(324);
insert into product(id, name, corp_id, p_type) value(325, '청년 처음적금', 11, 'SAVING');
insert into saving_product value(325);
insert into product(id, name, corp_id, p_type) value(326, 'IBK부모급여우대적금', 7, 'SAVING');
insert into saving_product value(326);
insert into product(id, name, corp_id, p_type) value(327, 'BNK 위더스(With-Us) 자유적금', 5, 'SAVING');
insert into saving_product value(327);
insert into product(id, name, corp_id, p_type) value(328, '원비즈플라자 멤버십 적금', 12, 'SAVING');
insert into saving_product value(328);
insert into product(id, name, corp_id, p_type) value(329, '우리 투게더 적금', 12, 'SAVING');
insert into saving_product value(329);
insert into product(id, name, corp_id, p_type) value(330, '3초 플레이 적금', 4, 'SAVING');
insert into saving_product value(330);
insert into product(id, name, corp_id, p_type) value(331, '텔레파시적금', 8, 'SAVING');
insert into saving_product value(331);
insert into product(id, name, corp_id, p_type) value(332, 'N일 적금(200일)', 12, 'SAVING');
insert into saving_product value(332);
insert into product(id, name, corp_id, p_type) value(333, 'N일 적금', 12, 'SAVING');
insert into saving_product value(333);
insert into product(id, name, corp_id, p_type) value(334, 'Sh어촌청년을 응원海', 1, 'SAVING');
insert into saving_product value(334);
insert into product(id, name, corp_id, p_type) value(335, 'IBK청년도약계좌', 7, 'SAVING');
insert into saving_product value(335);
insert into product(id, name, corp_id, p_type) value(336, 'KB청년도약계좌', 17, 'SAVING');
insert into saving_product value(336);
insert into product(id, name, corp_id, p_type) value(337, '우리페이 적금', 12, 'SAVING');
insert into saving_product value(337);
insert into product(id, name, corp_id, p_type) value(338, 'KB장병내일준비적금', 17, 'SAVING');
insert into saving_product value(338);
insert into product(id, name, corp_id, p_type) value(339, 'IBK탄소제로적금', 7, 'SAVING');
insert into saving_product value(339);
insert into product(id, name, corp_id, p_type) value(340, '카카오뱅크 한달적금', 16, 'SAVING');
insert into saving_product value(340);
insert into product(id, name, corp_id, p_type) value(341, '새희망적금', 8, 'SAVING');
insert into saving_product value(341);
insert into product(id, name, corp_id, p_type) value(342, 'NH1418스윙적금', 2, 'SAVING');
insert into saving_product value(342);
insert into product(id, name, corp_id, p_type) value(343, '청년 처음적금', 11, 'SAVING');
insert into saving_product value(343);
insert into product(id, name, corp_id, p_type) value(344, 'IBK부모급여우대적금', 7, 'SAVING');
insert into saving_product value(344);
insert into product(id, name, corp_id, p_type) value(345, 'BNK 위더스(With-Us) 자유적금', 5, 'SAVING');
insert into saving_product value(345);
insert into product(id, name, corp_id, p_type) value(346, '원비즈플라자 멤버십 적금', 12, 'SAVING');
insert into saving_product value(346);
insert into product(id, name, corp_id, p_type) value(347, '우리 투게더 적금', 12, 'SAVING');
insert into saving_product value(347);
insert into product(id, name, corp_id, p_type) value(348, '3초 플레이 적금', 4, 'SAVING');
insert into saving_product value(348);
insert into product(id, name, corp_id, p_type) value(349, '텔레파시적금', 8, 'SAVING');
insert into saving_product value(349);
insert into product(id, name, corp_id, p_type) value(350, 'N일 적금(200일)', 12, 'SAVING');
insert into saving_product value(350);
insert into product(id, name, corp_id, p_type) value(351, 'N일 적금', 12, 'SAVING');
insert into saving_product value(351);
insert into product(id, name, corp_id, p_type) value(352, 'Sh어촌청년을 응원海', 1, 'SAVING');
insert into saving_product value(352);
insert into product(id, name, corp_id, p_type) value(353, 'IBK청년도약계좌', 7, 'SAVING');
insert into saving_product value(353);
insert into product(id, name, corp_id, p_type) value(354, 'KB청년도약계좌', 17, 'SAVING');
insert into saving_product value(354);
insert into product(id, name, corp_id, p_type) value(355, 'NH청년도약계좌', 2, 'SAVING');
insert into saving_product value(355);
insert into product(id, name, corp_id, p_type) value(356, 'KB장병내일준비적금', 17, 'SAVING');
insert into saving_product value(356);
insert into product(id, name, corp_id, p_type) value(357, 'IBK탄소제로적금', 7, 'SAVING');
insert into saving_product value(357);
insert into product(id, name, corp_id, p_type) value(358, '카카오뱅크 한달적금', 16, 'SAVING');
insert into saving_product value(358);
insert into product(id, name, corp_id, p_type) value(359, '새희망적금', 8, 'SAVING');
insert into saving_product value(359);
insert into product(id, name, corp_id, p_type) value(360, 'NH1418스윙적금', 2, 'SAVING');
insert into saving_product value(360);
insert into product(id, name, corp_id, p_type) value(361, '청년 처음적금', 11, 'SAVING');
insert into saving_product value(361);
insert into product(id, name, corp_id, p_type) value(362, 'IBK부모급여우대적금', 7, 'SAVING');
insert into saving_product value(362);
insert into product(id, name, corp_id, p_type) value(363, 'BNK 위더스(With-Us) 자유적금', 5, 'SAVING');
insert into saving_product value(363);
insert into product(id, name, corp_id, p_type) value(364, '원비즈플라자 멤버십 적금', 12, 'SAVING');
insert into saving_product value(364);
insert into product(id, name, corp_id, p_type) value(365, '우리 투게더 적금', 12, 'SAVING');
insert into saving_product value(365);
insert into product(id, name, corp_id, p_type) value(366, '3초 플레이 적금', 4, 'SAVING');
insert into saving_product value(366);
insert into product(id, name, corp_id, p_type) value(367, '텔레파시적금', 8, 'SAVING');
insert into saving_product value(367);
insert into product(id, name, corp_id, p_type) value(368, 'N일 적금(200일)', 12, 'SAVING');
insert into saving_product value(368);
insert into product(id, name, corp_id, p_type) value(369, 'N일 적금', 12, 'SAVING');
insert into saving_product value(369);
insert into product(id, name, corp_id, p_type) value(370, 'Sh어촌청년을 응원海', 1, 'SAVING');
insert into saving_product value(370);
insert into product(id, name, corp_id, p_type) value(371, 'IBK청년도약계좌', 7, 'SAVING');
insert into saving_product value(371);
insert into product(id, name, corp_id, p_type) value(372, 'KB청년도약계좌', 17, 'SAVING');
insert into saving_product value(372);
insert into product(id, name, corp_id, p_type) value(373, 'NH청년도약계좌', 2, 'SAVING');
insert into saving_product value(373);
insert into product(id, name, corp_id, p_type) value(374, '신한 청년도약계좌', 11, 'SAVING');
insert into saving_product value(374);
insert into product(id, name, corp_id, p_type) value(375, 'IBK탄소제로적금', 7, 'SAVING');
insert into saving_product value(375);
insert into product(id, name, corp_id, p_type) value(376, '카카오뱅크 한달적금', 16, 'SAVING');
insert into saving_product value(376);
insert into product(id, name, corp_id, p_type) value(377, '새희망적금', 8, 'SAVING');
insert into saving_product value(377);
insert into product(id, name, corp_id, p_type) value(378, 'NH1418스윙적금', 2, 'SAVING');
insert into saving_product value(378);
insert into product(id, name, corp_id, p_type) value(379, '청년 처음적금', 11, 'SAVING');
insert into saving_product value(379);
insert into product(id, name, corp_id, p_type) value(380, 'IBK부모급여우대적금', 7, 'SAVING');
insert into saving_product value(380);
insert into product(id, name, corp_id, p_type) value(381, 'BNK 위더스(With-Us) 자유적금', 5, 'SAVING');
insert into saving_product value(381);
insert into product(id, name, corp_id, p_type) value(382, '원비즈플라자 멤버십 적금', 12, 'SAVING');
insert into saving_product value(382);
insert into product(id, name, corp_id, p_type) value(383, '우리 투게더 적금', 12, 'SAVING');
insert into saving_product value(383);
insert into product(id, name, corp_id, p_type) value(384, '3초 플레이 적금', 4, 'SAVING');
insert into saving_product value(384);
insert into product(id, name, corp_id, p_type) value(385, '텔레파시적금', 8, 'SAVING');
insert into saving_product value(385);
insert into product(id, name, corp_id, p_type) value(386, 'N일 적금(200일)', 12, 'SAVING');
insert into saving_product value(386);
insert into product(id, name, corp_id, p_type) value(387, 'N일 적금', 12, 'SAVING');
insert into saving_product value(387);
insert into product(id, name, corp_id, p_type) value(388, 'Sh어촌청년을 응원海', 1, 'SAVING');
insert into saving_product value(388);
insert into product(id, name, corp_id, p_type) value(389, 'IBK청년도약계좌', 7, 'SAVING');
insert into saving_product value(389);
insert into product(id, name, corp_id, p_type) value(390, 'KB청년도약계좌', 17, 'SAVING');
insert into saving_product value(390);
insert into product(id, name, corp_id, p_type) value(391, 'NH청년도약계좌', 2, 'SAVING');
insert into saving_product value(391);
insert into product(id, name, corp_id, p_type) value(392, '신한 청년도약계좌', 11, 'SAVING');
insert into saving_product value(392);
insert into product(id, name, corp_id, p_type) value(393, '우리 청년도약계좌', 12, 'SAVING');
insert into saving_product value(393);
insert into product(id, name, corp_id, p_type) value(394, '카카오뱅크 한달적금', 16, 'SAVING');
insert into saving_product value(394);
insert into product(id, name, corp_id, p_type) value(395, '새희망적금', 8, 'SAVING');
insert into saving_product value(395);
insert into product(id, name, corp_id, p_type) value(396, 'NH1418스윙적금', 2, 'SAVING');
insert into saving_product value(396);
insert into product(id, name, corp_id, p_type) value(397, '청년 처음적금', 11, 'SAVING');
insert into saving_product value(397);
insert into product(id, name, corp_id, p_type) value(398, 'IBK부모급여우대적금', 7, 'SAVING');
insert into saving_product value(398);
insert into product(id, name, corp_id, p_type) value(399, 'BNK 위더스(With-Us) 자유적금', 5, 'SAVING');
insert into saving_product value(399);
insert into product(id, name, corp_id, p_type) value(400, '원비즈플라자 멤버십 적금', 12, 'SAVING');
insert into saving_product value(400);
insert into product(id, name, corp_id, p_type) value(401, '우리 투게더 적금', 12, 'SAVING');
insert into saving_product value(401);
insert into product(id, name, corp_id, p_type) value(402, '3초 플레이 적금', 4, 'SAVING');
insert into saving_product value(402);
insert into product(id, name, corp_id, p_type) value(403, '텔레파시적금', 8, 'SAVING');
insert into saving_product value(403);
insert into product(id, name, corp_id, p_type) value(404, 'N일 적금(200일)', 12, 'SAVING');
insert into saving_product value(404);
insert into product(id, name, corp_id, p_type) value(405, 'N일 적금', 12, 'SAVING');
insert into saving_product value(405);
insert into product(id, name, corp_id, p_type) value(406, 'Sh어촌청년을 응원海', 1, 'SAVING');
insert into saving_product value(406);
insert into product(id, name, corp_id, p_type) value(407, 'IBK청년도약계좌', 7, 'SAVING');
insert into saving_product value(407);
insert into product(id, name, corp_id, p_type) value(408, 'KB청년도약계좌', 17, 'SAVING');
insert into saving_product value(408);
insert into product(id, name, corp_id, p_type) value(409, 'NH청년도약계좌', 2, 'SAVING');
insert into saving_product value(409);
insert into product(id, name, corp_id, p_type) value(410, '신한 청년도약계좌', 11, 'SAVING');
insert into saving_product value(410);
insert into product(id, name, corp_id, p_type) value(411, '우리 청년도약계좌', 12, 'SAVING');
insert into saving_product value(411);
insert into product(id, name, corp_id, p_type) value(412, '하나 청년도약계좌', 15, 'SAVING');
insert into saving_product value(412);
insert into product(id, name, corp_id, p_type) value(413, '신한투자증권 종합계좌', 19, 'CMA');
insert into cmaproduct value(413);