insert into product(id, name, corp_id, p_type) value(246, '내일로 신용대출', 28, 'LOAN')
insert into loan_product value(246)
insert into product(id, name, corp_id, p_type) value(247, '내집으로 신용대출', 28, 'LOAN')
insert into loan_product value(247)
insert into product(id, name, corp_id, p_type) value(248, '자동차 담보대출 내차로', 28, 'LOAN')
insert into loan_product value(248)
insert into product(id, name, corp_id, p_type) value(249, '소액론 신용대출', 28, 'LOAN')
insert into loan_product value(249)
insert into product(id, name, corp_id, p_type) value(250, '장기카드대출', 6, 'LOAN')
insert into loan_product value(250)
insert into product(id, name, corp_id, p_type) value(251, 'BNK모바일신용대출', 14, 'LOAN')
insert into loan_product value(251)
insert into product(id, name, corp_id, p_type) value(252, '올인원대출', 7, 'LOAN')
insert into loan_product value(252)
insert into product(id, name, corp_id, p_type) value(253, '신용대출', 22, 'LOAN')
insert into loan_product value(253)
insert into product(id, name, corp_id, p_type) value(254, '신용대출플러스', 22, 'LOAN')
insert into loan_product value(254)
insert into product(id, name, corp_id, p_type) value(255, '즉시대출', 1, 'LOAN')
insert into loan_product value(255)
insert into product(id, name, corp_id, p_type) value(256, '사업자금대출', 1, 'LOAN')
insert into loan_product value(256)
insert into product(id, name, corp_id, p_type) value(257, '원스탑대환대출', 1, 'LOAN')
insert into loan_product value(257)
insert into product(id, name, corp_id, p_type) value(258, '모바일프라임론', 16, 'LOAN')
insert into loan_product value(258)
insert into product(id, name, corp_id, p_type) value(259, '사장님 신용대출', 22, 'LOAN')
insert into loan_product value(259)
insert into product(id, name, corp_id, p_type) value(260, 'JB 위풍당당 대출', 13, 'LOAN')
insert into loan_product value(260)
insert into product(id, name, corp_id, p_type) value(261, '돌려드림론', 17, 'LOAN')
insert into loan_product value(261)
insert into product(id, name, corp_id, p_type) value(262, 'KB국민 이지론플러스', 6, 'LOAN')
insert into loan_product value(262)
insert into product(id, name, corp_id, p_type) value(263, 'Fi신용대출', 29, 'LOAN')
insert into loan_product value(263)
insert into product(id, name, corp_id, p_type) value(264, '사장님대출', 26, 'LOAN')
insert into loan_product value(264)
insert into product(id, name, corp_id, p_type) value(265, '사장님마이너스통장', 26, 'LOAN')
insert into loan_product value(265)
insert into product(id, name, corp_id, p_type) value(266, '우리 Oh!(5)클릭 대출', 20, 'LOAN')
insert into loan_product value(266)
insert into product(id, name, corp_id, p_type) value(267, 'BNK모바일신용대출플러스', 14, 'LOAN')
insert into loan_product value(267)
insert into product(id, name, corp_id, p_type) value(268, 'JB 햇살론뱅크', 13, 'LOAN')
insert into loan_product value(268)
insert into product(id, name, corp_id, p_type) value(269, 'PRIME플러스론', 16, 'LOAN')
insert into loan_product value(269)
insert into product(id, name, corp_id, p_type) value(270, 'GPS론', 30, 'LOAN')
insert into loan_product value(270)
insert into product(id, name, corp_id, p_type) value(271, '빅머니M', 30, 'LOAN')
insert into loan_product value(271)
insert into product(id, name, corp_id, p_type) value(272, '빅머니U', 30, 'LOAN')
insert into loan_product value(272)
insert into product(id, name, corp_id, p_type) value(273, '예스론', 30, 'LOAN')
insert into loan_product value(273)
insert into product(id, name, corp_id, p_type) value(274, 'JB 탄탄대로 사업자대출', 13, 'LOAN')
insert into loan_product value(274)
insert into product(id, name, corp_id, p_type) value(275, 'kiwi신용대출', 31, 'LOAN')
insert into loan_product value(275)
insert into product(id, name, corp_id, p_type) value(276, 'kiwi마이홈신용대출', 31, 'LOAN')
insert into loan_product value(276)
insert into product(id, name, corp_id, p_type) value(277, 'kiwi전환대출', 31, 'LOAN')
insert into loan_product value(277)
insert into product(id, name, corp_id, p_type) value(278, '직장인중금리', 17, 'LOAN')
insert into loan_product value(278)
insert into product(id, name, corp_id, p_type) value(279, '참신한대출', 32, 'LOAN')
insert into loan_product value(279)
insert into product(id, name, corp_id, p_type) value(280, 'KB국민 개인사업자대출', 6, 'LOAN')
insert into loan_product value(280)
insert into product(id, name, corp_id, p_type) value(281, 'KJB햇살론뱅크', 16, 'LOAN')
insert into loan_product value(281)
insert into product(id, name, corp_id, p_type) value(282, '사업자대출', 33, 'LOAN')
insert into loan_product value(282)
insert into product(id, name, corp_id, p_type) value(283, '교보e바로받는신용대출', 34, 'LOAN')
insert into loan_product value(283)
insert into product(id, name, corp_id, p_type) value(284, '대환대출', 35, 'LOAN')
insert into loan_product value(284)
insert into product(id, name, corp_id, p_type) value(285, '오토론', 36, 'LOAN')
insert into loan_product value(285)
insert into product(id, name, corp_id, p_type) value(286, '온라인햇살론', 37, 'LOAN')
insert into loan_product value(286)
insert into product(id, name, corp_id, p_type) value(287, '근로자햇살론', 38, 'LOAN')
insert into loan_product value(287)
insert into product(id, name, corp_id, p_type) value(288, 'BNK신용대출', 39, 'LOAN')
insert into loan_product value(288)
insert into product(id, name, corp_id, p_type) value(289, 'BNK신용대출PLUS', 39, 'LOAN')
insert into loan_product value(289)
insert into product(id, name, corp_id, p_type) value(290, 'kiwi비상금대출', 31, 'LOAN')
insert into loan_product value(290)
insert into product(id, name, corp_id, p_type) value(291, 'kiwi여성비상금대출', 31, 'LOAN')
insert into loan_product value(291)
insert into product(id, name, corp_id, p_type) value(292, '사잇돌2', 35, 'LOAN')
insert into loan_product value(292)
insert into product(id, name, corp_id, p_type) value(293, '하나슈퍼드림론', 40, 'LOAN')
insert into loan_product value(293)
insert into product(id, name, corp_id, p_type) value(294, '햇살론 ', 40, 'LOAN')
insert into loan_product value(294)
insert into product(id, name, corp_id, p_type) value(295, '햇살론', 41, 'LOAN')
insert into loan_product value(295)
insert into product(id, name, corp_id, p_type) value(296, '햇살론2', 30, 'LOAN')
insert into loan_product value(296)
insert into product(id, name, corp_id, p_type) value(297, '햇살론/온라인햇살론', 32, 'LOAN')
insert into loan_product value(297)
insert into product(id, name, corp_id, p_type) value(298, '사잇돌2대출', 32, 'LOAN')
insert into loan_product value(298)
insert into product(id, name, corp_id, p_type) value(299, '미래에셋캐피탈 신용대출', 43, 'LOAN')
insert into loan_product value(299)
insert into product(id, name, corp_id, p_type) value(300, '일반신용대출', 6, 'LOAN')
insert into loan_product value(300)
insert into product(id, name, corp_id, p_type) value(301, '직장인 신용대출', 44, 'LOAN')
insert into loan_product value(301)
insert into product(id, name, corp_id, p_type) value(302, '비타WON [신용]', 46, 'LOAN')
insert into loan_product value(302)
insert into product(id, name, corp_id, p_type) value(303, '직장인 햇살론', 47, 'LOAN')
insert into loan_product value(303)
insert into product(id, name, corp_id, p_type) value(304, '마이론', 41, 'LOAN')
insert into loan_product value(304)
insert into product(id, name, corp_id, p_type) value(305, 'DreamBig 신용대출', 48, 'LOAN')
insert into loan_product value(305)
insert into product(id, name, corp_id, p_type) value(306, '살만한대출', 49, 'LOAN')
insert into loan_product value(306)
insert into product(id, name, corp_id, p_type) value(307, '네이버파이낸셜 연계 신용대출(자산론)', 50, 'LOAN')
insert into loan_product value(307)
insert into product(id, name, corp_id, p_type) value(308, '키움예스론H', 51, 'LOAN')
insert into loan_product value(308)
insert into product(id, name, corp_id, p_type) value(309, '직장인신용대출 오렌지론', 53, 'LOAN')
insert into loan_product value(309)
insert into product(id, name, corp_id, p_type) value(310, '키움예스론F', 51, 'LOAN')
insert into loan_product value(310)
insert into product(id, name, corp_id, p_type) value(311, '키움예스론', 51, 'LOAN')
insert into loan_product value(311)
insert into product(id, name, corp_id, p_type) value(312, '키움 신용대출', 52, 'LOAN')
insert into loan_product value(312)
insert into product(id, name, corp_id, p_type) value(313, 'OK한도우대론', 54, 'LOAN')
insert into loan_product value(313)
insert into product(id, name, corp_id, p_type) value(314, '주부OK론', 54, 'LOAN')
insert into loan_product value(314)
insert into product(id, name, corp_id, p_type) value(315, '사업자OK론', 54, 'LOAN')
insert into loan_product value(315)
insert into product(id, name, corp_id, p_type) value(316, '웰컴중금리대출', 42, 'LOAN')
insert into loan_product value(316)
insert into product(id, name, corp_id, p_type) value(317, '참신한500', 32, 'LOAN')
insert into loan_product value(317)
insert into product(id, name, corp_id, p_type) value(318, '뉴플랜론Ⅲ', 55, 'LOAN')
insert into loan_product value(318)
insert into product(id, name, corp_id, p_type) value(319, '개인신용대출', 45, 'LOAN')
insert into loan_product value(319)
insert into product(id, name, corp_id, p_type) value(320, '자동차담보대출', 45, 'LOAN')
insert into loan_product value(320)
insert into product(id, name, corp_id, p_type) value(321, 'i-빅론U', 37, 'LOAN')
insert into loan_product value(321)
insert into product(id, name, corp_id, p_type) value(322, '네이버파이낸셜 연계 신용대출(직장인론)', 50, 'LOAN')
insert into loan_product value(322)
insert into product(id, name, corp_id, p_type) value(323, '애큐온프라임론', 56, 'LOAN')
insert into loan_product value(323)
insert into product(id, name, corp_id, p_type) value(324, '파라솔 신용대출(모바일 자동대출)', 57, 'LOAN')
insert into loan_product value(324)
insert into product(id, name, corp_id, p_type) value(325, '라이브M', 30, 'LOAN')
insert into loan_product value(325)
insert into product(id, name, corp_id, p_type) value(326, '라이브U', 30, 'LOAN')
insert into loan_product value(326)
insert into product(id, name, corp_id, p_type) value(327, '직장인 신용대출(오리치론)', 58, 'LOAN')
insert into loan_product value(327)
insert into product(id, name, corp_id, p_type) value(328, '소액신용대출(오예스론)', 58, 'LOAN')
insert into loan_product value(328)
insert into product(id, name, corp_id, p_type) value(329, '믿을론(다이렉트)', 59, 'LOAN')
insert into loan_product value(329)
