insert into corporation value (56, '미래에셋자산운용', 'https://financial.pstatic.net/pie/common-bi/1.0.2/images/CAPITAL_MIRAE_Profile.png')
insert into corporation value (57, '신한자산운용', 'https://financial.pstatic.net/pie/common-bi/1.0.2/images/CD_SHINHAN_Profile.png')
insert into corporation value (58, '삼성자산운용', 'https://yt3.googleusercontent.com/Q3PRIMassq_T3-Ax48QRNHN4y58j4JtyUywTRSLDC3_udGI57UC6HJPghC1dbNQVvtJRPL4RCQ=s900-c-k-c0x00ffffff-no-rj')
insert into corporation value (59, '케이비자산운용', 'https://financial.pstatic.net/pie/common-bi/1.0.2/images/CAPITAL_KB_Profile.png')
insert into product(id, name, corp_id, p_type) value(610, '미래에셋TIGER필라델피아반도체레버리지증권상장지수투자신탁(주식혼합-파생형)(합성)', 56, 'FUND')
insert into fund_product(id, price) value(610, 26382.79)
insert into product(id, name, corp_id, p_type) value(611, '미래에셋TIGER미국나스닥100레버리지증권상장지수투자신탁(주식혼합-파생형)(합성)', 56, 'FUND')
insert into fund_product(id, price) value(611, 19057.81)
insert into product(id, name, corp_id, p_type) value(612, '미래에셋인디아인프라섹터증권모투자신탁(주식)', 56, 'FUND')
insert into fund_product(id, price) value(612, 2775.85)
insert into product(id, name, corp_id, p_type) value(613, '미래에셋연금인디아인프라증권자투자신탁 1(주식)', 56, 'FUND')
insert into fund_product(id, price) value(613, 1130.22)
insert into product(id, name, corp_id, p_type) value(614, '미래에셋인디아인프라섹터증권자투자신탁 1(주식)', 56, 'FUND')
insert into fund_product(id, price) value(614, 3060.99)
insert into product(id, name, corp_id, p_type) value(615, '미래에셋TIGER필라델피아반도체레버리지증권상장지수투자신탁(주식혼합-파생형)(합성)', 56, 'FUND')
insert into fund_product(id, price) value(615, 26382.79)
insert into product(id, name, corp_id, p_type) value(616, '미래에셋TIGER미국나스닥100레버리지증권상장지수투자신탁(주식혼합-파생형)(합성)', 56, 'FUND')
insert into fund_product(id, price) value(616, 19057.81)
insert into product(id, name, corp_id, p_type) value(617, '미래에셋인디아인프라섹터증권모투자신탁(주식)', 56, 'FUND')
insert into fund_product(id, price) value(617, 2775.85)
insert into product(id, name, corp_id, p_type) value(618, '미래에셋연금인디아인프라증권자투자신탁 1(주식)', 56, 'FUND')
insert into fund_product(id, price) value(618, 1130.22)
insert into product(id, name, corp_id, p_type) value(619, '미래에셋인디아인프라섹터증권자투자신탁 1(주식)', 56, 'FUND')
insert into fund_product(id, price) value(619, 3060.99)
insert into product(id, name, corp_id, p_type) value(620, '미래에셋TIGER필라델피아반도체레버리지증권상장지수투자신탁(주식혼합-파생형)(합성)', 56, 'FUND')
insert into fund_product(id, price) value(620, 26382.79)
insert into product(id, name, corp_id, p_type) value(621, '미래에셋TIGER미국나스닥100레버리지증권상장지수투자신탁(주식혼합-파생형)(합성)', 56, 'FUND')
insert into fund_product(id, price) value(621, 19057.81)
insert into product(id, name, corp_id, p_type) value(622, '미래에셋인디아인프라섹터증권모투자신탁(주식)', 56, 'FUND')
insert into fund_product(id, price) value(622, 2775.85)
insert into product(id, name, corp_id, p_type) value(623, '미래에셋연금인디아인프라증권자투자신탁 1(주식)', 56, 'FUND')
insert into fund_product(id, price) value(623, 1130.22)
insert into product(id, name, corp_id, p_type) value(624, '미래에셋인디아인프라섹터증권자투자신탁 1(주식)', 56, 'FUND')
insert into fund_product(id, price) value(624, 3060.99)
insert into product(id, name, corp_id, p_type) value(625, '미래에셋TIGER필라델피아반도체레버리지증권상장지수투자신탁(주식혼합-파생형)(합성)', 56, 'FUND')
insert into fund_product(id, price) value(625, 26382.79)
insert into product(id, name, corp_id, p_type) value(626, '미래에셋TIGER미국나스닥100레버리지증권상장지수투자신탁(주식혼합-파생형)(합성)', 56, 'FUND')
insert into fund_product(id, price) value(626, 19057.81)
insert into product(id, name, corp_id, p_type) value(627, '미래에셋인디아인프라섹터증권모투자신탁(주식)', 56, 'FUND')
insert into fund_product(id, price) value(627, 2775.85)
insert into product(id, name, corp_id, p_type) value(628, '미래에셋연금인디아인프라증권자투자신탁 1(주식)', 56, 'FUND')
insert into fund_product(id, price) value(628, 1130.22)
insert into product(id, name, corp_id, p_type) value(629, '미래에셋인디아인프라섹터증권자투자신탁 1(주식)', 56, 'FUND')
insert into fund_product(id, price) value(629, 3060.99)
insert into product(id, name, corp_id, p_type) value(630, '미래에셋TIGER필라델피아반도체레버리지증권상장지수투자신탁(주식혼합-파생형)(합성)', 56, 'FUND')
insert into fund_product(id, price) value(630, 26382.79)
insert into product(id, name, corp_id, p_type) value(631, '미래에셋TIGER미국나스닥100레버리지증권상장지수투자신탁(주식혼합-파생형)(합성)', 56, 'FUND')
insert into fund_product(id, price) value(631, 19057.81)
insert into product(id, name, corp_id, p_type) value(632, '미래에셋인디아인프라섹터증권모투자신탁(주식)', 56, 'FUND')
insert into fund_product(id, price) value(632, 2775.85)
insert into product(id, name, corp_id, p_type) value(633, '미래에셋연금인디아인프라증권자투자신탁 1(주식)', 56, 'FUND')
insert into fund_product(id, price) value(633, 1130.22)
insert into product(id, name, corp_id, p_type) value(634, '미래에셋인디아인프라섹터증권자투자신탁 1(주식)', 56, 'FUND')
insert into fund_product(id, price) value(634, 3060.99)
insert into product(id, name, corp_id, p_type) value(635, '신한SOL한국형글로벌반도체액티브증권상장지수투자신탁[주식]', 57, 'FUND')
insert into fund_product(id, price) value(635, 18833.21)
insert into product(id, name, corp_id, p_type) value(636, '신한인디아증권모투자신탁[주식]', 57, 'FUND')
insert into fund_product(id, price) value(636, 2850.62)
insert into product(id, name, corp_id, p_type) value(637, '신한SOLAI반도체소부장증권상장지수투자신탁[주식]', 57, 'FUND')
insert into fund_product(id, price) value(637, 15731.5)
insert into product(id, name, corp_id, p_type) value(638, '신한동유럽플러스증권모투자신탁[주식]', 57, 'FUND')
insert into fund_product(id, price) value(638, 947.28)
insert into product(id, name, corp_id, p_type) value(639, '신한동유럽플러스증권자투자신탁(H)[주식](종류)', 57, 'FUND')
insert into fund_product(id, price) value(639, 671.13)
insert into product(id, name, corp_id, p_type) value(640, '신한SOL한국형글로벌반도체액티브증권상장지수투자신탁[주식]', 57, 'FUND')
insert into fund_product(id, price) value(640, 18833.21)
insert into product(id, name, corp_id, p_type) value(641, '신한인디아증권모투자신탁[주식]', 57, 'FUND')
insert into fund_product(id, price) value(641, 2850.62)
insert into product(id, name, corp_id, p_type) value(642, '신한SOLAI반도체소부장증권상장지수투자신탁[주식]', 57, 'FUND')
insert into fund_product(id, price) value(642, 15731.5)
insert into product(id, name, corp_id, p_type) value(643, '신한동유럽플러스증권모투자신탁[주식]', 57, 'FUND')
insert into fund_product(id, price) value(643, 947.28)
insert into product(id, name, corp_id, p_type) value(644, '신한동유럽플러스증권자투자신탁(H)[주식](종류)', 57, 'FUND')
insert into fund_product(id, price) value(644, 671.13)
insert into product(id, name, corp_id, p_type) value(645, '신한SOL한국형글로벌반도체액티브증권상장지수투자신탁[주식]', 57, 'FUND')
insert into fund_product(id, price) value(645, 18833.21)
insert into product(id, name, corp_id, p_type) value(646, '신한인디아증권모투자신탁[주식]', 57, 'FUND')
insert into fund_product(id, price) value(646, 2850.62)
insert into product(id, name, corp_id, p_type) value(647, '신한SOLAI반도체소부장증권상장지수투자신탁[주식]', 57, 'FUND')
insert into fund_product(id, price) value(647, 15731.5)
insert into product(id, name, corp_id, p_type) value(648, '신한동유럽플러스증권모투자신탁[주식]', 57, 'FUND')
insert into fund_product(id, price) value(648, 947.28)
insert into product(id, name, corp_id, p_type) value(649, '신한동유럽플러스증권자투자신탁(H)[주식](종류)', 57, 'FUND')
insert into fund_product(id, price) value(649, 671.13)
insert into product(id, name, corp_id, p_type) value(650, '신한SOL한국형글로벌반도체액티브증권상장지수투자신탁[주식]', 57, 'FUND')
insert into fund_product(id, price) value(650, 18833.21)
insert into product(id, name, corp_id, p_type) value(651, '신한인디아증권모투자신탁[주식]', 57, 'FUND')
insert into fund_product(id, price) value(651, 2850.62)
insert into product(id, name, corp_id, p_type) value(652, '신한SOLAI반도체소부장증권상장지수투자신탁[주식]', 57, 'FUND')
insert into fund_product(id, price) value(652, 15731.5)
insert into product(id, name, corp_id, p_type) value(653, '신한동유럽플러스증권모투자신탁[주식]', 57, 'FUND')
insert into fund_product(id, price) value(653, 947.28)
insert into product(id, name, corp_id, p_type) value(654, '신한동유럽플러스증권자투자신탁(H)[주식](종류)', 57, 'FUND')
insert into fund_product(id, price) value(654, 671.13)
insert into product(id, name, corp_id, p_type) value(655, '신한SOL한국형글로벌반도체액티브증권상장지수투자신탁[주식]', 57, 'FUND')
insert into fund_product(id, price) value(655, 18833.21)
insert into product(id, name, corp_id, p_type) value(656, '신한인디아증권모투자신탁[주식]', 57, 'FUND')
insert into fund_product(id, price) value(656, 2850.62)
insert into product(id, name, corp_id, p_type) value(657, '신한SOLAI반도체소부장증권상장지수투자신탁[주식]', 57, 'FUND')
insert into fund_product(id, price) value(657, 15731.5)
insert into product(id, name, corp_id, p_type) value(658, '신한동유럽플러스증권모투자신탁[주식]', 57, 'FUND')
insert into fund_product(id, price) value(658, 947.28)
insert into product(id, name, corp_id, p_type) value(659, '신한동유럽플러스증권자투자신탁(H)[주식](종류)', 57, 'FUND')
insert into fund_product(id, price) value(659, 671.13)
insert into product(id, name, corp_id, p_type) value(660, '삼성KODEX미국반도체MV증권상장지수투자신탁[주식]', 58, 'FUND')
insert into fund_product(id, price) value(660, 22962.95)
insert into product(id, name, corp_id, p_type) value(661, '삼성인도중소형FOCUS증권모투자신탁[주식]', 58, 'FUND')
insert into fund_product(id, price) value(661, 4215.64)
insert into product(id, name, corp_id, p_type) value(662, '삼성인도중소형FOCUS증권자투자신탁UH[주식]', 58, 'FUND')
insert into fund_product(id, price) value(662, 4177.42)
insert into product(id, name, corp_id, p_type) value(663, '삼성클래식인도중소형FOCUS연금증권자투자신탁UH[주식]', 58, 'FUND')
insert into fund_product(id, price) value(663, 4155.14)
insert into product(id, name, corp_id, p_type) value(664, '삼성인도중소형FOCUS증권자투자신탁UH[주식]_Cw', 58, 'FUND')
insert into fund_product(id, price) value(664, 4213.26)
insert into product(id, name, corp_id, p_type) value(665, '삼성KODEX미국반도체MV증권상장지수투자신탁[주식]', 58, 'FUND')
insert into fund_product(id, price) value(665, 22962.95)
insert into product(id, name, corp_id, p_type) value(666, '삼성인도중소형FOCUS증권모투자신탁[주식]', 58, 'FUND')
insert into fund_product(id, price) value(666, 4215.64)
insert into product(id, name, corp_id, p_type) value(667, '삼성인도중소형FOCUS증권자투자신탁UH[주식]', 58, 'FUND')
insert into fund_product(id, price) value(667, 4177.42)
insert into product(id, name, corp_id, p_type) value(668, '삼성클래식인도중소형FOCUS연금증권자투자신탁UH[주식]', 58, 'FUND')
insert into fund_product(id, price) value(668, 4155.14)
insert into product(id, name, corp_id, p_type) value(669, '삼성인도중소형FOCUS증권자투자신탁UH[주식]_Cw', 58, 'FUND')
insert into fund_product(id, price) value(669, 4213.26)
insert into product(id, name, corp_id, p_type) value(670, '삼성KODEX미국반도체MV증권상장지수투자신탁[주식]', 58, 'FUND')
insert into fund_product(id, price) value(670, 22962.95)
insert into product(id, name, corp_id, p_type) value(671, '삼성인도중소형FOCUS증권모투자신탁[주식]', 58, 'FUND')
insert into fund_product(id, price) value(671, 4215.64)
insert into product(id, name, corp_id, p_type) value(672, '삼성인도중소형FOCUS증권자투자신탁UH[주식]', 58, 'FUND')
insert into fund_product(id, price) value(672, 4177.42)
insert into product(id, name, corp_id, p_type) value(673, '삼성클래식인도중소형FOCUS연금증권자투자신탁UH[주식]', 58, 'FUND')
insert into fund_product(id, price) value(673, 4155.14)
insert into product(id, name, corp_id, p_type) value(674, '삼성인도중소형FOCUS증권자투자신탁UH[주식]_Cw', 58, 'FUND')
insert into fund_product(id, price) value(674, 4213.26)
insert into product(id, name, corp_id, p_type) value(675, '삼성KODEX미국반도체MV증권상장지수투자신탁[주식]', 58, 'FUND')
insert into fund_product(id, price) value(675, 22962.95)
insert into product(id, name, corp_id, p_type) value(676, '삼성인도중소형FOCUS증권모투자신탁[주식]', 58, 'FUND')
insert into fund_product(id, price) value(676, 4215.64)
insert into product(id, name, corp_id, p_type) value(677, '삼성인도중소형FOCUS증권자투자신탁UH[주식]', 58, 'FUND')
insert into fund_product(id, price) value(677, 4177.42)
insert into product(id, name, corp_id, p_type) value(678, '삼성클래식인도중소형FOCUS연금증권자투자신탁UH[주식]', 58, 'FUND')
insert into fund_product(id, price) value(678, 4155.14)
insert into product(id, name, corp_id, p_type) value(679, '삼성인도중소형FOCUS증권자투자신탁UH[주식]_Cw', 58, 'FUND')
insert into fund_product(id, price) value(679, 4213.26)
insert into product(id, name, corp_id, p_type) value(680, '삼성KODEX미국반도체MV증권상장지수투자신탁[주식]', 58, 'FUND')
insert into fund_product(id, price) value(680, 22962.95)
insert into product(id, name, corp_id, p_type) value(681, '삼성인도중소형FOCUS증권모투자신탁[주식]', 58, 'FUND')
insert into fund_product(id, price) value(681, 4215.64)
insert into product(id, name, corp_id, p_type) value(682, '삼성인도중소형FOCUS증권자투자신탁UH[주식]', 58, 'FUND')
insert into fund_product(id, price) value(682, 4177.42)
insert into product(id, name, corp_id, p_type) value(683, '삼성클래식인도중소형FOCUS연금증권자투자신탁UH[주식]', 58, 'FUND')
insert into fund_product(id, price) value(683, 4155.14)
insert into product(id, name, corp_id, p_type) value(684, '삼성인도중소형FOCUS증권자투자신탁UH[주식]_Cw', 58, 'FUND')
insert into fund_product(id, price) value(684, 4213.26)
insert into product(id, name, corp_id, p_type) value(685, 'KBKBSTAR글로벌원자력iSelect증권상장지수투자신탁(주식)', 59, 'FUND')
insert into fund_product(id, price) value(685, 17790.97)
insert into product(id, name, corp_id, p_type) value(686, 'KBKBSTAR글로벌메타버스Moorgate증권상장지수투자신탁(주식)', 59, 'FUND')
insert into fund_product(id, price) value(686, 14006.96)
insert into product(id, name, corp_id, p_type) value(687, 'KBKBSTAR비메모리반도체액티브증권상장지수투자신탁(주식)', 59, 'FUND')
insert into fund_product(id, price) value(687, 13735.98)
insert into product(id, name, corp_id, p_type) value(688, 'KB지수연계증권투자신탁230(ELS-파생형)(운용)', 59, 'FUND')
insert into fund_product(id, price) value(688, 1129.36)
insert into product(id, name, corp_id, p_type) value(689, 'KB지수연계증권투자신탁230(ELS-파생형)A', 59, 'FUND')
insert into fund_product(id, price) value(689, 1128.94)
insert into product(id, name, corp_id, p_type) value(690, 'KBKBSTAR글로벌원자력iSelect증권상장지수투자신탁(주식)', 59, 'FUND')
insert into fund_product(id, price) value(690, 17790.97)
insert into product(id, name, corp_id, p_type) value(691, 'KBKBSTAR글로벌메타버스Moorgate증권상장지수투자신탁(주식)', 59, 'FUND')
insert into fund_product(id, price) value(691, 14006.96)
insert into product(id, name, corp_id, p_type) value(692, 'KBKBSTAR비메모리반도체액티브증권상장지수투자신탁(주식)', 59, 'FUND')
insert into fund_product(id, price) value(692, 13735.98)
insert into product(id, name, corp_id, p_type) value(693, 'KB지수연계증권투자신탁230(ELS-파생형)(운용)', 59, 'FUND')
insert into fund_product(id, price) value(693, 1129.36)
insert into product(id, name, corp_id, p_type) value(694, 'KB지수연계증권투자신탁230(ELS-파생형)A', 59, 'FUND')
insert into fund_product(id, price) value(694, 1128.94)
insert into product(id, name, corp_id, p_type) value(695, 'KBKBSTAR글로벌원자력iSelect증권상장지수투자신탁(주식)', 59, 'FUND')
insert into fund_product(id, price) value(695, 17790.97)
insert into product(id, name, corp_id, p_type) value(696, 'KBKBSTAR글로벌메타버스Moorgate증권상장지수투자신탁(주식)', 59, 'FUND')
insert into fund_product(id, price) value(696, 14006.96)
insert into product(id, name, corp_id, p_type) value(697, 'KBKBSTAR비메모리반도체액티브증권상장지수투자신탁(주식)', 59, 'FUND')
insert into fund_product(id, price) value(697, 13735.98)
insert into product(id, name, corp_id, p_type) value(698, 'KB지수연계증권투자신탁230(ELS-파생형)(운용)', 59, 'FUND')
insert into fund_product(id, price) value(698, 1129.36)
insert into product(id, name, corp_id, p_type) value(699, 'KB지수연계증권투자신탁230(ELS-파생형)A', 59, 'FUND')
insert into fund_product(id, price) value(699, 1128.94)
insert into product(id, name, corp_id, p_type) value(700, 'KBKBSTAR글로벌원자력iSelect증권상장지수투자신탁(주식)', 59, 'FUND')
insert into fund_product(id, price) value(700, 17790.97)
insert into product(id, name, corp_id, p_type) value(701, 'KBKBSTAR글로벌메타버스Moorgate증권상장지수투자신탁(주식)', 59, 'FUND')
insert into fund_product(id, price) value(701, 14006.96)
insert into product(id, name, corp_id, p_type) value(702, 'KBKBSTAR비메모리반도체액티브증권상장지수투자신탁(주식)', 59, 'FUND')
insert into fund_product(id, price) value(702, 13735.98)
insert into product(id, name, corp_id, p_type) value(703, 'KB지수연계증권투자신탁230(ELS-파생형)(운용)', 59, 'FUND')
insert into fund_product(id, price) value(703, 1129.36)
insert into product(id, name, corp_id, p_type) value(704, 'KB지수연계증권투자신탁230(ELS-파생형)A', 59, 'FUND')
insert into fund_product(id, price) value(704, 1128.94)
insert into product(id, name, corp_id, p_type) value(705, 'KBKBSTAR글로벌원자력iSelect증권상장지수투자신탁(주식)', 59, 'FUND')
insert into fund_product(id, price) value(705, 17790.97)
insert into product(id, name, corp_id, p_type) value(706, 'KBKBSTAR글로벌메타버스Moorgate증권상장지수투자신탁(주식)', 59, 'FUND')
insert into fund_product(id, price) value(706, 14006.96)
insert into product(id, name, corp_id, p_type) value(707, 'KBKBSTAR비메모리반도체액티브증권상장지수투자신탁(주식)', 59, 'FUND')
insert into fund_product(id, price) value(707, 13735.98)
insert into product(id, name, corp_id, p_type) value(708, 'KB지수연계증권투자신탁230(ELS-파생형)(운용)', 59, 'FUND')
insert into fund_product(id, price) value(708, 1129.36)
insert into product(id, name, corp_id, p_type) value(709, 'KB지수연계증권투자신탁230(ELS-파생형)A', 59, 'FUND')
insert into fund_product(id, price) value(709, 1128.94)
