insert into product(id, name, corp_id, p_type) value(330, '미래에셋TIGER필라델피아반도체레버리지증권상장지수투자신탁(주식혼합-파생형)(합성)', 60, 'FUND')
insert into fund_product(id, price) value(330, 26382.79)
insert into product(id, name, corp_id, p_type) value(331, '미래에셋TIGER미국나스닥100레버리지증권상장지수투자신탁(주식혼합-파생형)(합성)', 60, 'FUND')
insert into fund_product(id, price) value(331, 19057.81)
insert into product(id, name, corp_id, p_type) value(332, '미래에셋인디아인프라섹터증권모투자신탁(주식)', 60, 'FUND')
insert into fund_product(id, price) value(332, 2775.85)
insert into product(id, name, corp_id, p_type) value(333, '미래에셋연금인디아인프라증권자투자신탁 1(주식)', 60, 'FUND')
insert into fund_product(id, price) value(333, 1130.22)
insert into product(id, name, corp_id, p_type) value(334, '미래에셋인디아인프라섹터증권자투자신탁 1(주식)', 60, 'FUND')
insert into fund_product(id, price) value(334, 3060.99)
insert into product(id, name, corp_id, p_type) value(335, '신한SOL한국형글로벌반도체액티브증권상장지수투자신탁[주식]', 61, 'FUND')
insert into fund_product(id, price) value(335, 18833.21)
insert into product(id, name, corp_id, p_type) value(336, '신한인디아증권모투자신탁[주식]', 61, 'FUND')
insert into fund_product(id, price) value(336, 2850.62)
insert into product(id, name, corp_id, p_type) value(337, '신한SOLAI반도체소부장증권상장지수투자신탁[주식]', 61, 'FUND')
insert into fund_product(id, price) value(337, 15731.5)
insert into product(id, name, corp_id, p_type) value(338, '신한동유럽플러스증권모투자신탁[주식]', 61, 'FUND')
insert into fund_product(id, price) value(338, 947.28)
insert into product(id, name, corp_id, p_type) value(339, '신한동유럽플러스증권자투자신탁(H)[주식](종류)', 61, 'FUND')
insert into fund_product(id, price) value(339, 671.13)
insert into product(id, name, corp_id, p_type) value(340, '삼성KODEX미국반도체MV증권상장지수투자신탁[주식]', 62, 'FUND')
insert into fund_product(id, price) value(340, 22962.95)
insert into product(id, name, corp_id, p_type) value(341, '삼성인도중소형FOCUS증권모투자신탁[주식]', 62, 'FUND')
insert into fund_product(id, price) value(341, 4215.64)
insert into product(id, name, corp_id, p_type) value(342, '삼성인도중소형FOCUS증권자투자신탁UH[주식]', 62, 'FUND')
insert into fund_product(id, price) value(342, 4177.42)
insert into product(id, name, corp_id, p_type) value(343, '삼성클래식인도중소형FOCUS연금증권자투자신탁UH[주식]', 62, 'FUND')
insert into fund_product(id, price) value(343, 4155.14)
insert into product(id, name, corp_id, p_type) value(344, '삼성인도중소형FOCUS증권자투자신탁UH[주식]_Cw', 62, 'FUND')
insert into fund_product(id, price) value(344, 4213.26)
insert into product(id, name, corp_id, p_type) value(345, 'KBKBSTAR글로벌원자력iSelect증권상장지수투자신탁(주식)', 63, 'FUND')
insert into fund_product(id, price) value(345, 17790.97)
insert into product(id, name, corp_id, p_type) value(346, 'KBKBSTAR글로벌메타버스Moorgate증권상장지수투자신탁(주식)', 63, 'FUND')
insert into fund_product(id, price) value(346, 14006.96)
insert into product(id, name, corp_id, p_type) value(347, 'KBKBSTAR비메모리반도체액티브증권상장지수투자신탁(주식)', 63, 'FUND')
insert into fund_product(id, price) value(347, 13735.98)
insert into product(id, name, corp_id, p_type) value(348, 'KB지수연계증권투자신탁230(ELS-파생형)(운용)', 63, 'FUND')
insert into fund_product(id, price) value(348, 1129.36)
insert into product(id, name, corp_id, p_type) value(349, 'KB지수연계증권투자신탁230(ELS-파생형)A', 63, 'FUND')
insert into fund_product(id, price) value(349, 1128.94)
